### ISSUE TITLE
Error after install plugin in android

### ISSUE THREAD

**Issue by divyanshupathak** [gre/react-native-view-shot#105]
### bug report

Please provide solution as soon as possible Its **URGENT** for my App

#### Version & Platform

```bash
react-native@0.48.3
react-native-view-shot@2.1.0
android-version@6.0.1
window 10 64 bit
```

**Platform:**  Android

#### Steps to reproduce the behavior
Install the versions of react native and react-native-view-shot (As described above) and just create a sample app and run in android

### Screenshot of error
![error](https://user-images.githubusercontent.com/19850600/30867342-4de65208-a2f9-11e7-866a-0bf28d5b001d.PNG)

**Comment by gre** [comment]
have you run `react-native link react-native-view-shot` ? it sounds like there is an issue in the android build config?

**Comment by divyanshupathak** [comment]
yes. I run this command `react-native link react-native-view-shot`

**Comment by enieber** [comment]
to fix this error I add this row code in android/app/build.gradle

```
dependencies {
    compile project(':react-native-view-shot')
    ....
}
```

**Comment by gre** [comment]
yes there might be a problem that `link` is not enough and you will have to link the library by yourself (refer to RN doc)

thanks

**Comment by leoabacade** [comment]
@gre could you provide the documents link of android manual installation?
