### ISSUE TITLE
Android 截屏 Image 必须下拉到渲染才出来。否则是以白屏代替

### ISSUE THREAD

**Issue by jiushicheng** [gre/react-native-view-shot#109]
#### Version & Platform

```bash
npm ls react-native react-native-view-shot #<- PASTE CMD RESULT IN HERE
```

**Platform:** iOS? Android?

**Comment by gre** [comment]
我会说汉语一点点可以不太懂你的说，你可不可以用英语写？

**Comment by jiushicheng** [comment]
Android screenshots, screenshots if very long, no screenshots of Image tags in the visual range of the mobile phone after being replaced by the white area, but not in normal pictures (only the visual range of mobile phone down to the Image tag region, Image was shown to normal screen. )

**Comment by jiushicheng** [comment]
Solved it,Call the twice this.refs.viewShot.capture() method。but, the new question is in iphone 7(system ios 10.2) Screenshots result is captures blank(in real machine) or Blur image(in Simulator)

**Comment by gre** [comment]
how big is the screenshot you attempt to take? There are probably some size limitations

**Comment by jiushicheng** [comment]
the screenshot height about 80929(Xcode result [432:80929] [PERF ASSETS] Loading image at size {1125, 9485}, which is larger than the screen size {1125, 2001}),How many the size limitations ？ can't the limitations be canceled?

**Comment by gre** [comment]
AFAIK the limitations are not clearly specified. On Android, it looks like you can't create a Bitmap bigger than the number of pixels of the screen. on iOS, i'm not sure.

It's hard for me to investigate what bug you are reaching, any chance to have a minimal example that reproduce the problem so we can test?

**Comment by jiushicheng** [comment]
In your Project Example (react-native-view-shot/example/).Run iOS platform, if ScrollView Including a lot of(number6,7) long pictures, after the screenshot, save the local album, reply to the present

**Comment by jiushicheng** [comment]
<ScrollView style={[style.container, { marginBottom: 50 }]}>
          <ViewShot
            ref={(self) => { this.viewShot = self; }}
            options={{ format: 'jpg', quality: 0.9 }}
          >
       ..........
            <View style={[style.module, { flex: 1 }]}>
              <View style={[style.moduleTitle, style.flexRowLeft]}>
                <Text style={style.leftBar} />
                <Text>产品详情</Text>
              </View>

              <View style={[style.moduleContent, { paddingHorizontal: 0 }]}>
                {
                  productPics.length > 0 ? productPics.map((item, index) => (
                    <ImageView
                      key={item}
                      style={[
                        styles.productImage, {
                          height: this.state[`image_${index}`]
                            ? (this.state[`image_${index}_height`] * ScreenWidth) /
                          this.state[`image_${index}_width`]
                          : ScreenWidth * 0.8,
                        }]}
                      url={{ uri: item }}
                      imageMode={2}
                    />
                  )) : <Text>暂无数据</Text>
                }
              </View>
            </View>

            <View style={styles.viewBorder} />
            <View style={[style.module]}>
              <View style={[style.moduleTitle, style.flexRowLeft]}>
                <Text style={style.leftBar} />
                <Text>申请流程</Text>
              </View>

              <View style={[style.moduleContent, { paddingHorizontal: 0 }]}>
                {
                  processPics.length > 0 ? processPics.map((item, index) => (
                    <ImageView
                      key={item}
                      style={[
                        styles.productImage, {
                          height: this.state[`images_${index}`]
                            ? (this.state[`images_${index}_height`] * ScreenWidth) /
                          this.state[`images_${index}_width`]
                          : ScreenWidth * 0.8,
                        }]}
                      url={{ uri: item }}
                      imageMode={2}
                    />
                  )) : <Text>暂无数据</Text>
                }
              </View>
            </View>
            <View style={styles.viewBorder} />
          </ViewShot>
        </ScrollView>
ImageView is Pre loading of pictures。 If processPics including 6,7items.call this.refs.viewShot.capture（）,result is captures blank(ios platform)

**Comment by gre** [comment]
好，我现在忙，我想下个周末看一看。

**Comment by jiushicheng** [comment]
ok, Thank you very much. If you are free, please take a look.

**Comment by jiushicheng** [comment]
hi. solved it.you can look it . http://www.jianshu.com/p/0cb9d1186b14

**Comment by gre** [comment]
do you want to try to send a PR to fix this in the present library? not sure what is wrong

**Comment by jiushicheng** [comment]
ok! PR has been sent

**Comment by Githubzxw** [comment]
@jiushicheng 请问，你怎么解决这个问题的， 图片太长截取的是白屏。

**Comment by Joan1106web** [comment]
> Android 还是 iOS 白屏

Android截屏，屏幕设置背景色，并没有用图片，还是白底代替

**Comment by cielu** [comment]
@Joan1106web  老哥，你的安卓白底代替的问题解决了吗？

**Comment by Joan1106web** [comment]
解决了，不过我的问题是生成二维码的组件的不支持，换了一个就可以了
