### ISSUE TITLE
Possible with Expo/create-react-native-app

### ISSUE THREAD

**Issue by jhalborg** [gre/react-native-view-shot#110]
### feature request
Hello, 

Would it be possible to modify this package to support Expo/crna apps, i.e. not linking?

**Comment by gre** [comment]
I'm not sure to understand what you mean. if you mean to use this package in Expo, then yes it is possible, however the current expo is outdated with this new version (v2) so you might want to stick on the v1 until this is supported. see also https://github.com/gre/react-native-view-shot/issues/106#issuecomment-335261154

**Comment by jhalborg** [comment]
Oh, my bad - I honestly didn't try - I just saw that the installation instructions said to `react-native link` which is not possible with Expo

**Comment by gre** [comment]
ok :) so my answer above will be good for now, hopefully v2 should work

**Comment by jhalborg** [comment]
I'm not sure I understand. You mean that it's not working with Expo apps as of now, but hope to implement it in v2?

**Comment by gre** [comment]
AFAIK Expo currently bring support for react-native-view-shot @ 1.x
but does not yet support @ 2.x

it's up to expo to eventually support this library v2. nothing I can do
