### ISSUE TITLE
implicit declaration of function 'RCTGetUIManagerQueue' is invalid in C99

### ISSUE THREAD

**Issue by sibelius** [gre/react-native-view-shot#114]
I'm getting this error on latest xcode 9.1 and latest react-native-view-shot 2.1.1

❌  app/node_modules/react-native-view-shot/ios/RNViewShot.m:19:10: implicit declaration of function 'RCTGetUIManagerQueue' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

  return RCTGetUIManagerQueue();
                ^

❌  app/node_modules/react-native-view-shot/ios/RNViewShot.m:19:10: implicit conversion of 'int' to 'dispatch_queue_t' (aka 'NSObject<OS_dispatch_queue> *') is disallowed with ARC

  return RCTGetUIManagerQueue();

**Comment by gre** [comment]
maybe need to add a `#import "RCTUIManagerUtils.h"` or probably more `#import <React/RCTUIManagerUtils.h>`

would you like to try and submit a PR ? thanks

**Comment by sibelius** [comment]
I thought this https://github.com/gre/react-native-view-shot/pull/108 would fix this

**Comment by Jonovono** [comment]
Got the same error after updating react and react native. Fix above works.

**Comment by gre** [comment]
does that means the `#if __has_include(<React/RCTUIManagerUtils.h>)` does not work as expected?
