### ISSUE TITLE
undefined is not an object 'this.refs.viewShot'

### ISSUE THREAD

**Issue by macelii** [gre/react-native-view-shot#115]
#### Version & Platform
```
RN 49.5, Simulator iPhone 8 iOS 11
```

```bash
npm ls react-native react-native-view-shot └── react-native-view-shot@2.1.1
```

**Platform:** iOS? Android?
```
iOS
```

#### Steps to reproduce the behavior

Hello there,
Thanks for this components, I am not able to launch with minimum setup and keep getting undefined is not an object 'this.refs.viewShot'. Am I missing something?

What I have is the something like this

```
import ViewShot from "react-native-view-shot";

save() {
      this.refs.viewShot.capture().then(uri => {
      console.log("do something with ", uri);
    });
}

render() {
  return (
    <View>
        <ViewShot ref="viewShot" options={{ format: "jpg", quality: 0.9 }}>
          <Image></Image>
        </ViewShot>
        <TouchableOpacity onPress={this.save}>
          <Text>Take this</Text>
        </TouchableOpacity>
    </View>
  )
}
```

**Comment by macelii** [comment]
duplicate of issue 106
https://github.com/gre/react-native-view-shot/issues/106

**Comment by macelii** [comment]
react-native link outputs the success but you still need to  manually link the component to solve the problem.
RN 49, iOS, react-native-view-shot@2.1.1

**Comment by tirrorex** [comment]
@macelii could you add that to the documentation please?

**Comment by macelii** [comment]
Hello @tirrorex 
I think the author has already done that as he stated in issue 106
Cheers

**Comment by tirrorex** [comment]
@macelii nothing in the readme on master
