### ISSUE TITLE
Cannot read property 'takeSnapshot' of undefined 

### ISSUE THREAD

**Issue by jophyson93** [gre/react-native-view-shot#12]
Hey so I'm having this issue. I can't seem to figure out if this is something that I'm doing wrong or an actual issue with the package. Please help! 
![simulator screen shot sep 29 2016 6 00 06 pm](https://cloud.githubusercontent.com/assets/8178911/18975313/d44a3600-866e-11e6-98a7-049f2fb0fc78.png)

**The code:**

`
snapshot = view => () =>
    takeSnapshot(this.refs[view], {
      format: "jpeg",
      quality: 0.8
    })
    .then(
      uri => console.log("Image saved to", uri),
      error => console.error("Oops, snapshot failed", error)
    )
`

**and**

`
<View ref = "main">
          <Button rounded danger
            style = {{ width: 55, height: 55 }}
            onPress = {this.snapshot("main")}
          >
            test
          </Button>
</View>
`

**Comment by gre** [comment]
How do you import takeSnapshot?

Le 30 sept. 2016 1:03 AM, "Jophy Johnson" <notifications@github.com> a
écrit :

**Comment by gre** [comment]
make sure you do 
```
import RNViewShot from "react-native-view-shot";
RNViewShot.takeSnapshot(...)
```

or

```
import {takeSnapshot} from "react-native-view-shot";
```

**Comment by tomchambers2** [comment]
I had this issue as well, had installed everything. Just needed to close xcode and restart the iOS simulator. Presumably that picked up the native code part.

**Comment by mrThinBone** [comment]
Did all of the steps including manually install for android, but I got same error.
