### ISSUE TITLE
Android: error: package fr.greweb.reactnativeviewshot does not exist

### ISSUE THREAD

**Issue by benniao-chen** [gre/react-native-view-shot#122]
![image](https://user-images.githubusercontent.com/23418117/33010988-7584b61c-ce17-11e7-9eb4-9b0b37b93199.png)

**package.json**
![image](https://user-images.githubusercontent.com/23418117/33011003-85f69722-ce17-11e7-8f4d-13ea26158c65.png)

**MainApplication.java**
![image](https://user-images.githubusercontent.com/23418117/33011046-ab3aa118-ce17-11e7-8a2b-03755ccac3f4.png)

**Comment by fufuninja** [comment]
Hi how did u solve this?

**Comment by MinhUITk9** [comment]
Hi how did u solve this? I've the same problem

**Comment by MinhUITk9** [comment]
@gre can you help me, please? I've exact the same problem :(

**Comment by fufuninja** [comment]
Make sure it's correctly linked. Check your android/app/build.gradle if it includes 'compile project(':react-native-view-shot')'

**Comment by MinhUITk9** [comment]
Thanks @fufuninja , that help me ^_^
