### ISSUE TITLE
Please add possibility to crop image

### ISSUE THREAD

**Issue by code-by** [gre/react-native-view-shot#123]
It will be nice to have such feature like crop here.

**Comment by gre** [comment]
won't be solved by this library, however there is already this feature in React Native:

https://facebook.github.io/react-native/docs/imageeditor.html

so you can do this:

```js
takeSnapshot(..)
.then(uri => new Promise((success,failure)=>ImageEditor.cropImage(uri,{...optionsHere},success,failure))
.then(uriCropped=>...)
```
