### ISSUE TITLE
nodeHandle.getHostNode is not a function.

### ISSUE THREAD

**Issue by ershubhamgarg** [gre/react-native-view-shot#124]
@gre I am getting this error : 'nodeHandle.getHostNode is not a function' when I am using captureRef as : 
captureRef('viewShot', {
            format: 'jpg',
            quality: 0.8
        })
            .then(
                uri => console.log('Image saved to', uri),
                error => console.error('Oops, snapshot failed', error)
            );

'viewShot' is the reference to react native View.

**Comment by gre** [comment]
Hi,

the provided code is wrong, you need to give to captureRef a reference, not a string.

like `this.refs.viewShot`
