### ISSUE TITLE
in android   take shot will crash   the debug info is trying to resolve view with 320 which doesn't exist

### ISSUE THREAD

**Issue by afeng159** [gre/react-native-view-shot#126]

**Comment by gre** [comment]
can you share your code? it is likely you are trying to snapshot a view that does not have a Android.View representation

**Comment by afeng159** [comment]
thanks ,just now，I try collapsable={false}       it's useful

**Comment by gre** [comment]
cool, yeah if it's a simple View , without a collapsable=false, on android it would not create an actual View in some cases, as written in the README

 thanks
