### ISSUE TITLE
captureScreen doesn't capture the good screen

### ISSUE THREAD

**Issue by AlexandreMaistret** [gre/react-native-view-shot#130]
Hi everybody !

I'm facing a problem with the function captureScreen(). Indeed, it doesn't capture the screen on my device but a another page of my app. 

However, I'm using this function in another page of my app, and it works well. I don't understand at all.

This is my function : 

` captureScreen({
        format: "jpg", quality: 0.7, width: SCREEN_WIDTH, height: SCREEN_HEIGHT,
       })
      .then((uri) => {
        console.log("Image saved to", uri);
        this.props.navigation.navigate('ParametersPhoto');
      })
      .catch((error) => console.error("Oops, snapshot failed", error)
      );`

I'm not using a single <ViewShot /> in my app, just to say.
 
I'm using react-navigation to connect my differents pages of my app.

So if somebody had already got this problem and find a solution :)

**Comment by gre** [comment]
I don't really understand your code. why is there a navigate chained after the captureScreen? you want to capture the previous screen or the new ParametersPhoto ?

**Comment by AlexandreMaistret** [comment]
Hi @gre !

The code might be clearer just below, it didn't do the indentation on my first post.

`captureScreen({ format: "jpg", quality: 0.7, width: SCREEN_WIDTH, height: SCREEN_HEIGHT }) 
.then((uri) => { 
         console.log("Image saved to", uri); 
         this.props.navigation.navigate('ParametersPhoto'); 
}) .catch((error) => console.error("Oops, snapshot failed", error) );`

The **navigate()** is executed just after the capture is taken. I have checked with the logs on google chrome, and the navigate is executed only when it gets a "uri".

So the code does this : 

_EditorPhotoScreen_ (screen which I want to take a capture)
  **=>**   
**captureScreen()** is execute and should take a capture of _EditorPhotoScreen_
  **=>**
when uri is received by the **captureScreen()**, it moves to _ParametersPhoto_
  **=>**
_ParametersPhoto_

And it always captures this last screen _ParametersPhoto_


I have tried the function **captureScreen()** without the **navigate('ParametersPhoto')**, so it stays on the screen which is normally captured ( _EditorPhotoScreen_  ) and it still captures the screen _ParametersPhoto_ even if the _ParametersPhoto_ screen is never shown on the device. 

So that's why I don't understand at all. The function capture a screen that's not even shown to the user.

**Comment by gre** [comment]
thanks for the explanation.
that sounds like there is a bug that the promise is redeemed to early , can you try to add a delay before navigate happen to see if that fix it? we'll need to investigate why the promise is redeemed earlier. (PR accepted, otherwise I'll probably only have time in a few weeks)

can you tell me if it happens on iOS or Android, or both?

**Comment by AlexandreMaistret** [comment]
I will try it. But just to say, even if there is no _navigate()_, **the captureScreen()** capture another screen than the one displayed on the device, so like this : 

_EditorPhotoScreen_ (screen which I want to take a capture)
=>
**captureScreen()** is execute and should take a capture of _EditorPhotoScreen_
=>
when uri is received, execute **console.log("Image saved to", uri);** , and stay on  _EditorPhotoScreen_
=>
_EditorPhotoScreen_

And it still captures _ParametersPhoto_

I have tested only on Android, on two devices, so Android 7.1.1 and Android 6.0.1., same problem.
(To see the photo, I use **saveToCameraRoll(tag, type?)**, just to explain)

**Comment by gre** [comment]
oh ok. weird.

**Comment by AlexandreMaistret** [comment]
Hi @gre !

So I change my code to make it captures the good screen and I think I can explain why it captured another screen before : 

- when my first page _EditorPhotoScreen_ shows up to the user, the page _ParametersPhoto_ rerender in background since it has new data.
- I believe captureScreen() capture the last screen that has rendered on the app even if it is not shown to the user

**Comment by gre** [comment]
it would be great to have a minimal example to reproduce the problem.

I'm not sure where in the code it is wrong, there are a few places to investigate: 
- is this the correct way to grab the "window view" https://github.com/gre/react-native-view-shot/blob/master/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java#L82
- wondering if this code have a side effect, might want to comment it out to test: https://github.com/gre/react-native-view-shot/blob/master/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java#L177-L185

**Comment by ricardochen** [comment]
I have the same problem, it's capturing the "root" of the navigation stack

**Comment by gre** [comment]
Would that be related to the use of a Modal?

**Comment by gre** [comment]
closing until having a minimal/reproductible example.

Best is to add a screen in the `example` app of this project.

**Comment by abhi06991** [comment]
> I have the same problem, it's capturing the "root" of the navigation stack

Exactly...this is capturing the root of the stack :(
