### ISSUE TITLE
The picture can't be shared in the current app cache area to the other app how to modify the path

### ISSUE THREAD

**Issue by mochixuan** [gre/react-native-view-shot#133]
The picture is in the cache path and can't be shared with other App, in the Android

**Comment by mochixuan** [comment]
How to modify the path, can you change the path, but can you leave an interface？

**Comment by gre** [comment]
use another library (or your own custom native module) to move the file somewhere else.
This library does not handle file saving because it's actually not so trivial and I prefer it is delegated to library like `react-native-fs` 

see https://github.com/gre/react-native-view-shot#saving-to-a-file
