### ISSUE TITLE
Trying to resolve view with tag 235 which doesn't exist resolveView   

### ISSUE THREAD

**Issue by chen236310** [gre/react-native-view-shot#134]
on  android,will be get this error :Trying to resolve view with tag 235 which doesn't exist resolveView  .
<View ref='viewShot'>
...
</View>
To resolve this error ,Add style to view, and specify the backgroundColor attribute

**Comment by gre** [comment]
i'm not seeing the code,
also this probably help: https://github.com/gre/react-native-view-shot#on-android-getting-trying-to-resolve-view-with-tag-tagid-which-doesnt-exist
