### ISSUE TITLE
How to pass a "reference to a Component" into captureRef?

### ISSUE THREAD

**Issue by KeyeZhang** [gre/react-native-view-shot#136]
I am wondering how do we pass a reference to a component into captureRef? Here in the first line of my code I passed in the name of one of my components "PostView"(the component this snippet of code lives in), and it gave me back a empty image. 

In the console, the error message was:
 **_" Error: findNodeHandle failed to resolve view=function PostView(props){ .... } "_**
In previous issue, passing in like <PostView /> instead also would not work because it is the component itself. So I am wondering how do we pass a reference to a component into captureRef? 

```
captureRef(PostView, this.state.value).then((res) =>
            this.state.value.result !== "tmpfile"
            ? res
            : new Promise((success, failure) =>
                Image.getSize(
                  res,
                  (width, height) => (
                    console.log(res, width, height), success(res)
                  ),
                  failure
                )
            )
        )
        .then((res) => {
            //....
        })
        .catch((error) => {
              //....
            }
        );
```

**Comment by gre** [comment]
captureRef takes an **React Element reference**, not a React Component, nor a React Element.

so you actually need to have an element rendered & mounted and gets its reference. 

```
captureIt = () => {
  captureRef(this._ref, ...).then(...)
}

render() {
  return <View ref={ref => { this._ref=ref }}>...</View>
}
```

**Comment by KeyeZhang** [comment]
@gre Thank you so much it works!
