### ISSUE TITLE
image artifacts on real ios device but not simulator

### ISSUE THREAD

**Issue by jcharbo** [gre/react-native-view-shot#137]
Hi, I'm using the latest version on RN 52.  When I save a png or jpg of text on a transparent view I get strange artifacts on the real device but not on the simulator.  The screenshot below shows 2 files, the one on the left is from a real iphone 8 and the one on the right is from an iphone 8 simulator.  If I add a background color to the view then the issue goes away.  Does anyone have any suggestions?
thanks
![screen shot 2018-02-20 at 12 20 00 pm](https://user-images.githubusercontent.com/6372919/36441818-639c8456-1639-11e8-88d2-90111717b096.png)

**Comment by jcharbo** [comment]
Additionally, it only occurs when the text is white.  If I add any color to the text the issue resolves.

**Comment by gre** [comment]
this is likely related to alpha channel. can you afford using a background color instead of having opacity?
i'm not sure there are anything we can fix from this library
