### ISSUE TITLE
Android react-native-qrcode  Cropped to obtain the picture is a blank figure

### ISSUE THREAD

**Issue by wangxiaohuang007** [gre/react-native-view-shot#139]
#### Version & Platform

```bash
npm ls react-native react-native-view-shot #<- PASTE CMD RESULT IN HERE
```

**Platform:** iOS? Android?

**Comment by gre** [comment]
please provide more detail. how do you try to capture it? have you tried with the `<ViewShot ref="viewShot" options={{ format: "jpg", quality: 0.9 }}>` element?

**Comment by wangxiaohuang007** [comment]
<QRCode  value={this.state.codeUrl+this.state.userId} size={332} bgColor="#000" fgColor="#fff"/>
cropped to obtain the picture is a blank figure

**Comment by wangxiaohuang007** [comment]
<QRCode  value={this.state.codeUrl+this.state.userId} size={332} bgColor="#000" fgColor="#fff"/>

**Comment by gre** [comment]
how to do you capture it? show me the code. if you direct use captureRef() function on the webview ref, you might fall into this https://github.com/gre/react-native-view-shot#interoperability-table (see the `1`) forcing you to do `<View collapsable={false}>` and snapshot this, this is why we have a higher level API with `<ViewShot>`, 

have you tried to do this kind of thing:

```js
class Example extends Component {
  onQRCodeReadyToCapture = () => {
    this.refs.viewShot.capture().then(uri => {
      console.log("do something with ", uri);
    })
  };
  render() {
    return (
      <ViewShot ref="viewShot">
        <QRCode ...>
      </ViewShot>
    );
  }
}
```

i'm not sure when you can call onQRCodeReadyToCapture, if it can be done at did mount time ?

**Comment by wangxiaohuang007** [comment]
I've tried your suggestion, but it doesn't work. I think it should be a component incompatibility problem.

**Comment by QiYunMeng1126** [comment]
I have that problem, some android  don't work,  cropped to obtain the picture is a blank figure.
my code:
<ViewShot style={styles.codeContanier}
                          ref={'code'}
                          options={{ format: "png", quality: 1 }}>
          <QRCode value={base64Icon}
                            size={fixWidth(260) - 16}
                            style={{justifyContent: 'center', alignItems: 'center'}}>
          </QRCode>
</ViewShot>

**Comment by callcter** [comment]
use react-native-qrcode-svg to replace react-native-qrcode

**Comment by thaiphamvan** [comment]
> use react-native-qrcode-svg to replace react-native-qrcode

solve it ?

**Comment by callcter** [comment]
> > use react-native-qrcode-svg to replace react-native-qrcode
> 
> solve it ?

yeah
