### ISSUE TITLE
Captured view not seen any more

### ISSUE THREAD

**Issue by billywanmf** [gre/react-native-view-shot#14]
Hi,

I successfully capture the view as png/jpeg in react-native in Android.

I captured the view as file and saved for later use. The view contain image and text. But the original view in the screen disappeared (become empty in the screen) after captured the view.

I want to display the same view (not captured image) even after captured the image. Any way to achieve this ? Please advise ASAP.

Please find attached the before view and after captured view (empty).

![error-before](https://cloud.githubusercontent.com/assets/22413645/19112601/4655ea32-8b38-11e6-80b4-0e55451a36f8.png)
![error-after](https://cloud.githubusercontent.com/assets/22413645/19112607/4a2782f6-8b38-11e6-9806-d60cc29e163a.png)

**Comment by gre** [comment]
can you share a minimal code that reproduce this? I'm not sure why it would disappear, seems weird to me, are you sure you keep rendering that view?

There is no such bug in https://github.com/gre/react-native-view-shot-example

**Comment by gre** [comment]
you might be right about this bug BTW, maybe it's not a good idea I do this without restoring back the layout:

https://github.com/gre/react-native-view-shot/blob/master/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java#L119

i'm not even sure if I need to to this? feel free to test without this line, check if result still get rendered too

**Comment by billywanmf** [comment]
Hi Gaëtan,
It seems working now by removing the line you mentioned in java and the view remained inside the screen. Will further check if the capture image is ok later.

Thank you for your prompt feedback and support.

**Comment by gre** [comment]
cool, feel free to send a PR. i'll later check if there is no case this would break and crop with a wrong size (unless you want to do it ;))
