### ISSUE TITLE
[Android] WebGL content inside a WebView source doesn't exist on a snapshot

### ISSUE THREAD

**Issue by kramer9x** [gre/react-native-view-shot#140]
First of all - Thanks for the library.

### bug report 
If a WebView source contains some webgl drawings - they are not visible on a snapshot.

#### Version & Platform

```bash
npm ls react-native react-native-view-shot:

├── react-native@0.52.0
└── react-native-view-shot@2.3.0
```

**Platform:** iOS? Android?
Android. Device.

#### Expected behavior
WebGL content also presented on an image
#### Actual behavior
WebGL content missing

#### Steps to reproduce the behavior

https://github.com/kramer9x/view-shot-webgl-example

- Run
- Press share (react-native-share was used)
- See shared image

This example contains an html with 2 canvas elements. 
For the first one we use webgl context, for the second - 2d.
When we do a snapshot, 2d content visible, webgl - not.
Please note that the issue could be reproducible on android device only (I used sgs 5 with android 6.0.1). Android emulators doesn't support webgl. 
iOS - works fine on both simualtor and device.

**Comment by gre** [comment]
I'm not sure we can fix it, we are relying on the platform capabilities and this is likely a Android limitation? 🤔

**Comment by sej1228** [comment]
How to solve it later

> 我不确定我们是否可以修复它，我们是否依赖平台功能，这可能是Android的限制吗？ 🤔
