### ISSUE TITLE
[Android] MapView renders on top of everything else

### ISSUE THREAD

**Issue by davidhellsing** [gre/react-native-view-shot#141]
Despite not being supported, having a MapView component will still render but also ruin the screenshot because it is misplaced and have the wrong stacking order (on top of everything)

It would be better to not show the map at all and refer to the react-native-maps snapshot function instead. Hiding/showing the map programatically is not an option.

**Comment by gre** [comment]
Hi @davidhellsing , thanks for the issue,
is it dup to https://github.com/gre/react-native-view-shot/issues/86 ?

**Comment by davidhellsing** [comment]
@gre yes I suppose so! I dodn’t know that MapView was a TextureView. You can close this

**Comment by gre** [comment]
ok thanks
