### ISSUE TITLE
Capture ScrollView beyond screen get black background

### ISSUE THREAD

**Issue by MrZhang123** [gre/react-native-view-shot#142]
### Environment

Android: 7.0
React Native: 0.53.3
react-native-view-shot: 2.3.0

### Describe

Capture ScrollView container , the  beyond screen part get black background

![download](https://user-images.githubusercontent.com/13158765/38125801-bcb2bde6-341e-11e8-87d4-48095310b08f.jpg)
 
the black part is beyond screen

### code

```js
import { captureRef } from 'react-native-view-shot'

  captureScreen = () => {
    console.log('this is captureScreen')
    captureRef(this.refs.Sc, {
      format: 'jpg',
      result: 'base64',
      snapshotContentContainer: true
    })
      .then(res => {
        console.log(`data:image/jpg;base64,${res}`, 'this is res')
      }).catch(error => {
        console.log(error, 'this is error')
      })
  }

<ScrollView
     ref='Sc'
     collapsable={false}
>
  <View>
    <Text>This is test</Text>
  </View>
</ScrollView>
```

### Expect

the beyond screen part  not get black background

**Comment by gre** [comment]
random guess but have you tried to capture a View that is parent of the scrollview?

like

```
<View ref="Sc" collapsable={false}>
  <ScrollView>
    <View>
      <Text>This is test</Text>
    </View>
  </ScrollView>
</View>
```

**Comment by JasonBan** [comment]
same issue and i try 'capture a View that is parent of the Scrollview' but it doesn't work

**Comment by JasonBan** [comment]
same issue and i try 'capture a View that is parent of the Scrollview' but it doesn't work

**Comment by MrZhang123** [comment]
@JasonBan maybe you need use `contentContainerStyle` to set ScrollView style

**Comment by antonioaltamura** [comment]
@MrZhang123 how do you exactly solved the problem using `contentContainerStyle`?

**Comment by MrZhang123** [comment]
@antonioaltamura I just use `contentContainerStyle` instead of `style` , this problem solved

**Comment by dieh1984** [comment]
@MrZhang123 Can you tell me how do you solved this problem with `contentContainerStyle`? I've the same issue.

**Comment by duansiyu** [comment]
这个问题解决了吗

**Comment by duansiyu** [comment]
I have tried contentContainerStyle，but there  is the same problem.

**Comment by fantasy525** [comment]
same issues

**Comment by rikur** [comment]
Have the same issue, none of the workaround I could think of worked.

**Comment by tza17313** [comment]
try  add `style={{backgroundColor:"#fff"}}` to ScrollView.
like this: 
```jsx
<ScrollView
     ref='Sc'
     collapsable={false}
     style={{backgroundColor:"#fff"}}
>
  <View>
    <Text>This is test</Text>
  </View>
</ScrollView>
```

**Comment by catnuxer** [comment]
> try add `style={{backgroundColor:"#fff"}}` to ScrollView.
> like this:
> 
> ```js-jsx
> <ScrollView
>      ref='Sc'
>      collapsable={false}
>      style={{backgroundColor:"#fff"}}
> >
>   <View>
>     <Text>This is test</Text>
>   </View>
> </ScrollView>
> ```

Hi @tza17313 did u have try on react-native 0.57.x, Here I got same result black screen when hit the screenshoot. Would you like to give your info react-native version.

Here my package.json
```
{
  "name": "testapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-view-shot": "^2.5.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by gaminilesh** [comment]
Getting some error

![Simulator Screen Shot - iPhone X - 2019-05-15 at 11 55 06](https://user-images.githubusercontent.com/8748763/57752997-836e5300-7708-11e9-8562-2b9bbbb5f51d.png)

**Comment by qweewqaq** [comment]
can you tell me , have you resolved? i have the same with you?

**Comment by gre** [comment]
initial problem is solved with `contentContainerStyle` & confirmed by the author.
if you have a bug please create a new issue.

**Comment by otherRick** [comment]
I just gave a  style={{backgorundColor: '#fff' to my ViewShot and got it fixed.

**Comment by UAdenisyu** [comment]
use ViewShot component to wrap the content inside of your ScrollView. And set a white color

```
import ViewShot from 'react-native-view-shot';

    <ScrollView>
      <ViewShot ref={scrollViewRef} style={{ backgroundColor: '#fff' }}>
        <Text>This is test</Text>
      </ViewShot>
    </ScrollView>
```
