### ISSUE TITLE
undefined is not an object (evaluating 'RNViewShot.captureRef')

### ISSUE THREAD

**Issue by tututututututu** [gre/react-native-view-shot#145]
#### Version & Platform
**Platform:** iOS
export function captureRef(
  view: number | ReactElement<*>,
  optionsObject?: Object
): Promise<string> {
  if (typeof view !== "number") {
    const node = findNodeHandle(view);
    if (!node)
      return Promise.reject(
        new Error("findNodeHandle failed to resolve view=" + String(view))
      );
    view = node;
  }
  const { options, errors } = validateOptions(optionsObject);
  if (__DEV__ && errors.length > 0) {
    console.warn(
      "react-native-view-shot: bad options:\n" +
        errors.map(e => `- ${e}`).join("\n")
    );
  }
  return RNViewShot.captureRef(view, options);
}

this code:
return RNViewShot.captureRef(view, options);

i use the new way to bind ref in this way:
ref={component => this.sc = component}
and use like 
captureRef(this.sc, {
            format: 'png',
            quality: 0.9,
            result: 'tmpfile',
            snapshotContentContainer: true
        })
            .then(res =>
                console.warn(`res1=${res}`)
            )
            .then(res =>
                console.warn(`res2=${res}`)
            )
            .catch(
                error => (
                    console.warn(`error=${error}`)
                )
            );
}

**Comment by jniac** [comment]
forgot to install the pod ?

**Comment by tututututututu** [comment]
@jniac emm..      link show success  ,but not ,    link manual  and work

**Comment by barnesheaton** [comment]
@jniac Which Pod are we supposed to install? Where might I find it?

**Comment by nihp** [comment]
Here the solution is to manually link the RNViewShot in Xcode project. Refer the below steps

**Steps:** 
1. Go to libraries under the Project in the target(Xcode)
2. Right click on the libraries 
3. Click Add files to the project
4. Select the RNViewShot Xcodeproj and add in libraries
5. Click on the Link Binary With Libraries
6. Add the "libRNViewShot.a" file in the Link binaries
7. Rebuild the app again.

**Comment by jakubgrzelak** [comment]
I have the same problem. Solution above it is not working :-(

**Comment by gre** [comment]
This means the linking was not correctly done.

In React Native 0.60. this is getting easier with autolink. Give it a try.
