### ISSUE TITLE
 When the image height is long, get a white background

### ISSUE THREAD

**Issue by Githubzxw** [gre/react-native-view-shot#146]
### Environment
Iphone7
React Native: 0.51.0
react-native-view-shot: 2.2.0

### Describe
sometimes. when the image height is long, get a white background.

### Code

```
snapshotConfig = {
    format: 'jpg',
    result: 'tmpfile',
    snapshotContentContainer: false,
};

<ScrollView>
      <View ref={(ref) => this._snapshot = ref}}>
          <Image />
      </View>
</ScrollView>
```

Please give me some advice，Thank you

**Comment by gre** [comment]
what do you mean by too long? like it goes out of screen? what is your image resolution?

**Comment by Githubzxw** [comment]
@gre image height over thousands of pixels.  
```
const {width} = Dimensions.get('window');
<Image 
  style={{
    width: width, 
    height: 2000
  }} 
  resizeMode="cover"
/>
```

**Comment by gre** [comment]
I'm not sure if it's the case for iPhone as well and if it's the same issue, but on Android for instance, you can't create a bitmap bigger than the device screen pixel size. it's a low level limitation.

**Comment by Githubzxw** [comment]
Yes, This problem is caused by too large image size。

**Comment by gre** [comment]
yeah, at this point, nothing we can really do than sticking to platform limitations
