### ISSUE TITLE
图片失真是为什么呢

### ISSUE THREAD

**Issue by JohnTree** [gre/react-native-view-shot#149]
#### Version & Platform

```bash
npm ls react-native react-native-view-shot #<- PASTE CMD RESULT IN HERE
```

**Platform:** iOS? Android?

**Comment by Yanzlllll** [comment]
Please Translate your question by Google Translate Sb

**Comment by gre** [comment]
我不知道，你有么有一个 reproductible example？ 😄

**Comment by Liaozhenting** [comment]
@Yanzlllll You looks like a messenger of justice.
