### ISSUE TITLE
Requiring unknown module "/data/data/..." on Android

### ISSUE THREAD

**Issue by stovmascript** [gre/react-native-view-shot#15]
I can't seem to `Image.getSize` nor `require()` the saved image on Android. Works fine on iOS.

```javascript
takeSnapshot(this.refs.content, {
	format: 'jpeg',
	quality: 0.8,
})
.then((response) => {
	Image.getSize(response, (width, height) => {
		this.setState({
			modalBackdropProps: {
				imageSize: {
					height,
					width,
				},
				source: {
					uri: response,
				},
			},
		});
	});
});
```

The image path is: `/data/data/<packageName>/cache/ReactNative_snapshot_image_<timestamp>.jpeg`.

For `Image.getSize` I get: "Error: Unsupported uri scheme!"

**Comment by gre** [comment]
can you tell on which version you are on, that seems related to this breaking change https://github.com/gre/react-native-view-shot/commit/a85cf9629af6ee27350f1c78084b8ec58eae4134

**Comment by gre** [comment]
might means I need to use URI again and people will have to resolve URI to a file :( it's weird Image.getSize don't support it, let me think what's appropriate solution..

**Comment by gre** [comment]
can you try to concat with `"file:" + response` (not tested)

**Comment by gre** [comment]
you shouldn't have to do this though, i'm just trying to figure things out

**Comment by stovmascript** [comment]
"react-native-view-shot": "1.3.0"
"react-native": "0.33.0"

**Comment by stovmascript** [comment]
Will try in about half an hour. Don't have a USB cable or emulator installed on train lol. #ossdevfail

**Comment by gre** [comment]
OK
It's probably a regression of this commit . Meanwhile try to use 1.2.0

**Comment by gre** [comment]
sorry, i'm afraid 1.2.0 wouldn't work neither.
let me see if I can find a solution.

**Comment by stovmascript** [comment]
Sorry for the delay. Confirmed, tried both combinations on both versions. Thanks for looking into it.
