### ISSUE TITLE
Trying to resolve view with tag 729 which doesn't exist

### ISSUE THREAD

**Issue by yolinsoft** [gre/react-native-view-shot#151]
RN 0.53.3
react-native-view-shot 2.3.0

Trying to resolve view with tag 729 which doesn't exist

execute
ViewShot.java: 84

**Comment by yolinsoft** [comment]
Style the view and specify the backgroundColor property

**Comment by suwu150** [comment]
@yolinsoft 
When I finished this way, I get the following error.
{"framesToPop": 1, "code": "E_UNABLE_SNAPSHOT"},
What is the reason?

**Comment by yolinsoft** [comment]
@suwu150 
Is it Android or Ios?

**Comment by suwu150** [comment]
IOS
