### ISSUE TITLE
Prepare for Android SDK 26-27

### ISSUE THREAD

**Issue by andrei-m-code** [gre/react-native-view-shot#152]
As everybody will be required to use latest Android SDKs, react-native will have to be upgraded. Following that all the 3rd party libraries including react-native-view-shot should ensure to be compatible with latest SDKs.

I have changed targetSdk in my gradle config and tried to use Viewshot. Here is what I got:

![screenshot_20180601-235434](https://user-images.githubusercontent.com/5212280/40870193-0aac3350-65f8-11e8-9082-2159910ec997.png)

We might have to go this route https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed. 

Is there an easy way to fix it?

**Comment by OleksandrKucherenko** [comment]
https://github.com/gre/react-native-view-shot/pull/177

android build plugins & dependencies are upgraded
