### ISSUE TITLE
Blank image with long/big snapshots

### ISSUE THREAD

**Issue by fv0008** [gre/react-native-view-shot#154]
when I try to capture more long scrollView screen the img will be blank

debug the Code at line 110 @ RNViewShot.m

success = [rendered drawViewHierarchyInRect:(CGRect){CGPointZero, size} afterScreenUpdates:YES];
UIImage *image = UIGraphicsGetImageFromCurrentImageContext();

rendered in debug will see the normal image in preview 
but *image will see blank in preview

test in simulator 6 plus and iPhone 6 plus

**Comment by fv0008** [comment]
[rendered.layer renderInContext: UIGraphicsGetCurrentContext()]; 
if use the renderInContext instead the drawViewHierarchyInRect it will be ok

**Comment by gre** [comment]
I can't remember exactly what but I think thare pro and cons of `renderInContext` vs `drawViewHierarchyInRect` . if we use `renderInContext` we'll have to make sure it works for all cases.

also i think if you want to capture content higher than the scrollview size, maybe you should try to render it outside of this scroll container, in background to capture it. it's a bit more code to write, but it might work out

**Comment by fv0008** [comment]
surly, I just try to test the renderInContext in some device but really can't confirm works on all cases

I will try to test more device for more time, all test use scrollview. renderInContext will solve my problem now

**Comment by Mitesh-2009** [comment]
[rendered.layer renderInContext:UIGraphicsGetCurrentContext()]; not working to capture scrollview contents

**Comment by gre** [comment]
I think it's ultimately not a problem of what this library can offer but more a problem of what the OS can offer. Usually you can't build images that are bigger than the screens of the phones (e.g. https://stackoverflow.com/questions/15313807/android-maximum-allowed-width-height-of-bitmap )

a trick could be to cut the images into slice (snapshot multiple parts). PR welcomed if you find a solution but I assume it's a problem wider than this library.
