### ISSUE TITLE
Hide components from image shot

### ISSUE THREAD

**Issue by mutale** [gre/react-native-view-shot#155]
Hi, 

I can't seem to find in the documentation an option for excluding components from shot (Buttons etc.).

Is it posible?
Ideally I'd assume a prop should be given to the components I wish to ignore.
If not -Is there any preShot trigger I can hook to to remove those components?

Thanks!

**Comment by gre** [comment]
you can either render the same components tree (without the one you want to not screenshot) in a hidden way (offset it off the screen viewport), or you can re-render your things without the element to snapshot before you call the snapshot methods, but it means that user visually see the glitch. depends on your needs.

**Comment by abhishek-pokhriyal** [comment]
Really need this feature!

**Comment by oluseyi-ged** [comment]
Hi, i hope i am not too late to give a response but one thing i tried doing that works perfectly was recreate the component the way i want it to be when saved on the gallery, then set the position absolute then give it a zIndex of 0 while the main one to be displayed is absolute as well but with a zIndex of 999. and assign the caption function to the one hidden below.

and it works... hope my explanation is not too confusing.
`
 <View style={{flex: 1, position: 'relative'}}>
      <ViewShot
        ref={viewShot}
        style={{
          flex: 0.4,
          backgroundColor: '#fff',
          height: '100%',
          width: '100%',
          position: 'absolute',
          zIndex: 0,
        }}
        options={{format: 'jpg', quality: 1.0}}>
       ...
       </ViewShot>
<View>

 <ScrollView
        showsHorizontalScrollIndicator={false}
        contentContainerStyle={{
          paddingBottom: 20,
          backgroundColor: COLORS.white,
          position: 'absolute',
          zIndex: 99999,
        }}>
     ....
</ScrollView>
`
