### ISSUE TITLE
Slow performance with captureScreen()

### ISSUE THREAD

**Issue by shorty131** [gre/react-native-view-shot#156]
### Speed problem with captureScreen()

**Platform:** Android

#### Expected behavior
Time to take and save screenshot of whole screen should be faster if it`s possible ?
#### Actual behavior
It takes about 1100ms on Samsung note 8 with --variant release

What can be done to speed up captureScreen?

Could use of opengl in native code help in this case?

I need to speed up this screen-taking action because i use that image for blur effect for action menu,
and it's slow's down user experience.

**Comment by gre** [comment]
This is maybe because it takes time to create a Bitmap object. I'm not sure if there are other ways.

you might want to profile what's slow

I don't see how OpenGL could help here, because for instance, if you want to have a view rendered into OpenGL you actually need to rasterize it from CPU

**Comment by jgreen210** [comment]
Profiling would be better than guesswork of course, but...

Would it be worth wrapping the FileOutputStream used by https://github.com/gre/react-native-view-shot/blob/master/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java in a BufferedOutputStream? If https://developer.android.com/reference/android/graphics/Bitmap.html#compress(android.graphics.Bitmap.CompressFormat,%20int,%20java.io.OutputStream) generates lots of small writes, the buffering would coalesce them, saving some time.

**Comment by jg210** [comment]
Adding buffering would mean https://github.com/gre/react-native-view-shot/pull/169 would become more important.

**Comment by OleksandrKucherenko** [comment]
This pull request https://github.com/gre/react-native-view-shot/pull/177 should resolve all those issues
