### ISSUE TITLE
android issue... 'gl-react-image' is in use. If you capture using 'captureRef', only the image will be white.

### ISSUE THREAD

**Issue by godesani** [gre/react-native-view-shot#158]
'gl-react-image' is in use. If you capture using 'captureRef', only the image will be white.

code :
//-------------------
View ref="onlyPhoto" collapsable={false} style={style}
  View {...this._panResponder.panHandlers}
     Surface width={this.props.cropWidth} height={this.props.cropHeight} pixelRatio=
{this.props.pixelRatio} backgroundColor="transparent" ref="cropit"
           GLImage source={{ uri: this.props.image }} 
//-------------------

      

We use 'captureRef' in the same way.
The problem works well in 'IOS'. But on "Android", it only displays as a white screen.

The development environment is as follows.
package.json
{
     "gl-react": "2.3.1",
     "gl-react-native": "2.48.0",
     "react-native": "0.55.4",
     "react-native-view-shot": "^ 2.4.0",
....
}

MainApplication.java
import fr.greweb.reactnativeviewshot.RNViewShotPackage;

public class MainApplication extends NavigationApplication
{
protected List <ReactPackage> getPackages () {
         return Arrays. <ReactPackage> asList (
            new RNViewShotPackage (),
            ....
}

Installation seems to be done without problems ....
I do not know why android have such symptoms.

I'm still in a position to learn 'react native' and I am not good enough.
If you know how to solve the above problem, please answer it.....

**Comment by ParhamZare** [comment]
I have the same issue too

**Comment by sundariragavan** [comment]
@OleksandrKucherenko  I have same issue. Any solution

**Comment by gre** [comment]
our example show GL view (of gl-react-native **v2**, not v3!) screenshot properly works so i think there are no reason this wouldn't work with GLImage as well.

if you think the bug is still present, please create a new `example/` screen that reproduces it. Thanks.
