### ISSUE TITLE
react-native link doesn't work well, manual link required Android

### ISSUE THREAD

**Issue by omergulen** [gre/react-native-view-shot#160]
### feature request

I spent my last days struggling with this situation, so I wanted to share solution in here to help others.
My `link` command doesn't work well, so I needed to link this library manually. I couldn't find any documentation in this library about it. So, I used another library's documentation, but I will share the correct code for this library.

### bug report 

`react-native link` doesn't work. It never ends.

#### Version & Platform

```bash
$ npm ls react-native react-native-view-shot
soguk_savas@0.1.5 D:\Sqerty\oldSogukSavas\soguksavas
+-- UNMET DEPENDENCY react-native@0.55.3
`-- UNMET DEPENDENCY react-native-view-shot@^2.4.0
```

**Platform:** Android

#### Expected behavior

`react-native link react-native-view-shot` suppose to link this library.

#### Actual behavior

`react-native link react-native-view-shot` command never ends, it stucks.

**Comment by omergulen** [comment]
##### In ``android/build.gradle`` add the jitpack repository to your project.

```diff
allprojects {
    repositories {
        mavenLocal()
        jcenter()
+       maven {                                                                                                             
+          url "https://jitpack.io"                                                                                       
+       }                                                                                                                   
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$projectDir/../../node_modules/react-native/android"
        }
    }
}
```

##### In `android/app/build.gradle`, add the react-native-spinkit dependency
```diff
dependencies {
+    compile project(':react-native-view-shot')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

##### In `android/settings.gradle`
```diff
include ':app'
+ include ':react-native-view-shot'
+ project(':react-native-view-shot').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-view-shot/android')
```

##### In `android/app/src/main/java/com/example/MainApplication.java`, add the `RNSpinkitPackage` dependency.
```diff
import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
+ import fr.greweb.reactnativeviewshot.RNViewShotPackage;                                                                 

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

    ...
    
    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
+          new RNViewShotPackage(),                                                                                         
        );
    }
}

```

#### Warning: 
##### After I tried to link it with `react-native link react-native-view-shot` command several times, in the process of linking it manually I figured it out that it was double linked, every piece of code was written twice. Please remove duplicates and try again, maybe this will help, too.

**Comment by gre** [comment]
`react-native link` is now replaced by autolink in RN 0.60. it correctly works with react-native-view-shot
