### ISSUE TITLE
Add views to shot only

### ISSUE THREAD

**Issue by martjoao** [gre/react-native-view-shot#161]
### feature request

It would be nice if there was a way to add custom views to the shot only (not showing them on the app itself). One use case would be to add a logo or a title to the image on a custom location

**Comment by gre** [comment]
not really sure how it would technically be possible. I mean, there is not yet "offline rendering" of react native elements

**Comment by AricWu** [comment]
I think you can set the view you want to shot under other view. Then the view may not show and you can shot it .

**Comment by keksonov** [comment]
One way I have found is to create the same view with `position: 'absolute'` and `left: '100%'`. Add anything you want on this view and capture it.

If you need any help, I would be happy to provide.
