### ISSUE TITLE
Snapshot from Raw HTML String

### ISSUE THREAD

**Issue by CHOMNANP** [gre/react-native-view-shot#162]
### feature request
Is there any work around to snapshot an image from Raw HTML String or JSX String?

The reason that I would not want to display the content on the the screen, but I'd like to generate an image without user see the image.

**Comment by gre** [comment]
you can put it in a WebView and snapshot it 🤔

**Comment by CHOMNANP** [comment]
I'm quite new. Any example to achieve this. This sound very straight forward.

**Comment by gre** [comment]
see the example that snapshot a WebView: https://github.com/gre/react-native-view-shot/blob/master/example/App.js#L283-L293
 then for webview doc, see on React Native https://facebook.github.io/react-native/docs/webview

**Comment by Dror-Bar** [comment]
@gre first example - page not found.
