### ISSUE TITLE
Change file uri

### ISSUE THREAD

**Issue by Albert0405** [gre/react-native-view-shot#163]
how can i change the file destination when i capture() it? the `uri` puts it in a folder where it is hidden and cannot be seen in my phone file manager.

For example i wanted to save it in `Download` folder..

**Comment by Albert0405** [comment]
solved: Using `rn-fetch-blob`

```
saveQrCode() {
    const PATH_TO_WRITE = `${RNFetchBlob.fs.dirs.DownloadDir}/test.png`;

    this.refs.viewShot.capture().then(data => {
      RNFetchBlob.fs.writeFile(PATH_TO_WRITE, data, "base64").then(() => {
        ToastAndroid.show("Saved to gallery !!", ToastAndroid.SHORT);
      });
    });
  }
```

**Comment by omorhefere** [comment]
How did you avoid this error: "Error: open failed: EACCES (Permission denied)"?

**Comment by HeinXtet** [comment]
before save to file request storge permission of both

**Comment by Piyush132000** [comment]
> How did you avoid this error: "Error: open failed: EACCES (Permission denied)"?

hii bro i am also facing same problem if you find answer of this problem please help me

**Comment by Piyush132000** [comment]
hlo friends, i am here with solution of this problem , For solving this problem you have to go on your App permission on your real mobile and allow for camera storage then you  can easily save your ViewShot on Your Mobile.

go to App Permisssion  in your App.info
allow Camera accesss storage
