### ISSUE TITLE
Cannot Capture entire scrollview using captureRef and Cant Attach empty file- Android. 

### ISSUE THREAD

**Issue by nameisveeru** [gre/react-native-view-shot#164]
Platform : Both IOS and Android.

1. I have a ViewContainer that contains ScrollView with data in a list. I want the entire data in the scrollview to be captured using captureRef.But it Still captures the only screen available on the phone display.

Only Android : 

2.Created a snapshot of the page using CaptureScreen and passed response url to the RNMail as url attachment .It works fine on the IOS. But on Android it displays : Can't Attach empty file. 

Please let me know if i am doing anything wrong or is there any other alternative fixes.

Thanks,
Veerendra

**Comment by Taym95** [comment]
For ScrollView use this :

` capture ScrollView content
class ExampleCaptureScrollViewContent extends Component {
  onCapture = uri => {
    console.log("do something with ", uri);
  }
  render() {
    return (
      <ScrollView>
        <ViewShot onCapture={this.onCapture} captureMode="mount">
          <Text>...The Scroll View Content Goes Here...</Text>
        </ViewShot>
      </ScrollView>
    );
  }
}`

**Comment by MithleshKumarAndroid** [comment]
this.props.captureMode="mount" 
Give Error undefined
