### ISSUE TITLE
Supporting dynamic refs within a loop

### ISSUE THREAD

**Issue by AliRadmanesh** [gre/react-native-view-shot#165]
#### Version & Platform

react-native: 0.55.4
react-native-view-shot: 2.3.0

**Platform:** iOS & Android

#### Expected behavior

when I want to use ViewShot within a loop (in my case map function) there should be a way to reference to a specific <ViewShot> by using its index; but unfortunately I can't :(

#### Actual behavior

I'm using map function like so:

```
transactions.slice(0, 29).map((transactionList, index) =>
              <ViewShot
                ref={`ViewShot${index}`}
              >
              // Content to capture
              </ViewShot>

                  <Button
                    ...
                    onPress={() => {
                        this.refs.{`ViewShot${index}`}.capture().then(uri => {
                          // do sth with image
                          });
                    }}
                  >
                  ...
                  </Button>
```

but I got error on this line:

```
this.refs.{`ViewShot${index}`}.capture().then(uri => {
```

I handle it by using a switch-case but it's a workaround not a solution!

**Comment by gre** [comment]
`ref` is not part of this library, in fact it's part of React. and to address you usecase, you can instead give a function to ref, or even a ref object created with React.createRef (introduced since React 16.x).
see https://reactjs.org/docs/refs-and-the-dom.html
