### ISSUE TITLE
RNViewShot.captureRef is not a functon

### ISSUE THREAD

**Issue by CryLittleSister** [gre/react-native-view-shot#166]
### bug report 
I'm using the examples given here but am getting the same error message every time: _RNViewShot.captureRef is not a function_
```bash
paint-the-town@0.1.0 /home/tara/northCoders/project/Project-FrontEnd/paint-the-town
├── react-native@0.55.4
└── react-native-view-shot@2.4.0
```

**Platform:** iOS? Android?
iOS
#### Expected behavior
take a snapshot
#### Actual behavior
error message
#### Steps to reproduce the behavior
i'm just copying and pasting the example

**Comment by gre** [comment]
it means the project is not properly configured on the native side. native link is not linked.
