### ISSUE TITLE
persistent storage...

### ISSUE THREAD

**Issue by MeKarina** [gre/react-native-view-shot#17]
instead of writing into `tmp` file,,why don't store image into persistent storage such as `Documents` directory..?? after that image can be accessed with `~/Documents/filename`...

**Comment by gre** [comment]
see my answer here https://github.com/gre/react-native-view-shot/issues/18#issuecomment-254522504

**Comment by gre** [comment]
i've released a new version 1.8.0 that have a path allowing to define an absolute path where to save the snapshot.
