### ISSUE TITLE
undefined is not a function (evaluating 'RNViewShot.captureRef(view,options)')

### ISSUE THREAD

**Issue by vimalchandhru** [gre/react-native-view-shot#173]
Please refer this link.
[https://stackoverflow.com/questions/52352355/undefined-is-not-a-function-evaluating-rnviewshot-capturerefview-options](url)

**Comment by vimalchandhru** [comment]
@gre

**Comment by gre** [comment]
the error sounds like the library was not correctly linked in XCode

**Comment by EdgarXolop** [comment]
yes, in ios you need to update your pods
