### ISSUE TITLE
Beyond screen black screen

### ISSUE THREAD

**Issue by duansiyu** [gre/react-native-view-shot#179]
Android: 7.0
React Native: 0.57.3
react-native-view-shot: 2.5.0
**Display in simulator**
![image](https://user-images.githubusercontent.com/17777911/48475442-c32aaf80-e837-11e8-903c-b4241eed9af0.png)
**captureRef**
![image](https://user-images.githubusercontent.com/17777911/48475501-ece3d680-e837-11e8-9947-f0530b634832.png)
**The following is the code.**
/**
 * @file   生成图片分享
 * @author duansiyu 2018/10/18
 */

import React, {Component} from 'react';
import {
    View,
    StyleSheet,
    Text,
    TouchableOpacity,
    Image,
    Platform,
    Modal,
    ImageBackground,
    ScrollView,
    Dimensions,
    NativeModules
} from 'react-native';
import PropTypes from 'prop-types';
import {CSS} from '../../assets/css/common';
import LinearGradient from 'react-native-linear-gradient';//渐变色
import StarRating from 'react-native-star-rating';//评分组件
import {convertNumber,shareboard,convertEmoji} from '../../utils/global';
import {captureRef} from "react-native-view-shot";
import Toast from '../widgets/toast';//轻提示
import {uploadImg} from '../../api';
import { px2dp } from '../../utils/scale';
const { StatusBarManager } = NativeModules;
const STATUSBAR_HEIGHT = StatusBarManager.HEIGHT;
const height = Dimensions.get('window').height;

export default class ShareImage extends Component {
    constructor(props) {
        super(props);
        this.state={
            showModal:true,
            shareUrl:'',
        }
    }

    static propTypes = {
        image: PropTypes.string,//图片
        title: PropTypes.string,//标题
        content:PropTypes.string,//内容
        type:PropTypes.number,//1卡片 2短评
        comic:PropTypes.object,//漫画相关,
        showModal:PropTypes.bool,
    }

    static defaultProps = {
        showModal:false,
        cancelCb:()=>{}
    }

    componentDidMount(){
        setTimeout(()=>{
            captureRef(this.refs["share_content"], {
                format: "jpg",
                quality: 1,
                result: "tmpfile",
                snapshotContentContainer: true
            }).then(res => {
                setTimeout(()=>{this.on_getImgMsg(res) },500);
                }
            ).catch(error => {
                Toast.show('生成图片失败，请稍后再试');
                });
        },500)
        Toast.show("正在生成图片，请稍等");
    }

    onCancel=()=>{
        this.props.cancelCb();
    }

    on_getImgMsg(imgMsg){
        let formData = new FormData();
        formData.append('file_data', {
            uri:imgMsg,
            type:'multipart/form-data',
            name:"unname.jpg"
        });
        uploadImg(formData,true).then(res=>{
            if(res.data.data&&res.data.data.raw_url){
                this.setState({shareUrl:res.data.data.raw_url},()=>{ this.share();});
                console.log(res.data.data.raw_url);
            }
        }).catch(error=>{
            Toast.show('生成图片失败，请稍后再试');
        })
    }

    share(){
        console.log(this.state.shareUrl);
        if(this.state.shareUrl.length==0){
            return Toast.show("正在生成图片，请稍等");
        }
        shareboard(
            {
                img: this.state.shareUrl,
                callback: (res) => {
                    Toast.show(res.msg);
                }
            }
        )
    }

    render(){
        const {image,title,content,type,comic,showModal} = this.props;
        return(
            showModal?<View style={{position:'absolute',left:0,bottom:0,top:0,right:0}}>
                <ScrollView  ref="share_content" collapsable={false} showsVerticalScrollIndicator={false} style={styles.root}
                             contentContainerStyle={styles.container}>
                     <ImageBackground blurRadius={30} style={styles.fullScreen} source={{uri:this.props.image}}>
                        <TouchableOpacity onPress={()=>this.share()} activeOpacity={1}>
                            <View style={{position:'relative'}}>
                                <View style={styles.img_view}>
                                    <Image source={{uri:image}} style={type==1?styles.short_img:styles.card_img} resizeMode='cover'/>
                                </View>
                                {type==2?
                                    <View>
                                        <LinearGradient colors={['rgba(0,0,0,0)','rgba(0,0,0,0.6)']} style={styles.linear}>
                                            <Text style={styles.comic_title}>{comic.title}</Text>
                                            <Text style={styles.comic_author}>作者:{comic.author}</Text>
                                        </LinearGradient>
                                    </View>
                                    :null
                                }
                            </View>
                            <View style={styles.content}>
                                {
                                   type==2?
                                       <View  style={{flexDirection:'row'}}>
                                           <Image source={{uri:comic.avatar}} style={styles.head}/>
                                           <View style={{justifyContent:'center',marginLeft:8}}>
                                               <Text style={styles.name}>{comic.username}</Text>
                                               <StarRating
                                                   disabled={true}
                                                   maxStars={5}
                                                   rating={Math.round(comic.score) / 2}
                                                   fullStarColor={'#ffc752'}
                                                   emptyStarColor={'#ffc752'}
                                                   starSize={14}
                                                   containerStyle={{width: 68}}
                                                   />
                                           </View>
                                       </View>:null
                                }
                                {title?<Text style={styles.title}>{title}</Text>:null}
                                {content?<Text style={type==1?styles.infoText:styles.shortText}>{convertEmoji(content)}</Text>:null}
                            </View>
                            <View style={styles.img_bottom}>
                                <ImageBackground style={styles.center_img} source={require('../../assets/img/share/pic_share_bg.png')}>
                                    <Image style={styles.code_img} source={require('../../assets/img/share/qr_code.png')}/>
                                    <View style={styles.right}>
                                        <Text style={styles.right_text}>长按识别二维码</Text>
                                        <Text style={styles.right_text}>下载鳗娱FUN</Text>
                                    </View>
                                </ImageBackground>
                             </View>
                            <Image style={styles.logo} source={require('../../assets/img/share/ic_share_logo.png')}/>
                            {type==2?
                                <View style={styles.score_view}>
                                    <Text style={styles.score}>{comic.score}</Text>
                                    <StarRating
                                        disabled={true}
                                        maxStars={5}
                                        rating={Math.round(comic.score) / 2}
                                        fullStarColor={'#fff'}
                                        emptyStarColor={'#fff'}
                                        starSize={12}
                                        containerStyle={{width: 65}}
                                    />
                                    <Text style={styles.number}>{convertNumber(comic.comment_num)}人</Text>
                                </View>:null
                            }
                        </TouchableOpacity>
                    </ImageBackground>
                </ScrollView>
                <Text style={styles.close} onPress={()=>this.onCancel()}>&#xe629;</Text>
            </View>:null
        )
    }
}

const styles = StyleSheet.create({
    fullScreen: {
        flex:1,
        paddingTop:54,
        paddingBottom:40,
        alignItems:'center',
        justifyContent:'center',
        ...Platform.select({
            ios: {
                minHeight:height,
            },
            android: {
                minHeight:height-STATUSBAR_HEIGHT,
            },
        }),
    },
    img_view:{
        borderTopLeftRadius:12,
        borderTopRightRadius:12,
        overflow: 'hidden'
    },
    img_bottom:{
        borderBottomLeftRadius:12,
        borderBottomRightRadius:12,
        overflow: 'hidden'
    },
    short_img:{
        width:px2dp(654),
        height:1.02*(px2dp(654)),

    },
    card_img:{
        width:px2dp(654),
        height:0.75*(px2dp(654)),
    },
    content:{
        width:px2dp(654),
        backgroundColor:'#fff',
        paddingTop:17,
        paddingLeft:17,
        paddingRight:17,
        justifyContent:'center'
    },
    title:{
        color:'#333',
        fontSize:24,
        textAlign:'center',
    },
    infoText: {
        fontSize: 16,
        color: '#8f8e94',
        textAlign: 'center',
        lineHeight:20
    },
    shortText:{
        fontSize: 14,
        color: '#8f8e94',
        marginTop:15,
        lineHeight:20
    },
    center_img:{
        width: px2dp(654),
        height:px2dp(194),
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        borderBottomLeftRadius:12,
        borderBottomRightRadius:12,
    },
    code_img:{
        width:px2dp(128),
        height:px2dp(128),
        marginTop:12
    },
    right:{
        marginLeft:9,
        marginTop:12
    },
    right_text:{
        fontSize:12,
        color:'#8f8e94'
    },
    logo:{
        width: 111,
        height:34,
        marginTop:16,
        alignSelf:'center'
    },
    linear:{
        width:px2dp(654),
        height:103,
        position:'absolute',
        bottom:0,
        left:0,
        zIndex:1,
        paddingLeft:22,
        paddingBottom:12,
        justifyContent:'flex-end'
    },
    comic_title:{
        color:'#fff',
        fontSize:20,
        width:CSS.screenWidth-186
    },
    comic_author:{
        color:'#bfbfbf',
        fontSize:14,
        width:CSS.screenWidth-186
    },
    score_view:{
        backgroundColor:'#000',
        borderRadius:8,
        alignItems:'center',
        justifyContent:'center',
        position:'absolute',
        top:px2dp(360),
        right:26,
        width:84,
        zIndex:99,
        paddingTop:10,
        paddingBottom:10
    },
    score:{
        color:'#fff',
        fontSize:32,
    },
    number:{
        color:'rgba(288,255,255,0.8)',
        fontSize:12,
        marginTop:8
    },
    head:{
        width:48,
        height:48,
        borderRadius:24
    },
    name:{
        color:'#8f8e94',
        fontSize:16,
        marginTop:3,
        width:px2dp(654)-194
    },
    root: {
        flex: 1,
        backgroundColor: "#f6f6f6",
    },
    container: {
        backgroundColor: "#f6f6f6",
    },
    close:{
        fontSize: 20,
        position: 'absolute',
        color: '#fff',
        top: 15,
        left: 10,
        fontFamily: 'iconfont'
    }
})

**Comment by yiky84119** [comment]
use View instead of ScrollView, snap ScrollView has some bugs on android

**Comment by yiky84119** [comment]
try surround ScrollView's content with a View, then snap the View, some bugs on Android with ScrollView

**Comment by rikur** [comment]
This started happening aroung RN 0.57.3, IIRC. Snapping a ScrollView no longer works on Android. Only the current visible slice of the ScrollView is captured properly.

**Comment by andy-zhang-guohua** [comment]
> Android: 7.0
> React Native: 0.57.3
> react-native-view-shot: 2.5.0
> **Display in simulator**
> ![image](https://user-images.githubusercontent.com/17777911/48475442-c32aaf80-e837-11e8-903c-b4241eed9af0.png)
> **captureRef**
> ![image](https://user-images.githubusercontent.com/17777911/48475501-ece3d680-e837-11e8-9947-f0530b634832.png)
> **The following is the code.**
> /**
> 
> * @file   生成图片分享
> * @author duansiyu 2018/10/18
>   */
> 
> import React, {Component} from 'react';
> import {
> View,
> StyleSheet,
> Text,
> TouchableOpacity,
> Image,
> Platform,
> Modal,
> ImageBackground,
> ScrollView,
> Dimensions,
> NativeModules
> } from 'react-native';
> import PropTypes from 'prop-types';
> import {CSS} from '../../assets/css/common';
> import LinearGradient from 'react-native-linear-gradient';//渐变色
> import StarRating from 'react-native-star-rating';//评分组件
> import {convertNumber,shareboard,convertEmoji} from '../../utils/global';
> import {captureRef} from "react-native-view-shot";
> import Toast from '../widgets/toast';//轻提示
> import {uploadImg} from '../../api';
> import { px2dp } from '../../utils/scale';
> const { StatusBarManager } = NativeModules;
> const STATUSBAR_HEIGHT = StatusBarManager.HEIGHT;
> const height = Dimensions.get('window').height;
> 
> export default class ShareImage extends Component {
> constructor(props) {
> super(props);
> this.state={
> showModal:true,
> shareUrl:'',
> }
> }
> 
> ```
> static propTypes = {
>     image: PropTypes.string,//图片
>     title: PropTypes.string,//标题
>     content:PropTypes.string,//内容
>     type:PropTypes.number,//1卡片 2短评
>     comic:PropTypes.object,//漫画相关,
>     showModal:PropTypes.bool,
> }
> 
> static defaultProps = {
>     showModal:false,
>     cancelCb:()=>{}
> }
> 
> componentDidMount(){
>     setTimeout(()=>{
>         captureRef(this.refs["share_content"], {
>             format: "jpg",
>             quality: 1,
>             result: "tmpfile",
>             snapshotContentContainer: true
>         }).then(res => {
>             setTimeout(()=>{this.on_getImgMsg(res) },500);
>             }
>         ).catch(error => {
>             Toast.show('生成图片失败，请稍后再试');
>             });
>     },500)
>     Toast.show("正在生成图片，请稍等");
> }
> 
> onCancel=()=>{
>     this.props.cancelCb();
> }
> 
> on_getImgMsg(imgMsg){
>     let formData = new FormData();
>     formData.append('file_data', {
>         uri:imgMsg,
>         type:'multipart/form-data',
>         name:"unname.jpg"
>     });
>     uploadImg(formData,true).then(res=>{
>         if(res.data.data&&res.data.data.raw_url){
>             this.setState({shareUrl:res.data.data.raw_url},()=>{ this.share();});
>             console.log(res.data.data.raw_url);
>         }
>     }).catch(error=>{
>         Toast.show('生成图片失败，请稍后再试');
>     })
> }
> 
> share(){
>     console.log(this.state.shareUrl);
>     if(this.state.shareUrl.length==0){
>         return Toast.show("正在生成图片，请稍等");
>     }
>     shareboard(
>         {
>             img: this.state.shareUrl,
>             callback: (res) => {
>                 Toast.show(res.msg);
>             }
>         }
>     )
> }
> 
> render(){
>     const {image,title,content,type,comic,showModal} = this.props;
>     return(
>         showModal?<View style={{position:'absolute',left:0,bottom:0,top:0,right:0}}>
>             <ScrollView  ref="share_content" collapsable={false} showsVerticalScrollIndicator={false} style={styles.root}
>                          contentContainerStyle={styles.container}>
>                  <ImageBackground blurRadius={30} style={styles.fullScreen} source={{uri:this.props.image}}>
>                     <TouchableOpacity onPress={()=>this.share()} activeOpacity={1}>
>                         <View style={{position:'relative'}}>
>                             <View style={styles.img_view}>
>                                 <Image source={{uri:image}} style={type==1?styles.short_img:styles.card_img} resizeMode='cover'/>
>                             </View>
>                             {type==2?
>                                 <View>
>                                     <LinearGradient colors={['rgba(0,0,0,0)','rgba(0,0,0,0.6)']} style={styles.linear}>
>                                         <Text style={styles.comic_title}>{comic.title}</Text>
>                                         <Text style={styles.comic_author}>作者:{comic.author}</Text>
>                                     </LinearGradient>
>                                 </View>
>                                 :null
>                             }
>                         </View>
>                         <View style={styles.content}>
>                             {
>                                type==2?
>                                    <View  style={{flexDirection:'row'}}>
>                                        <Image source={{uri:comic.avatar}} style={styles.head}/>
>                                        <View style={{justifyContent:'center',marginLeft:8}}>
>                                            <Text style={styles.name}>{comic.username}</Text>
>                                            <StarRating
>                                                disabled={true}
>                                                maxStars={5}
>                                                rating={Math.round(comic.score) / 2}
>                                                fullStarColor={'#ffc752'}
>                                                emptyStarColor={'#ffc752'}
>                                                starSize={14}
>                                                containerStyle={{width: 68}}
>                                                />
>                                        </View>
>                                    </View>:null
>                             }
>                             {title?<Text style={styles.title}>{title}</Text>:null}
>                             {content?<Text style={type==1?styles.infoText:styles.shortText}>{convertEmoji(content)}</Text>:null}
>                         </View>
>                         <View style={styles.img_bottom}>
>                             <ImageBackground style={styles.center_img} source={require('../../assets/img/share/pic_share_bg.png')}>
>                                 <Image style={styles.code_img} source={require('../../assets/img/share/qr_code.png')}/>
>                                 <View style={styles.right}>
>                                     <Text style={styles.right_text}>长按识别二维码</Text>
>                                     <Text style={styles.right_text}>下载鳗娱FUN</Text>
>                                 </View>
>                             </ImageBackground>
>                          </View>
>                         <Image style={styles.logo} source={require('../../assets/img/share/ic_share_logo.png')}/>
>                         {type==2?
>                             <View style={styles.score_view}>
>                                 <Text style={styles.score}>{comic.score}</Text>
>                                 <StarRating
>                                     disabled={true}
>                                     maxStars={5}
>                                     rating={Math.round(comic.score) / 2}
>                                     fullStarColor={'#fff'}
>                                     emptyStarColor={'#fff'}
>                                     starSize={12}
>                                     containerStyle={{width: 65}}
>                                 />
>                                 <Text style={styles.number}>{convertNumber(comic.comment_num)}人</Text>
>                             </View>:null
>                         }
>                     </TouchableOpacity>
>                 </ImageBackground>
>             </ScrollView>
>             <Text style={styles.close} onPress={()=>this.onCancel()}>&#xe629;</Text>
>         </View>:null
>     )
> }
> ```
> }
> 
> const styles = StyleSheet.create({
> fullScreen: {
> flex:1,
> paddingTop:54,
> paddingBottom:40,
> alignItems:'center',
> justifyContent:'center',
> ...Platform.select({
> ios: {
> minHeight:height,
> },
> android: {
> minHeight:height-STATUSBAR_HEIGHT,
> },
> }),
> },
> img_view:{
> borderTopLeftRadius:12,
> borderTopRightRadius:12,
> overflow: 'hidden'
> },
> img_bottom:{
> borderBottomLeftRadius:12,
> borderBottomRightRadius:12,
> overflow: 'hidden'
> },
> short_img:{
> width:px2dp(654),
> height:1.02*(px2dp(654)),
> 
> ```
> },
> card_img:{
>     width:px2dp(654),
>     height:0.75*(px2dp(654)),
> },
> content:{
>     width:px2dp(654),
>     backgroundColor:'#fff',
>     paddingTop:17,
>     paddingLeft:17,
>     paddingRight:17,
>     justifyContent:'center'
> },
> title:{
>     color:'#333',
>     fontSize:24,
>     textAlign:'center',
> },
> infoText: {
>     fontSize: 16,
>     color: '#8f8e94',
>     textAlign: 'center',
>     lineHeight:20
> },
> shortText:{
>     fontSize: 14,
>     color: '#8f8e94',
>     marginTop:15,
>     lineHeight:20
> },
> center_img:{
>     width: px2dp(654),
>     height:px2dp(194),
>     flexDirection:'row',
>     justifyContent:'center',
>     alignItems:'center',
>     borderBottomLeftRadius:12,
>     borderBottomRightRadius:12,
> },
> code_img:{
>     width:px2dp(128),
>     height:px2dp(128),
>     marginTop:12
> },
> right:{
>     marginLeft:9,
>     marginTop:12
> },
> right_text:{
>     fontSize:12,
>     color:'#8f8e94'
> },
> logo:{
>     width: 111,
>     height:34,
>     marginTop:16,
>     alignSelf:'center'
> },
> linear:{
>     width:px2dp(654),
>     height:103,
>     position:'absolute',
>     bottom:0,
>     left:0,
>     zIndex:1,
>     paddingLeft:22,
>     paddingBottom:12,
>     justifyContent:'flex-end'
> },
> comic_title:{
>     color:'#fff',
>     fontSize:20,
>     width:CSS.screenWidth-186
> },
> comic_author:{
>     color:'#bfbfbf',
>     fontSize:14,
>     width:CSS.screenWidth-186
> },
> score_view:{
>     backgroundColor:'#000',
>     borderRadius:8,
>     alignItems:'center',
>     justifyContent:'center',
>     position:'absolute',
>     top:px2dp(360),
>     right:26,
>     width:84,
>     zIndex:99,
>     paddingTop:10,
>     paddingBottom:10
> },
> score:{
>     color:'#fff',
>     fontSize:32,
> },
> number:{
>     color:'rgba(288,255,255,0.8)',
>     fontSize:12,
>     marginTop:8
> },
> head:{
>     width:48,
>     height:48,
>     borderRadius:24
> },
> name:{
>     color:'#8f8e94',
>     fontSize:16,
>     marginTop:3,
>     width:px2dp(654)-194
> },
> root: {
>     flex: 1,
>     backgroundColor: "#f6f6f6",
> },
> container: {
>     backgroundColor: "#f6f6f6",
> },
> close:{
>     fontSize: 20,
>     position: 'absolute',
>     color: '#fff',
>     top: 15,
>     left: 10,
>     fontFamily: 'iconfont'
> }
> ```
> })

I guess your problem is that you want to capture the whole ScrollView content but unfortunately it turns out to be the current visible viewport. 

If this is really your problem, you can get around it by setting the style.overflow of the ScrollView to be 'visible'.

Something did change during around RN 0.56/7.x in its ScrollView implementation class ReactScrollView as below shows :

Before : 
 @Override
  public void draw(Canvas canvas) {
    if (mEndFillColor != Color.TRANSPARENT) {
      final View content = getChildAt(0);
      if (mEndBackground != null && content != null && content.getBottom() < getHeight()) {
        mEndBackground.setBounds(0, content.getBottom(), getWidth(), getHeight());
        mEndBackground.draw(canvas);
      }
    }
    super.draw(canvas);
  }

After:  

 @Override
  public void draw(Canvas canvas) {
    if (mEndFillColor != Color.TRANSPARENT) {
      final View content = getChildAt(0);
      if (mEndBackground != null && content != null && content.getBottom() < getHeight()) {
        mEndBackground.setBounds(0, content.getBottom(), getWidth(), getHeight());
        mEndBackground.draw(canvas);
      }
    }
    getDrawingRect(mRect);

   ///// The below switch is the change ===>
    switch (mOverflow) {
      case ViewProps.VISIBLE:
        break;
      default:
        canvas.clipRect(mRect);
        break;
    }
   ///// The above switch is the change <===

    super.draw(canvas);
  }

**Comment by walkerzhy** [comment]
兄弟  你这个问题解决了吗？

**Comment by xunaizhong20** [comment]
@andy-zhang-guohua “If this is really your problem, you can get around it by setting the style overflow of the ScrollView to be 'visible'.”
This only to IOS, What about Android？

**Comment by xunaizhong20** [comment]
@andy-zhang-guohua You're right～
@walkerzhy 上面这人回答是正确的

**Comment by rikur** [comment]
```<ScrollView style={{ overflow: 'visible' }} />```

fixes the issue, but caused some other odd artifacts on Android. Solved it with a hack:

```
<ScrollView style={{ overflow: this.state.overflowFix ? 'visible' : 'scroll' }}>
..
this.setState({ overflowFix: true })
this.forceUpdate(() => {
    captureRef(this.scrollRef._root, {
      snapshotContentContainer: true,
      format: 'png',
    })
}
this.setState({ overflowFix: false })
..
```

**Comment by zhuanghongji** [comment]
What andy-zhang-guohua said is absolute right.

But if you have the same issue after set `overflow: 'visible'` in style prop,
maybe you can try to set `backgroundColor: 'white'` in contentContainerStyle.

**Comment by amaury-soto** [comment]
Guys as talked about in comments above, for android and from versions 0.57.0 onwards, the snapshotContentContainer: true property is apparently not working. 
The way I fixed this was adding to the ScrollView styles the property `overflow: 'visible'. `
However, this may cause the UI to change a bit, so as a recommendation this property could be handled dynamically. 
Example: 
` <ScrollView
              ref={viewRef}
              style={{
                ...styles.contentContainer,
                overflow: overflowVisible ? 'visible' : 'scroll', 
              }}>`
