### ISSUE TITLE
【Android】Trying to resolve view with tag which doesn't exist 【NEW】

### ISSUE THREAD

**Issue by chunipo** [gre/react-native-view-shot#180]
### feature request

Trying to resolve view with tag which doesn't exist 

### 

```
<View collapsable={false}  ref="imagee" style={{backgroundColor:'black',position:'absolute',marginRight:9999}}>
                    <Image   resizeMode='stretch'  style={{width:this.state.imageCom.width,height:this.state.imageCom.height}} source={{uri:this.state.imageCom.uri}}></Image>
                </View>

```

###

Now the same problem will still occur in this setting.Take a look at the trouble.

Thanks

**Comment by gre** [comment]
the code is too small to understand what the problem is.

Checkout out last `example/` project, there shouldn't be any problem.

**Comment by maticzav** [comment]
Also checkout [this comment](https://github.com/gre/react-native-view-shot/issues/151#issuecomment-393385101) it did the trick for me.

@gre thank you for this amazing library! Maybe you could add a comment somewhere about this? It seems like a common issue.

**Comment by chunipo** [comment]
> Also checkout [this comment](https://github.com/gre/react-native-view-shot/issues/151#issuecomment-393385101) it did the trick for me.
> 
> @gre thank you for this amazing library! Maybe you could add a comment somewhere about this? It seems like a common issue.

omg，I have forgotten what this question is. Thank you anyway
