### ISSUE TITLE
Get image from uri.

### ISSUE THREAD

**Issue by BipinAle** [gre/react-native-view-shot#181]
### Help
How to get image from uri?

### bug report 
captureRef(this.refs.viewShot, {
 format: "jpg",
 quality: 0.8,
width: size, height: size, 
 result:"tmpfile"
 })
.then(
 uri => console.warn("Image saved to", uri),<== this uri is pointing towards android cache file and when I open there is nothing.
               error => console.warn("Oops, snapshot failed", error)
              ); 

#### Version & Platform
android 

#### Expected behavior
I want to the change uri to base64.
#### Actual behavior
There is no data in cache folder.

**Comment by mun5865** [comment]
Hi @BipinAle , I also faced the same issue here, the cache file is empty, how would you fixed it?

**Comment by BipinAle** [comment]
@mun5865 cache file is never accessible. In my case, i converted that uri in to base64 and got the actual image.

**Comment by Piyush132000** [comment]
hlo friends, i am here with solution of this problem , For solving this problem you have to go on your App permission on your real mobile and allow for camera storage then you can easily save your ViewShot on Your Mobile.

go to App Permisssion in your App.info
allow Camera accesss storage
