### ISSUE TITLE
undefined is not an object (evaluating 'RNViewShot.captureScreen')

### ISSUE THREAD

**Issue by Shanie1331** [gre/react-native-view-shot#191]
Facing only this, Just added the library and linked it (only npm). Please help!
platform is android, version is @latest.
Do I need to rebuild with Android studio?

**Comment by haven2world** [comment]
Try to link it manually.

**Comment by jakubgrzelak** [comment]
The same problem in ios. After manual linking, rebuilding the app and installing it once more on the device

**Comment by KarimFikani** [comment]
Facing the same issue. How did you guys solve it?

**Comment by gre** [comment]
this indicates an issue with linking. See latest README instructions. react-native-view-shot is properly working with RN 0.60 autolink as well.
