### ISSUE TITLE
providing width and height to captureScreen has no effect

### ISSUE THREAD

**Issue by jasan-s** [gre/react-native-view-shot#192]
#### Version & Platform

```bash
npm ls react-native react-native-view-shot #
├── react-native@0.57.7
└── react-native-view-shot@2.5.0
```

**Platform:** iOS? Android?
iOS

#### Expected behavior
captured screenShot should be of size **320X568**(matxhing the passed in width and height values)
#### Actual behavior
captured screenShot is of size **640 × 1136**
#### Steps to reproduce the behavior

```
  captureScreenShot = () => {
    captureScreen({
      format: 'jpg',
      quality: 1,
      width: 320,
      height: 568,
    }).then(
      uri => {
        this.saveToCameraRoll(uri)
        this.resumeCamera()
      },
      error => console.error('Oops, snapshot failed', error),
    )
  }
```

**Comment by gre** [comment]
cannot reproduce on the demo app. captureScreen when defining a width and height will create a resized image.

<img width="476" alt="Capture d’écran 2019-08-11 à 12 35 59" src="https://user-images.githubusercontent.com/211411/62829819-54ca2080-bc02-11e9-9452-8e7552eebd18.png">
