### ISSUE TITLE
react-native-view-shot doesn't work as expected with react-native-camera

### ISSUE THREAD

**Issue by nkaczor** [gre/react-native-view-shot#193]
I am trying to use react-native-camera along with react-native-view-shot
I have following code:
```javascript
<ViewShot style = {{position: 'absolute', width: '100%', height: '100%', }}
            ref={ref => {
              this.view = ref;
        }}>
            <RNCamera
              ref={ref => {
                this.camera = ref;
              }}
              faceDetectionLandmarks={RNCamera.Constants.FaceDetection.Landmarks.all}
              onFacesDetected={this.onFacesDetected}
              onFaceDetectionError={this.onFaceDetectionError}
              style = {styles.preview}
              type={RNCamera.Constants.Type.front}
              flashMode={RNCamera.Constants.FlashMode.on}
              permissionDialogTitle={'Permission to use camera'}
              permissionDialogMessage={'We need your permission to use your camera phone'}
            />
            <Text>It's visible in live. but it's not visible on view shot</Text>
          {/* {this.renderLandmarks()} */}
</ViewShot>
```
And I can see this Text component in live, but unfortunately it isn't contained in view shot result image. This also concerns other components as well.
I've found this [topic on StackOverflow](https://stackoverflow.com/questions/50924848/screen-shot-in-react-native-android) which describes my problem, but without any working solution
#### Version & Platform
react-native@0.57.8
└── react-native-view-shot@2.5.0

**Platform:** Android

#### Expected behavior
Elements which are drawn on top of react native camera preview are visible in snapshot
#### Actual behavior
Elements which are drawn on top of react native camera preview aren't visible in snapshot

**Comment by gre** [comment]
Yes, I don't think it will be easy to offer a cross-library dependencies unless we have a way to interop between react native libraries but it's pretty tricky. I think what you are looking for is a way to get a frame from the Camera natively
if doing effect over it, then you can use in second step the camera snapshot and draw something on top and do a second shot.
