### ISSUE TITLE
captureRef failed to capture view

### ISSUE THREAD

**Issue by BhadreshNimble** [gre/react-native-view-shot#195]
captureRef failed to capture view

```
<View ref="viewShotRef">
<Image source={{ uri: imageUri }} />
</View>
```

method body:
captureRef(this.refs.viewShotRef, {
      format: "jpg",
      quality: 0.8,
    }).then(
      uri => {
      }
    );

platform:android
react-native-view-shot: 2.5.0,
react-native: 0.56.0,

Set image and capture the view and show image to other image view 
first time it's capture proper image and shown to image view
when I changed the image and capture it to second time it's show first image.

**Comment by cielu** [comment]
@BhadreshNimble  Have you ever soloved this problem ?

**Comment by gre** [comment]
the report does not contain enough information to conclude anything.

Ideally, please create an `example/` screen that reproduce the problem. alternatively, more detail is needed.
