### ISSUE TITLE
captureRef resolved with blank image

### ISSUE THREAD

**Issue by CharlyPoppins** [gre/react-native-view-shot#198]
#### Version & Platform
expo@31.0.6
react-native-view-shot@2.5.0

**Platform:** iOS and Android

#### Expected behavior
Capturing the target View and its children.

#### Actual behavior
Resolve with a blank image without throwing an exception.

#### Steps to reproduce the behavior
I have a **View** with a child **Image** displaying a large picture.
If the picture is too heavy **captureRef** resolve with a blank image.
If I resize the picture to lower its weight, **captureRef** resolve correctly the target **View** an its children.

I tried to debug **EXViewShot.m** but did not manage to find something.

**Comment by jiantongc** [comment]
It's very likely your view contains some unsupported components.

> Some special components are unfortunately not supported. If you have a View that contains one of an unsupported component, the whole snapshot might be compromised as well.

**Comment by CharlyPoppins** [comment]
I re-checked the interoperability table and there is no listed unsupported components.

Seems weird because the behaviour is not consistent. I'm snapshoting the same parent component.

Blank snapshot appears when the picture is too large, even if I remove the **<Image>** inner component
I'm a bit confused ^^ .

**Comment by ytl6547** [comment]
Same issue, is there any solution for this?

**Comment by sllvn** [comment]
I had the same problem (snapshotted view being too tall, resulting in a blank image).

I was able to work around this (for iOS only) per https://stackoverflow.com/a/25704861 by changing `RNViewShot.m`:

```objective-c
success = [rendered drawViewHierarchyInRect:tempRect afterScreenUpdates:YES];
```

to

```objective-c
[rendered.layer renderInContext:UIGraphicsGetCurrentContext()];
```

And because `renderInContext` returns void instead of bool, I've had to remove the `success` check. This is a kludgy solution and perhaps someone else can produce a more reliable fix.

**Comment by gre** [comment]
should we revive https://github.com/gre/react-native-view-shot/pull/112 ?

**Comment by Mitesh-2009** [comment]
[rendered.layer renderInContext:UIGraphicsGetCurrentContext()]; not working to capture scrollview contents

**Comment by damikdk** [comment]
@Mitesh-2009 and any tranforms too, btw

**Comment by awadeyar** [comment]
Any update on this?
as renderInContext does the trick why can't you update the library?

**Comment by gre** [comment]
renderInContext is not suitable specifically because it creates regression on the snapshot of some content ( https://github.com/gre/react-native-view-shot/pull/269#issuecomment-581115217 )

We could introduce a parameter that allow to configure the strategy to use tho. PR welcomed 👍

**Comment by gre** [comment]
oh actually it was done already! the option is there :) https://github.com/gre/react-native-view-shot/commit/8e251952981c71f9df081d5662ba035beda7eb7f

**Comment by ADLsourceCode** [comment]
Getting blank image on android, iOS works well , Below is the code :-
 
```

"react-native-view-shot": "^3.1.2",



  <View style={styles(theme).container}>
        <View collapsable={false}  style={[styles(theme).digitalView]} ref={viewRef}>
          <DigitalFlyar barberUser={barberUser} isTheme={isTheme} />
        </View>

<Button text={strings.download} onPress={downloadImage} style={styles(theme).buttonView} />


const downloadImage = async () => {
   console.warn("Download");
   try {
    // react-native-view-shot caputures component
    const format = Platform.OS === "android" ? "raw" : "png";
const result = Platform.OS === "android" ? "zip-base64" : "base64";
    captureRef(viewRef, {
      format: 'jpg',
      quality: 0.8,
      result,
    }).then(data => {
      // expected pattern 'width:height|', example: '1080:1731|'
      const resolution = /^(\d+):(\d+)\|/g.exec(data);
      const base64 = data.substr((resolution || [''])[0].length || 0);
      // console.warn("IMAGE DOWNLOAD",base64);
      onShareImage('data:image/jpeg;base64,' + base64);
    });
  } catch (error) {
    console.warn(error);
  }
  };

  const onShareImage = async (url: string) => {
    try {
      await Share.open({
        title: 'Barbr',
        url: url,
        failOnCancel: false,
        type: 'image/jpeg',
      })
        .then(res => {
          console.log(res);
          navigation.goBack();
        })
        .catch(err => {
          err && console.log('err', err);
        });
    } catch (error) {
      //@ts-ignore
      console.warn(error);
      showAlert('', error.message);
    }
  };
```

**Comment by ryanSoftwareEngineer** [comment]
having issues as well

**Comment by Accoladecreative** [comment]
I fixed by wrapping my component with this
`<ViewShot ref={viewShotRef} options={{ format: 'jpg', quality: 0.9 }}>` and using
`const imageURI = await viewShotRef.current.capture();`
it worked for me after many days of debugging, i hope this will help someone
