### ISSUE TITLE
save as base64 throw error

### ISSUE THREAD

**Issue by Tomatoo** [gre/react-native-view-shot#20]
when i save image as base64, throw a error, and set result to 'data-uri' is same.

RN version: 0.36.1.

code:
`
RNViewShot.takeSnapshot(this.ref, {
      format: "png",
      quality: 0.8,
      result: 'base64',
    })
`

error:

> 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106df8d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010642bdeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106cb1a52 -[__NSPlaceholderArray initWithObjects:count:] + 290
	3   CoreFoundation                      0x0000000106d0e0b4 +[NSArray arrayWithObjects:count:] + 52
	4   mofang_app                          0x0000000102908edf -[RCTPhotoLibraryImageLoader loadImageForURL:size:scale:resizeMode:progressHandler:partialLoadHandler:completionHandler:] + 447
	5   mofang_app                          0x0000000102a155d3 __118-[RCTImageLoader _loadImageOrDataWithURLRequest:size:scale:resizeMode:progressBlock:partialLoadBlock:completionBlock:]_block_invoke.191 + 355
	6   libdispatch.dylib                   0x0000000107edbd9d _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x0000000107efc3eb _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x0000000107ee282c _dispatch_queue_drain + 2215
	9   libdispatch.dylib                   0x0000000107ee1d4d _dispatch_queue_invoke + 601
	10  libdispatch.dylib                   0x0000000107ee4996 _dispatch_root_queue_drain + 1420
	11  libdispatch.dylib                   0x0000000107ee4405 _dispatch_worker_thread3 + 111
	12  libsystem_pthread.dylib             0x00000001082394de _pthread_wqthread + 1129
	13  libsystem_pthread.dylib             0x0000000108237341 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by gre** [comment]
are you sure it's throwing at the time you call `takeSnapshot` ?
Your stacktrace don't have react-native-view-shot, it seems to crash when you set back this uri to an image?
the library don't use `RCTImageLoader` afaik
