### ISSUE TITLE
android build failed

### ISSUE THREAD

**Issue by zlf911216** [gre/react-native-view-shot#200]
./gradlew clean cleanBuildCache assembleDebug

> Task :react-native-view-shot:extractDebugAnnotations
Warning: fr.greweb.reactnativeviewshot.ViewShot.Formats: The typedef annotation should have @Retention(RetentionPolicy.SOURCE)
Warning: fr.greweb.reactnativeviewshot.ViewShot.Results: The typedef annotation should have @Retention(RetentionPolicy.SOURCE)

 ./gradlew assembleRelease

.....
`          /Users/zhenglingfeng/WebstormProjects/Movie_app/node_modules/react-native-view-shot/android/build/intermediates/res/compiled/release/values-ja_values-ja.arsc.flat\
          -R\
          /Users/zhenglingfeng/WebstormProjects/Movie_app/node_modules/react-native-view-shot/android/build/intermediates/res/compiled/release/drawable-v23_abc_control_background_material.xml.flat\
          -R\
          /Users/zhenglingfeng/WebstormProjects/Movie_app/node_modules/react-native-view-shot/android/build/intermediates/res/compiled/release/xml_preferences.xml.flat\
          -R\
          /Users/zhenglingfeng/WebstormProjects/Movie_app/node_modules/react-native-view-shot/android/build/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\
          /Users/zhenglingfeng/WebstormProjects/Movie_app/node_modules/react-native-view-shot/android/build/intermediates/res/compiled/release/drawable-xhdpi-v4_abc_ic_menu_selectall_mtrl_alpha.png.flat\
          --auto-add-overlay\
          --non-final-ids\
          -0\
          apk\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0
`

platform:android
react-native-view-shot: 2.5.0,
react-native: 0.58.3,

**Comment by ps1312** [comment]
Read the first 2 answers from this question, solved for me: https://stackoverflow.com/questions/51508578/react-native-android-release-build-failing-gradle

**Comment by gre** [comment]
it should be fixed. please test with latest version. we have an example that properly works with RN 0.60
