### ISSUE TITLE
capture screen did not take with modal opened, it just take current screen behind!

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [gre/react-native-view-shot#202]
actions take screen capture call on modal view when opened

**Comment by Taym95** [comment]
Can you give a code example, please?

**Comment by Taym95** [comment]
This issue has nothing to do with `react-native-view-shot`!

`class ExampleCaptureModal extends Component {
  onCapture = uri => {
    this.refs.viewShot.capture().then(uri => {
      console.log("do something with ", uri);
    });
  }
  render() {
    return (
      <ViewShot ref="viewShot" options={{ format: "jpg", quality: 0.9 }}>
        <Modal>Your Modal content</Modal>
      </ViewShot>
    );
  }
}`

Your Modal should be wrapped with ViewShot.

**Comment by nguyenvanphuc2203** [comment]
@Taym95  i got this erorr with your example code
![screen shot 2019-03-06 at 9 11 09 am](https://user-images.githubusercontent.com/33291479/53851305-e64cbb00-3ff0-11e9-9ca0-912e9fcaa71d.png)

**Comment by gre** [comment]
need to have more precision / code to reproduce it.

A good way to test it is to use the `example/` app and add one more screen to it to attempt to reproduce the bug and so we can later add that new example when we fix the bug.

**Comment by xclidongbo** [comment]
> @Taym95 i got this erorr with your example code
> ![screen shot 2019-03-06 at 9 11 09 am](https://user-images.githubusercontent.com/33291479/53851305-e64cbb00-3ff0-11e9-9ca0-912e9fcaa71d.png)
> so want capture screen have modal and screen behind

+1

**Comment by Taym95** [comment]
> > @Taym95 i got this erorr with your example code
> > ![screen shot 2019-03-06 at 9 11 09 am](https://user-images.githubusercontent.com/33291479/53851305-e64cbb00-3ff0-11e9-9ca0-912e9fcaa71d.png)
> > so want capture screen have modal and screen behind
> 
> +1

@xclidongbo create a reproducing GitHub repo please, maybe we can help you.
