### ISSUE TITLE
full page screenshot?

### ISSUE THREAD

**Issue by rahul-desai3** [gre/react-native-view-shot#204]
### Help wanted
`capture()` currently takes screenshot of only what is visible on the screen. How do I take screenshot of the full page, including the content that is flowing out of the screen?
For example, [Full Page Screen Capture](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl) chrome extension that takes full page screenshots on Chrome.

#### Version & Platform

```
yarn list react-native react-native-view-shot
├─ react-native-view-shot@2.5.0
└─ react-native@0.57.1
```

**Platform:** iOS and Android, both

#### Expected behavior
Take full page screenshot, including the content that is flowing out of the screen

#### Actual behavior
Taking screenshot of only what is visible on the screen

#### Steps to reproduce the behavior

This is what I have in `componentDidMount`:
```
  componentDidMount () {
    this.refs.viewShot.capture().then(uri => {
      console.log("do something with ", uri);
    });
  }
```

**Comment by gre** [comment]
I don't think it's technically possible, not easily at least.

Typically Android don't allow to create a pixel buffer that is bigger than the phone's screen resolution.
