### ISSUE TITLE
Can u update release tags ?

### ISSUE THREAD

**Issue by ranuwp** [gre/react-native-view-shot#205]
### feature request

Update release tags.

### bug report 

When i `npm install react-native-view-shot` i only get the latest version `2.5.0` that release last year. I got build error that can be solved by using the latest master.

#### Steps to reproduce the behavior
`npm install react-native-view-shot` the latest version is 2.5.0, need to be update for the newest one for build error.

**Comment by fwh1990** [comment]
I can't use this package in RN-0.59.5

And anybody know is there another package can use instead of this one?

**Comment by fwh1990** [comment]
@ranuwp 
As author doesn't publish new version, we can install package by git repo:
```bash
yarn add react-native-view-shot@https://github.com/gre/react-native-view-shot.git
```
In this way, you can get the newest code.
