### ISSUE TITLE
生成的图片质量很低

### ISSUE THREAD

**Issue by jeekliang** [gre/react-native-view-shot#206]
### feature request

BUG

### bug report 
this.refs.viewShot.capture().then(uri => {
      console.log("do something with ", uri);
      生成的图片质量很低
});

#### Version & Platform

```bash
npm ls react-native react-native-view-shot #<- PASTE CMD RESULT IN HERE
```
react-native: 0.57.4
react-native-view-shot: 2.5.0

**Platform:** iOS? Android?
Android

#### Actual behavior
实际生成的图片很模糊

**Comment by gre** [comment]
你好,

Have you tried different options. I have doubt anything can be done about it because we basically just use what Android offers us for rasterization of views. If it is blurry it might be because of Android.

When you don't provide a width or height, it's supposed to use the pixel size which shouldn't be blurred.

**Comment by jeekliang** [comment]
> 你好,
> 
> Have you tried different options. I have doubt anything can be done about it because we basically just use what Android offers us for rasterization of views. If it is blurry it might be because of Android.
> 
> When you don't provide a width or height, it's supposed to use the pixel size which shouldn't be blurred.

captureRef(this.refs.viewShot, {
            format: "png",
            quality: 1.0
        }).then((uri, error) => {
            // console.log('result', uri, error)
            if(!error) {
                NativeModules.sharemodule.shareImage(uri, SharePlatform.WECHAT, (result)=>{
                   // 生成的图片依然很模糊
                });
            }
        })

**Comment by jeekliang** [comment]
> 你好,
> 
> Have you tried different options. I have doubt anything can be done about it because we basically just use what Android offers us for rasterization of views. If it is blurry it might be because of Android.
> 
> When you don't provide a width or height, it's supposed to use the pixel size which shouldn't be blurred.

我已经修复了此问题 @gre

**Comment by cielu** [comment]
@jeekliang  你的安卓手机可以用组件截屏分享吗？我分享出来的是白色背景。。。

**Comment by jeekliang** [comment]
> @jeekliang 你的安卓手机可以用组件截屏分享吗？我分享出来的是白色背景。。。

**Comment by jeekliang** [comment]
> @jeekliang 你的安卓手机可以用组件截屏分享吗？我分享出来的是白色背景。。。

@cielu ViewShot 设置 backgroundColor

**Comment by cielu** [comment]
@jeekliang  不是，不同的安卓版本会生成不同的东西，我有的安卓手机正常截图，有的直接是白色底

**Comment by neohuiji** [comment]
@jeekliang  你好， 能问下你是如何解决图片质量低的问题的吗？
我现在在做分享到小程序， 使用这个组件截出来的图质量非常差

**Comment by wuweijian1997** [comment]
> > 你好,
> > Have you tried different options. I have doubt anything can be done about it because we basically just use what Android offers us for rasterization of views. If it is blurry it might be because of Android.
> > When you don't provide a width or height, it's supposed to use the pixel size which shouldn't be blurred.
> 
> 我已经修复了此问题 @gre

您好，请问你是修复了模糊的问题吗？能请教一下解决办法吗？

**Comment by hanxiaofeng** [comment]
@jeekliang 请问你是如何解决模糊问题的？

**Comment by FengFuLiu** [comment]
> @jeekliang 请问你是如何解决模糊问题的？

亲测ios后缀保存为 .raw 格式后非常清晰。
