### ISSUE TITLE
spacer image on iphone device not on simulator

### ISSUE THREAD

**Issue by callcter** [gre/react-native-view-shot#208]
#### Bug

when i use **this.refs.viewShot.capture().then(uri => {})**, create a temp image file and the image is a spacer image on iPhone device. iOS simulator & android is ok

#### Version & Platform

react-native 0.57.1
react-native-view-shot 2.5.0
platform iOS

**Comment by gre** [comment]
not enough information provided to reproduce. could you try again on latest version of react-native-view-shot?

thanks
