### ISSUE TITLE
Could not find method safeExtGet() for arguments [supportLibVersion, 27.+]

### ISSUE THREAD

**Issue by maoweipeng** [gre/react-native-view-shot#211]
#### Version: 2.5.0

**Platform:** Android
**gradle version:** 4.4

Reported this error in this line of code when I built the Android project.
`implementation "com.android.support:support-v4:${safeExtGet('supportLibVersion', '27.+')}"`
Maybe this is not supported now.

When I change to
`implementation 'com.android.support:support-v4:27.1.1'`
it works fine

**Comment by dipo1** [comment]
The safeExtGet function is probably not defined.
Make sure the function is defined before calling it.

```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

implementation "com.android.support:support-v4:${safeExtGet('supportLibVersion', '27.+')}"

```
You may also use the logic directly

`
implementation "com.android.support:support-v4:${rootProject.ext.has('supportLibVersion') ? rootProject.ext.supportLibVersion : '27.+'}"

`

**Comment by gre** [comment]
I cannot reproduce on latest `example` that runs with a fresh project created with `react-native init` and RN 0.60

**Comment by rikur** [comment]
Probably the same issue, androidx doesn't seem to support annotations?

```
ViewShot.java:11: error: cannot find symbol
import androidx.annotation.IntDef;

..

ViewShot.java:13: error: cannot find symbol
import androidx.annotation.StringDef;

..

RNViewShotModule.java:8: error: cannot find symbol
import androidx.annotation.NonNull;```

etc.

**Comment by dipo1** [comment]
> I cannot reproduce on latest `example` that runs with a fresh project created with `react-native init` and RN 0.60

It's not an example. I was explaining to @maoweipeng why he is getting the error.
He must define the safeExtGet function before calling it.
