### ISSUE TITLE
Twilio Video Views appears as black boxes

### ISSUE THREAD

**Issue by jedabero** [gre/react-native-view-shot#216]
### bug report 
In my application I have a requirement where a user can take a screenshot at any time during a video conference. I'm using react-native-twilio-video-webrtc for the conference part and this library for screenshots.

I should note that when taking a screenshot with the device shorcut to do so the video views appear normally.

#### Version & Platform

```bash
npm ls react-native react-native-view-shot 
TwilioTest@0.0.1 /redacted/project/location/TwilioTest
├── react-native@0.59.8 
└── react-native-view-shot@2.6.0 
```
`package.json`
```json
{
  "name": "TwilioTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-twilio-video-webrtc": "https://github.com/blackuy/react-native-twilio-video-webrtc",
    "react-native-view-shot": "^2.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Platform:** Android, have not tested in iOS

#### Expected behavior
Screen captured with view-shot should show video views normally

#### Actual behavior
Screen captured with view-shot should shows video views as black boxes

#### Steps to reproduce the behavior

1. Create a new project `react-native init NewProjectName`
2. Add this library
3. Add [react-native-twilio-video-webrtc](https://github.com/blackuy/react-native-twilio-video-webrtc)
4. You'll need at least two devices (either two android emulators, one emulator and one android phone, two android phones or two iphones)

I've setup a minimal project here
https://github.com/pluriza/twilio-view-shot
The creation of the accessToken can be done at https://www.twilio.com/console/video/runtime/testing-tools

I've also reported this to react-native-twilio-video-webrtc @ [issue 199](https://github.com/blackuy/react-native-twilio-video-webrtc/issues/199)

**Comment by slycoder** [comment]
Yeah, it's probably how the surface is rendered (using a GL blt) on Android.  If you look at the view shot page, you'll see that lots of similar components are not supported by ViewShot including react-native-video and react gl.

**Comment by gre** [comment]
I think this is out of scope of this library, you are probably better looking for either an in-house solution or a feature in react-native-twilio-video-webrtc / react-native-webrtc that would solve what you need from the native side.
