### ISSUE TITLE
How to record view as video

### ISSUE THREAD

**Issue by devdeepakrathod** [gre/react-native-view-shot#217]
I want to record a view in form of a video, any suggestion will be so helpful thanks in advance

**Comment by ami9000** [comment]
@devdeepakrathod did you ever find this? Also looking...

**Comment by shads06** [comment]
@devdeepakrathod @ami9000 I'm looking as well.
Other solution which I'm exploring is taking burst shot multiple shots and display them. Do you guys think it's feasible?

**Comment by ami9000** [comment]
> @devdeepakrathod @ami9000 I'm looking as well.
> Other solution which I'm exploring is taking burst shot multiple shots and display them. Do you guys think it's feasible?

If it helps, I tried https://github.com/code-matt/react-native-replaykit which worked for me on iOS. However, the ReplayKit framework frequently asks for screen record permissions which isn't the UX I need. 

@shads06 your solution may be feasible.  I've definitely seen solutions with frame by frame shots being fed into an AVAssetWriter to output a video on the native side. Still figuring out if it could work for react native views.

**Comment by Taym95** [comment]
You can use [react-native-screen-recorder ](https://github.com/ycswaves/react-native-screen-recorder)
