### ISSUE TITLE
Support iOS App Extension

### ISSUE THREAD

**Issue by zek** [gre/react-native-view-shot#218]
### feature request

When I am trying to use this library on iOS App Extension it gives me error

#### Version & Platform

react-native-view-shot@2.6.0

**Platform:** iOS

#### Actual behavior

![image](https://user-images.githubusercontent.com/3463291/58655827-b24d1180-8323-11e9-94e0-54b408675022.png)

'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

#### Steps to reproduce the behavior
https://github.com/alinz/react-native-share-extension

**Comment by Oguntoye** [comment]
https://github.com/OneSignal/react-native-onesignal/issues/1272

May be related to this.
