### ISSUE TITLE
captureRef on Android is not faster with raw image format

### ISSUE THREAD

**Issue by naftalibeder** [gre/react-native-view-shot#220]
### Bug report

On Android, running `captureRef` with

    { format: 'raw', result: 'zip-base64' }

 takes the same amount of time as

    { format: 'png', result: 'base64' }

or similar.

#### Version & Platform

```bash
react-native@0.57.7 
react-native-view-shot@2.6.0 
```

**Platform:** Android

#### Expected behavior

Capturing a full-screen view, using `captureRef` with the `png/base64` configuration, takes about 250-400ms. Per the claim in [this section](https://github.com/gre/react-native-view-shot#raw-images), it should take <10% as long to capture the same view using `raw/zip-base64`.

#### Actual behavior

It actually takes the same amount of time, 250-400ms.

#### Steps to reproduce the behavior
I can put together a simplified example if needed, but I wanted to check if this is a known issue, or if there's anything else I can try to speed it up (raw _or_ png). Thanks!

**Comment by OleksandrKucherenko** [comment]
Capturing is faster... transfer to JS side is always a bottleneck. If you want the fastest possible way, try RAW format and temporary file.

**Comment by OleksandrKucherenko** [comment]
In two words:
- capture on native code side happens faster
- converting of RAW zip-base64 to PNG takes a lot of time, its CPU intensive operation. When code assigns ARGB buffer to PNG instance, PNG lib starting ZIP operation according to minimize PNG size. 

That is why in the Warnings section mentioned that you should think twice, will it work for your code or not.

**Comment by naftalibeder** [comment]
Oh so in other words, saving a file to disk and reading it from the JS
might actually be faster than passing it over the bridge? Just checking I
read this right, because that would be surprising to me. Thanks!

**Comment by naftalibeder** [comment]
I tried it with `raw` and `tmpfile`, and it does seem a little faster. Certainly not 16ms like claimed, but ~160ms, which is a definite improvement.

**Comment by OleksandrKucherenko** [comment]
In my case, were used several processes for capturing and processing the images.

Pipelines are:  
Device <--> Capture Server --> RAW images to File System
RAW files from File System --> Transforming x N --> PNG
