### ISSUE TITLE
[feature-request] Support web

### ISSUE THREAD

**Issue by NiciusB** [gre/react-native-view-shot#224]
Currently, it seems like react-native-view-shot just returns `undefined` when ran in a web browser with react-native-web

I understand why this happens, but it might be interesting to wrap a library like [html2canvas](http://html2canvas.hertzen.com/) to provide at least some basic functionality

I will happily send a pull request if @gre thinks that it's within the scope of the package

**Comment by gre** [comment]
it can happens yeah 😍

**Comment by dario30186** [comment]
Hi,
did you add support for Web ?

**Comment by NiciusB** [comment]
Hi @dario30186. The [merge request](https://github.com/gre/react-native-view-shot/pull/226) is still open, so the npm `react-native-view-shot` package does not have web support.

You could use my fork `react-native-view-shot-with-web-support`(https://github.com/NiciusB/react-native-view-shot), but it will not be perfect.
It uses [html2canvas](https://html2canvas.hertzen.com/) which has some drawbacks, more notably the text kerning can be pretty weird.

**Comment by likeSo** [comment]
Hello, when will this feature be merged? @gre @NiciusB

**Comment by ShivamJoker** [comment]
@gre please respond

**Comment by dackom** [comment]
> You could use my fork: `react-native-view-shot-with-web-support` on npm (https://github.com/NiciusB/react-native-view-shot). I have to warn, it will not be perfect. It uses [html2canvas](https://html2canvas.hertzen.com/) which has some drawbacks, more notably the text kerning can be pretty weird.

@NiciusB this is awesome. Works perfectly for me. Thanks for saving a ton of hours. 😍

**Comment by anurag55555** [comment]
Is this PR merged ?

**Comment by gre** [comment]
The PR can't be merged because it conflicts with upstream. Please reopen one that can be merged 🙏

**Comment by chrispader** [comment]
I'm going to continue the work of @NiciusB in [this PR](https://github.com/gre/react-native-view-shot/pull/476) 🚀

**Comment by chrispader** [comment]
@gre could you please also push a new version on NPM. :) That would be great. Thanks for merging this so soon 🥳

**Comment by NiciusB** [comment]
Nice! Great job @chrispader 🤘

**Comment by chrispader** [comment]
@NiciusB thanks to you, you did most of the work already haha 😉
