### ISSUE TITLE
Possible Unhandled Promise Rejection can't find variable: viewShot

### ISSUE THREAD

**Issue by skuttenkuler** [gre/react-native-view-shot#225]
import ViewShot from "react-native-view-shot";
componentDidMount () {
        this.refs.viewShot.capture().then(uri => {
            console.log("success")
            CameraRoll.saveToCameraRoll(viewShot, ['photo']);

        });
      }

this.state = {
imageURI : 'file:///sdcard/screenshot.jpg',
}

<ViewShot ref="viewShot" options={{ format: "jpg", quality: 0.9 }}>
 

#### Version & Platform

```bash
├── react-native@0.59.8
└── react-native-view-shot@2.6.0
```

**Platform:** 
Android

#### Expected behavior
To take View Snap shot then save snapshot to Android Camera Roll
#### Actual behavior
![Screen Shot 2019-06-26 at 8 39 42 PM](https://user-images.githubusercontent.com/33381106/60234366-d5061380-9858-11e9-9f26-de90b720638d.png)

**Comment by sergiosrax** [comment]
Is happening for me too

**Comment by gre** [comment]
please check with latest release (3.0.2) and prefer the use of React.Ref (via React.createRef or useRef)
