### ISSUE TITLE
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

### ISSUE THREAD

**Issue by klawdyo** [gre/react-native-view-shot#227]
### bug report 
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

#### Version & Platform
view-shot: 2.6.0
react: 16.8.6
react-native: 0.60.0

**Platform:** Android

#### Expected behavior

get print screen  then save in camera roll

#### Actual behavior
![image](https://user-images.githubusercontent.com/100168/60893263-00b0d280-a237-11e9-85a9-70d8f57c78a6.png)

#### Steps to reproduce the behavior

```js
  async share() {
    const uri = await this.refs.viewShot.capture()
    // Salvando
    CameraRoll.saveToCameraRoll(uri);
    alert('savo')
  }
```

**Comment by gre** [comment]
this is now fixed
