### ISSUE TITLE
Detect snap

### ISSUE THREAD

**Issue by YusufBesim** [gre/react-native-view-shot#23]
Is there a any way for detect user manual snapshot ?

**Comment by gre** [comment]
mmh, it's probably off-topic of this library. You need to look at native events.

maybe see:

- for iOS: http://stackoverflow.com/questions/2121970/notification-of-or-detecting-screenshot-being-taken
- for Android: http://stackoverflow.com/questions/32243946/how-to-catch-screen-capture-event-on-android-devices

**Comment by numera19** [comment]
https://github.com/emilemoureau/react-native-screen-recorder-detect

**Comment by numera19** [comment]
yess, [https://github.com/emilemoureau/react-native-screen-recorder-detect](url)
