### ISSUE TITLE
Can't find variable: nextProps

### ISSUE THREAD

**Issue by meraklis56** [gre/react-native-view-shot#232]
#84 # bug report 

I am following the guide to install and use the view shot, but instead i get "Can't find variable: nextProps"

#### Version & Platform

```
react-native-view-shot@3.0.0
"react-native": "^0.59.10"
```

**Platform:** Android, probably iOS

#### Expected behavior

It should return the screenshot

#### Actual behavior

It returns a reference error

#### Steps to reproduce the behavior

```
onCapture = uri => {
    console.log("do something with ", uri);
};

render() {
        return (
        ....
       <ViewShot onCapture={this.onCapture} captureMode="mount"> 
       <Text>...Something to rasterize...</Text>
       </ViewShot>
      ....
      )
}
```

**Comment by zxf107** [comment]
The same problem happened to react native 0.60+

**Comment by gre** [comment]
this is now fixed.

The new `example` app also runs with React Native 0.60
