### ISSUE TITLE
Where could I find the screenshots?

### ISSUE THREAD

**Issue by Gusabary** [gre/react-native-view-shot#233]
### feature request

(It seems not to be a feature request but I am sure it isn't a bug report)

#### Version & Platform

```bash
react-native @0.59.9
react-native-view-shot @2.6.0
```

**Platform:** Android

#### Expected behavior
I have written code like this:
```react
this.refs.A.capture().then(uri => {
            console.log("Image saved to ", uri);
        });
```
and I got this:
```
'Image saved to', 'file:///data/user/0/com.front_end/cache/ReactNative-snapshot-image5134457190681563875.jpg'
```
I expected to find the screenshot at this uri.
#### Actual behavior
It looks ok, but I cannot find the uri in my phone.
maybe I need root privilege?
#### Steps to reproduce the behavior
just that code in single line

**Comment by gre** [comment]
the file are sandboxed inside the app's data folder so probably not accessible from external point of view. They also are meant to be **temporary files** and they get removed at some point.

If you want more persistence, please check https://github.com/gre/react-native-view-shot#saving-to-a-file
