### ISSUE TITLE
程序包中的类过期，需要手动替换

### ISSUE THREAD

**Issue by Yieron** [gre/react-native-view-shot#236]
import android.support.annotation.IntDef;
import android.support.annotation.NonNull;
import android.support.annotation.StringDef;
上面三个需要替换为下面三个
import androidx.annotation.IntDef;
import androidx.annotation.NonNull;
import androidx.annotation.StringDef;
程序才能运行！
![image](https://user-images.githubusercontent.com/16173466/61778877-2e4e6c00-ae32-11e9-9435-93aae8db1774.png)
![image](https://user-images.githubusercontent.com/16173466/61779074-9a30d480-ae32-11e9-9807-001aedcc996e.png)

**Comment by gre** [comment]
i'm not very familiar with androidx.annotation but it seems to be the new way to import these classes https://developer.android.com/reference/android/support/annotation/IntDef

maybe there is something to configure in your side to make it work? https://stackoverflow.com/a/53722247

@catnuxer do you have a better understanding? thanks

**Comment by afeichuanqi** [comment]
I am the opposite. I have to import import android.support.annotation.IntDef;
Import android.support.annotation.NonNull;
Import android.support.annotation.StringDef;

**Comment by catnuxer** [comment]
@gre Hi gre, the android new class API jitpack in 2019 have been migrate to androidx and have been new mapping, I read the documentation from https://developer.android.com/jetpack/androidx/migrate

This for for example
The old class
android.support.annotation.IntDef

Use new class
androidx.annotation.IntDef

Don't forget to update your sdk on android studio platform 
 
I've tested on RN 0.60.x platform which is 0.60 version support androidx already. 

I hope it's help you, @Yieron  @afeichuanqi

**Comment by gre** [comment]
Ok thanks. We'll stick to latest standard then. I hope everyone find a way to migrate otherwise you can fork this library.
Cheers

**Comment by xuejunyou** [comment]
> import android.support.annotation.IntDef;
> import android.support.annotation.NonNull;
> import android.support.annotation.StringDef;
> 上面三个需要替换为下面三个
> import androidx.annotation.IntDef;
> import androidx.annotation.NonNull;
> import androidx.annotation.StringDef;
> 程序才能运行！
> ![image](https://user-images.githubusercontent.com/16173466/61778877-2e4e6c00-ae32-11e9-9435-93aae8db1774.png)
> ![image](https://user-images.githubusercontent.com/16173466/61779074-9a30d480-ae32-11e9-9807-001aedcc996e.png)

你好，我遇到了同样的问题，可是最新版本的文件已经替换了，我这边还是不能运行，请问你已经解决问题了吗

**Comment by catnuxer** [comment]
> 你好，我遇到了同样的问题，可是最新版本的文件已经替换了，我这边还是不能运行，请问你已经解决问题了吗

Hi dude, please make sure use master branch this github repo @gre  and use platform RN 0.60.x version, then try to use the example, I also add scrollview example already. Then put your problems in here. If I see the gradle plugin show error try using sdk 23, please change your sdk to 28 version, and update your sdk android studio. Lets see how is going on.

Cheers

**Comment by wenkangzhou** [comment]
我用RN0.59，不支持androidx，需要手动换四个库：
import android.util.Pair;
import android.support.annotation.IntDef;
import android.support.annotation.NonNull;
import android.support.annotation.StringDef;
