### ISSUE TITLE
Cannot read property 'captureScreen' of undefined

### ISSUE THREAD

**Issue by KrinaPatel2018** [gre/react-native-view-shot#238]
I'm using these version
"react-native": "0.60.4",
"react-native-view-shot": "^3.0.0"

I found this error: "Cannot read property 'captureScreen' of undefined" 
Platform: iOS

Please help me to solve this
Thanks

**Comment by pssgo** [comment]
+1

**Comment by gmverdon** [comment]
Did you run `cd ios && pod install && cd ..`?

**Comment by gre** [comment]
this is a link / autolink issue. i'll get a new version out soon with 0.60 support too.
