### ISSUE TITLE
your example is not running .....can you tell me why ??

### ISSUE THREAD

**Issue by fayezkabirCBNITS** [gre/react-native-view-shot#239]
#### Version & Platform

```bash
npm ls react-native react-native-view-shot #<- PASTE CMD RESULT IN HERE
```

**Platform:** iOS? Android?

**Comment by Taym95** [comment]
This is a realy bad issue! at least give a reproducing example with error message and a nice issue title not `....can you tell me why ??` wth!

**Comment by gre** [comment]
i'll publish a fresh new example in a few hours (with latest React Native too).
