### ISSUE TITLE
[Android] No options leads to error

### ISSUE THREAD

**Issue by sodik82** [gre/react-native-view-shot#24]
I am using simple code to take snapshots:
```
takeSnapshot(view)
    .then(uri => { ...
```
works fine on IOS but fails on android `Attempt to invoke ... hasKey ... on a null object reference` and pointung to line [49](https://github.com/gre/react-native-view-shot/blob/master/android/src/main/java/fr/greweb/reactnativeviewshot/RNViewShotModule.java#L49).

From the documentation itself it is not 100% clear if options are mandatory however flow definition shows that they should be https://github.com/gre/react-native-view-shot/blob/master/index.js#L9

**Comment by gre** [comment]
Good catch.
Yeah I think options should remain optional (all option field should be fallback to some value).

I think the library JS implementation should probably merge the user options with defaults so the implementation receives the same and we can factorize all the fallback code (and assume both the implementation receives resolved options, all options are provided).


I'll probably work on that next weekend or feel free to provide a PR.

**Comment by gre** [comment]
fixed in 1.8.0
