### ISSUE TITLE
Is there any way to capture screen shoot without rendering the view?

### ISSUE THREAD

**Issue by shubhamdeol** [gre/react-native-view-shot#242]
I don't want to render the view. I just want to convert it into an image. Is there any way.
Something like this:
```javascript
const imgShoot = viewShot.capture("
<View><Text>Convert this to image</Text></View>
")
```

**Comment by gre** [comment]
There are no easy way to solve this and is beyond scope of this package. but you can render that view offscreen by offseting it away of user's visibility.
