### ISSUE TITLE
Suggest to add a CHANGELOG.md

### ISSUE THREAD

**Issue by irvingchenn** [gre/react-native-view-shot#243]
### feature request

Could not figure out clearly what had been changed in every specific version 

**Platform:** iOS and Android

#### Expected behavior

Maintain a CHANGELOG.md file in root project to tell what had been changed in every version.

#### Actual behavior

There have not a CHANGELOG.md file.

**Comment by gre** [comment]
i'll update https://github.com/gre/react-native-view-shot/releases
