### ISSUE TITLE
I want to know how you took a screenshot of the react-native-camera. Can you give me an example?

### ISSUE THREAD

**Issue by yigerendehaotianqi** [gre/react-native-view-shot#245]
#### Version & Platform

```bash
npm ls react-native react-native-view-shot #<- PASTE CMD RESULT IN HERE
```

**Platform:** iOS? Android?

**Comment by gre** [comment]
I don't think you need this library to take a camera picture, directly use `react-native-camera` **takePictureAsync** function: https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#takepictureasyncoptions-promise

thanks
