### ISSUE TITLE
can‘t resolve  these classes

### ISSUE THREAD

**Issue by wuxiii** [gre/react-native-view-shot#246]
#### Version & Platform
react-native :0.59.10
react-native-view-shot:3.0.2
**Platform:**  
Android
#### Actual behavior
gradle sync succussfully,but build failed,error info as below
![image](https://user-images.githubusercontent.com/28565020/63348759-896d7300-c38c-11e9-8892-69a8ff6e62d4.png)
can‘t resolve  these classes
![image](https://user-images.githubusercontent.com/28565020/63349037-28926a80-c38d-11e9-892c-9867a3e6c2fb.png)

Please help me to solve this
Thanks

**Comment by n417363620** [comment]
Me too!

**Comment by wuxiii** [comment]
> Me too!
use version 2.6.0
It will not be pretty, but it works.

**Comment by n417363620** [comment]
thanks

**Comment by gre** [comment]
latest version should no longer have this issue.
