### ISSUE TITLE
react native version

### ISSUE THREAD

**Issue by zhanf** [gre/react-native-view-shot#247]
hi , using {api 'com.facebook.react:react-native:+'} is not friendly to developers.
"+" is  not support old version with react-native. Every time "npm install" it cause reload lastest version with react-native,but in my project dependt many different react native  libraries.
so can you support like this:
    api "com.facebook.react:react-native:${rootProject.ext.reactNative}"

**Comment by gre** [comment]
thanks, good point, do you want to provide a PR?
