### ISSUE TITLE
Combining ViewShots

### ISSUE THREAD

**Issue by Dror-Bar** [gre/react-native-view-shot#249]
Is there any way to combine two ViewShots into a single image? In my use-case, I can't fit everything into a single ViewShot. I need to get the entire content of a Scrollview, and additionally, a floating component with position absolute.
Is this possible?

**Version & Platform**
NPM: 6.9.0
react: 16.8.3
react-native: 0.59.10
react-native-view-shot: 3.0.2
iOS & Android

**Comment by gre** [comment]
https://github.com/gre/react-native-view-shot/releases/tag/v3.3.0 added the option `useRenderInContext` which may help to solve this. This issue being a bit old (sorry for the delay) I'll close for inactivity, feel free to reopen bug if relevant.
