### ISSUE TITLE
Error: findNodeHandle failed to resolve view=undefined

### ISSUE THREAD

**Issue by rohitgoyal** [gre/react-native-view-shot#25]
Hi
I integrated rnvs few weeks back and it was working perfectly then. Suddenly I am seeing error whenever I am trying to capture screenshot. 
Here is my code for taking screenshot.

```
takeScreenShot(){
    RNViewShot.takeSnapshot(this.refs.screenshot, {
      format: "jpeg",
      quality: 0.8
    })
    .then(
      uri => this.saveScreenshot(uri),
      error => console.error("Oops, snapshot failed", error)
    );
  }
```

This is the error I am getting whenever calling takeScreenShot function.

> 2016-12-06 14:34:22.635 [error][tid:com.facebook.react.JavaScript] 'Oops, snapshot failed', { [Error: findNodeHandle failed to resolve view=undefined]
>   line: 525,
>   column: 133,
>   sourceURL: 'file:///Users/ABC/Library/Developer/CoreSimulator/Devices/17A973BC-5639-4C55-B52E-D7FE972F2651/data/Containers/Bundle/Application/87DDE253-950F-4BB2-8F4C-C8C468862DD2/MYAPP.app/main.jsbundle' }

**Comment by gre** [comment]
it looks like your ref `this.refs.screenshot` is undefined.

You should make sure you don't call takeSnapshot when your view is not yet rendered or has been unmounted.

**Comment by rohitgoyal** [comment]
@gre Sorry that was my fault actually. I corrected the refs. 
My issue is I am getting this error on Android while it is working on iOS.
'Trying to resolve view with tag 232 which doesn't exist.'

**Comment by gre** [comment]
You probably fall into one of the caveats of the Android implementation. See https://github.com/gre/react-native-view-shot/blob/master/README.md#caveats

Can you try to set collapsable={false} on the view you snapshot?
Android react-native implementation tends to "collapse" the nested view so most View don't always have a native View.

**Comment by shahen94** [comment]
@gre Thanks ! setting collapsable={false} helped me

**Comment by gerardus1995** [comment]
Hi i have the same problem and cant manage to resolve it. This is my code:

            <View style={{position:'absolute', right:45}}>
              <TouchableOpacity  onPress={()=>{
                let shareOptions = null;
                takeSnapshot(this.screenshot, {
                  format: "jpeg",
                  quality: 0.8,
                  result: "base64"
                })
                .then(
                  uri => {
                    console.log(uri);
                    shareOptions = {
                      title: "Nautal",
                      message: "Hola mundo",
                      url: uri,
                      subject: "Share Link" //  for email
                    };
                  },
                  error => console.error("Oops, snapshot failed", error)
                );
                console.log(shareOptions);
                //Share.open(shareOptions);
              }}>
                <View style={[STYLES.circleSecondary, {borderColor:'white', margin:10}]}>
                  <Icon name="share-alt" size={15} color="white" />
                </View>
              </TouchableOpacity>
            </View>

And i declare the view that i want snapshot of later in code like this:

          <View ref={(shot) => { this.screenshot = shot; }} style={[STYLES.subContainer,{paddingTop:5}]}>

When i execute the screenshot code page is already rendered but im getting the error anyway. Any ideas how to solve this?

**Comment by gre** [comment]
@gerardus1995 as said above, set `collapsable={false}` on the `View` you snapshot

**Comment by rahulmishra1991** [comment]
@gerardus1995 can you please share your code i have lots of issues.

**Comment by rahulmishra1991** [comment]
How do we this in the flat list?  I am trying renderRowItem > View dynamic reference but it's showing undefined...Please let me know if any solution...Thanks!

**Comment by rahulmishra1991** [comment]
This is my flat list code 

renderRowItem = (itemData, sectionID, index) => {
  
    Moment.locale('en');
    return (
      <View collapsable={false} ref={(shot) => { this.screenshot.itemData.item._id = shot; }} >

     </View>
   )
}

How to capture this particular view?

**Comment by michaelVictoriaDev** [comment]
collapsable={false} doent help :/
