### ISSUE TITLE
shot from react-native-view-pdf

### ISSUE THREAD

**Issue by hannanstd** [gre/react-native-view-shot#252]
Hi
how can i get shot from below package:
https://www.npmjs.com/package/react-native-view-pdf

i tested all of the methods, but this pdf viewer has scroll and shot doest get all of the content.

i need get shot from all of content that pdf viewer.

**Comment by Taym95** [comment]
Did you try this?

```
class Example extends Component {
  onCapture = uri => {
    console.log("do something with ", uri);
  }
  render() {
    return (
        <ViewShot onCapture={this.onCapture} captureMode="mount">
          <View style={{ flex: 1 }}>
	        <PDFView
	          fadeInDuration={250.0}
	          style={{ flex: 1 }}
	          resource={resources[resourceType]}
	          resourceType={resourceType}
	          onLoad={() => console.log(`PDF rendered from ${resourceType}`);}
	          onError={() => console.log('Cannot render PDF', error)}
	        />
      	  </View>
      </ScrollView>
    );
  }
}
```

**Comment by hannanstd** [comment]
hi
thanks.
yes i tested now again
but only capture the viewable screen. i need to capture all of content.

**Comment by Taym95** [comment]
Okey try this workaround, wrap your PDFView with ScrollView :

class Example extends Component {
  onCapture = uri => {
    console.log("do something with ", uri);
  }
  render() {
    return (
      <ScrollView>
        <ViewShot onCapture={this.onCapture} captureMode="mount">
          <View style={{ flex: 1 }}>
	        <PDFView
	          fadeInDuration={250.0}
	          style={{ flex: 1 }}
	          resource={resources[resourceType]}
	          resourceType={resourceType}
	          onLoad={() => console.log(`PDF rendered from ${resourceType}`);}
	          onError={() => console.log('Cannot render PDF', error)}
	        />
      	  </View>
      </ScrollView>
    );
  }
}

**Comment by hannanstd** [comment]
when i wrap with scrollview the PDFVIEW will be hidden and doest appear. i,m sorry but can you test it personaly in live code?

**Comment by hannanstd** [comment]
hi
is there any solution to get shot from a base64 pdf? also without PDFView.

**Comment by hannanstd** [comment]
is there any way to shot pdfs?

**Comment by gre** [comment]
I think that it's more up to the PDF library to solve this / offer you a way to rasterize the content in a good quality way.

**Comment by wangxy-520** [comment]
Hey, here's how I worked it out. It might help you

class Example extends Component {
  onCapture = uri => {
    console.log("do something with ", uri);
  }
  render() {
    return (
      <ScrollView>
        <ViewShot onCapture={this.onCapture} captureMode="mount">
          <View style={{ flex: 1, width: WidthUtils.screenWidth(), height: pdfPageHeight * this.state.pdfPageCount}}>
	        <PDFView
	          fadeInDuration={250.0}
	          style={{ flex: 1 }}
	          resource={resources[resourceType]}
	          resourceType={resourceType}
	          onLoad={() => console.log(`PDF rendered from ${resourceType}`);}
	          onError={() => console.log('Cannot render PDF', error)}
	        />
      	  </View>
		</ViewShot>
      </ScrollView>
    );
  }
}
