### ISSUE TITLE
Wrong size of image.

### ISSUE THREAD

**Issue by BlackCat1397** [gre/react-native-view-shot#253]
#### Version & Platform

```bash
react-native@0.59.9
react-native-view-shot@3.0.2 
```

**Platform:** iOS

#### Expected behavior
Get image with size specified in options.

#### Actual behavior
Size is multiplied by pixel density.

#### Steps to reproduce the behavior

I have following code:
```javascript
captureRef(viewRef, {
                width: 364,
                height: 200,
                format: 'jpg',
            }).then(uri =>
                Share.share({ url: uri })
            ).catch(err =>
                console.log(err)
            );
```

The resulting image has 1092x600 size. I tried to change height to 100 and achieved the 1092x300 image.

Is it desired behaviour? In this case how should I achieve the image with specified width and height? Don't think that it's good idea to divide sizes by 3.

**Comment by BlackCat1397** [comment]
Debugged a little bit. Looks like the problem is on Apple's side, because UIImage created with the right size 
```lldb
po image.size
(width = 364, height = 100)
```
But the resulting image has 3x pixel density.
Would be great to have it mentioned in the Lib documentation.
<img width="909" alt="Screen Shot 2019-09-09 at 8 37 16 PM" src="https://user-images.githubusercontent.com/13522469/64553396-f481e800-d341-11e9-98d5-28d311a852b8.png">

**Comment by BlackCat1397** [comment]
So I finished with
```javascript
import { PixelRatio } from 'react-native';

const pixelRatio = PixelRatio.get();
captureRef(this.card, {
                format: 'jpg',
                width: 364 / pixelRatio,
                height: 200 / pixelRatio,
            })
```
Works as expected, but looks a bit hacky.

**Comment by hosseinpro** [comment]
I had the same problem and your solution with PixelRatio works perfectly.
Thank you BlackCat1397.

**Comment by gre** [comment]
this is expected and documented. https://github.com/gre/react-native-view-shot#snapshotted-image-does-not-match-my-width-and-height-but-is-twice3-times-bigger
