### ISSUE TITLE
Video conference screenshot.

### ISSUE THREAD

**Issue by ghost** [gre/react-native-view-shot#254]
Hi, 
I try to take screenshot of video conference when conference is going on in my app on android device but getting black screen in screenshot.
Any help will be appreciated.

**Comment by Taym95** [comment]
duplicate #250

**Comment by gre** [comment]
unfortunately it's more the scope of the video library to provide a solution to capture frames. even if you manage to make it work, I think using this library would remain a hack and wouldn't offer a good quality.
