### ISSUE TITLE
android Build error: can't find symbol class IntDef.

### ISSUE THREAD

**Issue by Quantum-35** [gre/react-native-view-shot#257]
### bug report 
Android build fails when you are using react-native-version 0.59.10 with react-native-view-shot version 3.0.2 with error `can't find symbol class IntDef`.

But works well if I downgrade react-native-view-shot to version 2.6.0

**Comment by Taym95** [comment]
Hey, I am just guessing, but `AndroidX is supported in RN 60+` and because this library is using Androidx annotation `IntDef` in `2.6.0+` you have this issue, so you need to upgrade your RN version to 60+ so you can use latest version of this library.

**Comment by gre** [comment]
fixed now.
