### ISSUE TITLE
how to capture entire screen

### ISSUE THREAD

**Issue by daheeahn** [gre/react-native-view-shot#258]
Hi! My component contains both the view and the camera screen (RNCamera). However, when I do 'captureScreen' using view-shot, only the camera's screen is captured and my view is not included in the result. How can I capture the entire screen?

**Comment by gre** [comment]
I'm not sure to understand what you meant by "only the camera's screen is captured".
I think it captures everything except the "system UIs" like the status bar, and i'm not sure we can technically do it in Android/iOS.
