### ISSUE TITLE
Refview question

### ISSUE THREAD

**Issue by Ian999777** [gre/react-native-view-shot#26]
Can anyone give me an example of how to implement the Refview?
I just put view there, and it throws an error 'ExceptionsManager.js:71 Unhandled JS Exception: findNodeHandle(...): Argument is not a component (type: function, keys: displayName,AccessibilityTraits,AccessibilityComponentType,forceTouchAvailable,propTypes)'

Many thanks,
Ian

**Comment by gre** [comment]
here is the example app: https://github.com/gre/react-native-view-shot-example

e.g. https://github.com/gre/react-native-view-shot-example/blob/master/App.js#L36

in `takeSnapshot(ref, options)`,

it's basically a 'normal' [React ref](https://facebook.github.io/react/docs/refs-and-the-dom.html).
