### ISSUE TITLE
Returning URI other than base64, with result: 'base64' option

### ISSUE THREAD

**Issue by TiagoGouvea** [gre/react-native-view-shot#260]
### bug report 

I'm trying the get the base64 result, but it ever return the URI. My code:

``` 
...
import ViewShot from "react-native-view-shot";

class ShareDishViewImage extends Component {
    onImageLoad = () => {
        this.refs.viewShot.capture({ result: 'base64' }).then((data) => {
            console.log("capture base64", data);
        }).catch(e => {
            errorHandler.log(e);
        });
    };

    render () {
        return (
            <ViewShot ref='viewShot' style={Styles.shareDishView.imageView}>
                <View style={Styles.shareDishView.imageContainer}>
                    <Image
                        source={{ uri: this.props.image }}
                        onLoad={this.onImageLoad}
                        resizeMode='cover'
                        style={Styles.shareDishView.image}
                    />
                    <Text>
                        my text
                    </Text>
                </View>
            </ViewShot>
        );
    }
}

```

On ` console.log("capture base64", data)` I got `file:///data/user/0/io.appmasters.lowcarb/cache/ReactNative-snapshot-image2440291982127758274.png`

#### Version & Platform

```bash
lowcarb-mobile@2.4.31 /Users/tiagogouvea/www/lowcarb-app/mobile
├── react-native@0.60.5 
└── react-native-view-shot@3.0.2 
```

**Platform:** Android

#### Expected behavior

Expected that capture method with `result: 'base64'` would return a base64 string other than the file URI.

#### Actual behavior

It returns the file URI other than the desired base 64 content.

**Comment by gre** [comment]
This is expected, if you use a ViewShot, the way to provide the options is via the options props.

```
<ViewShot options={{ result: "base64" }} ...
```


`viewShot.capture()` takes no parameter.

**Comment by Pietro-Putelli** [comment]
```
      <ViewShot
        ref={ref}
        style={containerStyle}
        options={{ result: "base64", format: "png" }}
      >
      </ViewShot>
```

Hi this is what I'm trying but it generates a malformed base64 string, and I knot it because using this tool https://base64.guru/tools/repair it repairs the image and it works in react-native.
Any solution? Thank you
