### ISSUE TITLE
captureRef functionality throws Error: Failed to capture view snapshot

### ISSUE THREAD

**Issue by AMichaelK** [gre/react-native-view-shot#263]
#### Version & Platform

bash-3.2$

"expo": "^34.0.3",
"react": "16.8.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
"react-native-view-shot": "^3.0.2",

**Platform:**
Android

#### Expected behavior
Expected for captureRef to create a screenshot of the view that it is sent

#### Actual behavior
Crashes with error log: [Unhandled promise rejection: Error: Failed to capture view snapshot]

#### Steps to reproduce the behavior
Code used to reproduce the behavior:
```import React from 'react';
import {
  View,
  Text,
} from 'react-native';
import { captureRef as takeSnapshotAsync } from 'react-native-view-shot';

class ScreenshotView extends React.Component {
  pageView = null;

  async componentDidMount() {
    await this.takeSnapshot();
  }

  takeSnapshot = async () => {
    const base64 = await takeSnapshotAsync(this.pageView, {
      format: 'png',
      result: 'base64',
      quality: 0.3,
      snapshotContentContainer: true
    });
    console.log(base64);
  }

  render() {
    return (
      <View
        ref={(component) => { this.pageView = component; }}
        collapsable={false}
      >
        <Text>
          hi
        </Text>
      </View>
    );
  }
}

export default ScreenshotView;
```

**Comment by zhy8023** [comment]
i have same promise

**Comment by tiwus** [comment]
facing same issue

**Comment by gre** [comment]
snapshotContentContainer is normally for ScrollView, I think the problem is coming from this.

Check example project that have many working examples.

this error can also happen when you try to screenshot something that is not handled by this library (e.g. a blackbox component like GL or video,..). If it's the case, please create a new issue with more detail. thanks.

**Comment by BKudale** [comment]
Facing same issue 
My Code,
<ViewShot
                style={{ flex: null }}
                ref={ref => {
                  this.viewShot = ref;
                }}
                options={{ format: 'jpg', quality: 1.0 }}
              >
                <ImageBackground
                  ref={image => (this.imageComponent = image)}
                  source={imageSource}
                  // resizeMode="contain"
                  style={[styles.attachment, this.props.imageStyle, { height: screenHeight - 64 - 80 }]}
                >
                  {showSticker && this._isMounted && (
                    <Animated.View
                      {...this.panResponder.panHandlers}
                      style={[this.state.pan.getLayout()]}
                    >
                      <TouchableOpacity onPress={() => { this.onPressCloseSticker() }}>
                        <Text>
                          Close
                    </Text>
                      </TouchableOpacity>
                      <Image
                        style={{ width: this.props.stickerSize, height: this.props.stickerSize }}
                        source={sticker}
                      />
                    </Animated.View>
                  )}
                </ImageBackground>
              </ViewShot>

**Comment by Seamus1989** [comment]
still an issue +1

**Comment by Adeel984** [comment]
+1

**Comment by deniska69** [comment]
Hi! I am facing the same problem
This helped me: [https://github.com/gre/react-native-view-shot/issues/489#issuecomment-1704034862](https://github.com/gre/react-native-view-shot/issues/489#issuecomment-1704034862)

**Comment by Agustin-Perezz** [comment]
> Hi! I am facing the same problem This helped me: [#489 (comment)](https://github.com/gre/react-native-view-shot/issues/489#issuecomment-1704034862)

this also solves my problem

**Comment by Demianeen** [comment]
> > Hi! I am facing the same problem This helped me: [#489 (comment)](https://github.com/gre/react-native-view-shot/issues/489#issuecomment-1704034862)
> 
> this also solves my problem, thanks

Thanks, worked for me! Had this error with the Expo tutorial

**Comment by JLany** [comment]
I have the same issue, I am using an Android Redmi to develop my application. 
No solution worked for me, I tried the collapsable, and ViewShot, nothing works till now. 

Any updates?

**Comment by JLany** [comment]
> Hi! I am facing the same problem This helped me: [#489 (comment)](https://github.com/gre/react-native-view-shot/issues/489#issuecomment-1704034862)

It works for me on the web, not on my Android device. Did work for you on Android?
