### ISSUE TITLE
Capture full screen with only 1 view

### ISSUE THREAD

**Issue by dericeira** [gre/react-native-view-shot#264]
Hi.I need to capture the device screen but only one view. 

Example: I have one text in center of screen, and I need to capture all the bounds (transparent).

**Comment by gre** [comment]
`react-native-view-shot` scope is to snapshot a native view.

if you want to capture something that is not to be visible from the user,
what you can do is render in an hidden space (like you can position absolute offset out of the visible boundaries of the app) and snapshot that space.
