### ISSUE TITLE
Long view (800 × 8235 pixels) fails to get captured

### ISSUE THREAD

**Issue by jefflewis** [gre/react-native-view-shot#268]
### bug report 

When capturing a view that gets rendered as 800 × 8235 pixels fails to get converted into a UIImage with the view's content. It's a blank alpha image.

#### Version & Platform

```bash
npm ls react-native react-native-view-shot └── react-native-view-shot@3.0.0
```

**Platform:** iOS? Android?
iOS

#### Expected behavior
UIImage with content

#### Actual behavior
UIImage of correct size, but empty content.

#### Steps to reproduce the behavior

I tried to build the example project but it failed to compile. Adding a _really_ long view to it should show the failure though.

**Comment by gre** [comment]
let's keep the disucssion in https://github.com/gre/react-native-view-shot/issues/154 :)
