### ISSUE TITLE
Error: The content size must not be zero or negative. Got: (736, 0)

### ISSUE THREAD

**Issue by ppv94** [gre/react-native-view-shot#270]
I am not able to take a screen shot in react-native application i am getting  **Error: The content size must not be zero or negative. Got: (736, 0)**
#### Version & Platform
I am using react-native-view-shot version 3.0.2 and react-native version 0.61.4 
 i am using 
`  this.refs.viewShot.capture().then(uri => {
          alert(JSON.stringify(uri))
        })`

How can i solve this issue

**Comment by gre** [comment]
I think this is documented in https://github.com/gre/react-native-view-shot#getting-the-content-size-must-not-be-zero-or-negative
