### ISSUE TITLE
capture() ignores large qrcode images

### ISSUE THREAD

**Issue by vivek2910** [gre/react-native-view-shot#272]
When capturing, if the view consists of a qr code that is generated by QRCODE package and if the size of qr is large for ex-200, then view shot ignores the qr in captured image

**Comment by gre** [comment]
@vivek2910 thanks for the issue.
Please provide a snippet of code to help reproducing the issue. Thanks.

**Comment by gre** [comment]
I will suspect it's related to inherent limitation of iOS/Android max bitmap sizes. I would suggest to ask the QR code library to provide you a way to generate the image as a file instead of using this library.
