### ISSUE TITLE
ViewShot with RTCView

### ISSUE THREAD

**Issue by johndm76** [gre/react-native-view-shot#276]
Hi
I'm trying to use a ViewShot with an RTCView (on Android) like below, but nothing appears in the resultant snapshot except a black image:
...
<ViewShot ref={ref => this.vs = ref} options={{ format: 'jpg', quality: 0.9 }}><RTCView zOrder={1} style={{ width: 300, height: 300, backgroundColor: '#808080' }} collapsable={false} streamURL={stream.toURL()} /></ViewShot>
...
Could you please help.
Thank you

**Comment by johndm76** [comment]
Please any help

**Comment by gre** [comment]
similarly to https://github.com/gre/react-native-view-shot/issues/201#issuecomment-520125912 I consider this is out of scope of this library and it's for react-native-webrtc to offer a way to capture image frames.

**Comment by K12AZ** [comment]
@johndm76  did you found any solution for this?

**Comment by rxmoein** [comment]
Any solution?
