### ISSUE TITLE
How can I capture WebView content?

### ISSUE THREAD

**Issue by xclidongbo** [gre/react-native-view-shot#278]
#### Version & Platform

```bash
npm ls react-native react-native-view-shot #<- PASTE CMD RESULT IN HERE
```
$ npm ls react-native-view-shot
WorkbenchApp@3.0.1 /Users/lidongbo/WorkBentch/ReactNative/sinosig/workbench-app
└── react-native-view-shot@2.6.0

   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New minor version of npm available! 6.11.3 → 6.13.4       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.4   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

**Platform:** iOS

**Comment by gre** [comment]
https://github.com/gre/react-native-view-shot/blob/master/example/src/WebView.js is an example that prove capturing webview works


<img width="535" alt="Capture d’écran 2020-01-19 à 12 52 36" src="https://user-images.githubusercontent.com/211411/72680478-9668cc80-3aba-11ea-9821-b80617dfa6f2.png">

**Comment by maxrisk** [comment]
Can I snapshot a whole web page?

**Comment by gre** [comment]
I don't think so. unless you make your WebView having the height of the page you are capturing.

**Comment by maxrisk** [comment]
> I don't think so. unless you make your WebView having the height of the page you are capturing.

So this component can only capture one screen, right?

**Comment by gre** [comment]
@maxrisk `captureRef` captures a view by its ref and `captureScreen` captures the full viewport ("screen") of the app.

**Comment by sriteja777** [comment]
@gre I am using a WebView, but when I capture the ref of WebView, only the part that is visible on the screen is captured, is it possible to capture whole web page?

**Comment by TalhaAbid1** [comment]
@gre I can't see Any Code  **To Capture WebView** 
Your Given Link Isn't Opening  
> Please Assist me With CODE

**Comment by DanDayne** [comment]
@TalhaAbid1 This code captures only the currently visible content of the webview instead of the whole page. How do we capture the entire page?
```
import React, {useState, useCallback, useRef} from 'react';
import {Button, View} from 'react-native';
import ViewShot from 'react-native-view-shot';
import WebView from 'react-native-webview';
import {createAssetAsync, usePermissions} from "expo-media-library";

const WebViewExample = () => {
    const [source, setSource] = useState(null);
    const [status, requestPermission] = usePermissions();

    const dimension = { width: "100%", height: "100%"};

    let viewShotRef = useRef<ViewShot>()

    const onCapture = useCallback(uri => setSource({ uri }), []);

    const takeScreenshot = () => {
        viewShotRef.current.capture().then(
            async uri => {
                console.log(uri)

                if (status.accessPrivileges !== 'all') {
                    await requestPermission();
                }
                await createAssetAsync(uri);
            }
        )
    }

    return (
        <View style={{ marginTop: 40, flex: 1, display: 'flex' }}>
            <Button onPress={takeScreenshot} title="Take Screenshot"/>
            <ViewShot
                ref={viewShotRef}
                onCapture={onCapture}
                style={dimension}
            >
                <WebView
                    source={{
                        uri: 'https://github.com/gre/react-native-view-shot/issues/278',
                    }}
                    style={{ position: 'relative' }}
                    bounces={false}
                />
            </ViewShot>
        </View>
    );
};

WebViewExample.navigationOptions = {
    title: 'react-native-webview',
};

export default WebViewExample;
```

**Comment by bryanltobing** [comment]
is capturing the whole page of the webview still not possible?

**Comment by GitKat** [comment]
> is capturing the whole page of the webview still not possible?
This is a view capture. If you want the whole page of webview, give it full height and width
