### ISSUE TITLE
Base64 generated cannot be decoded by window.atob in iOS

### ISSUE THREAD

**Issue by yannickmodahgouez** [gre/react-native-view-shot#279]
## Version & Platform

```bash
react-native@0.59.10
react-native-view-shot@2.6.0 
```

**Platform:** iOS 13.1

#### Expected behavior

```
 captureRef( this.scanArea , {
            format: 'jpg',
            result: 'base64',
          }).then(data => {
var binary_string = window.atob(base64); 
}
```
Should not throw and exception

#### Actual behavior

Code above throws an exception when run in a production release. Strangely it doesn't in a debug release.

the reason for this exception is that window.atob doesnt accept line endings inserted into the base64 string by the following code 
https://github.com/gre/react-native-view-shot/blob/ad9a536b898fc9a40b39f72c51ea0f6fd51b7894/ios/RNViewShot.m#L146

My proposed fix is to remove the NSDataBase64Encoding64CharacterLineLength option since default behaviour of base64EncodedStringWithOptions is to *not* add line endings.

**Comment by yannickmodahgouez** [comment]
kinda jumped the gun on this one. Culprit are not line endings but this : https://stackoverflow.com/questions/42829838/react-native-atob-btoa-not-working-without-remote-js-debugging

however, not sure why line endings are added to the base64 encoding. Is there a reason ?

**Comment by gre** [comment]
I'm a bit confused by this ticket because `window.atob` does not exist in React Native.

The equivalent I know is to do `Buffer.from(str, "base64")` and it seems to work:

https://github.com/gre/react-native-view-shot/commit/a2a41e3d5429a59f0168844cf3a31eb4c174258d

```
2020-01-19 15:51:15.755 [info][tid:com.facebook.react.JavaScript] buffer of length 2070612
```
