### ISSUE TITLE
Upon linking the dependency my app won't launch.

### ISSUE THREAD

**Issue by KaeganClark** [gre/react-native-view-shot#280]
#### Bug Report
When I install the module through npm and try to use it I get the following error:
   "Error: react-native-view-shot: NativeModules.RNViewShot is undefined. Make sure the 
   library is linked on the native side."
Which I would expect. 
After linking the module my app will no longer debug and I get like 20 of these errors:
   > Task :react-native-view-shot:compileDebugJavaWithJavac FAILED
   /Users/kaeganclark/keli/attendance/node_modules/react-native-view- 
   shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:11: error: cannot find 
   symbol
   import androidx.annotation.IntDef;
                          ^
  symbol:   class IntDef
  location: package androidx.annotation
   /Users/kaeganclark/keli/attendance/node_modules/react-native-view- 
   shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:12: error: cannot find 
   symbol
   import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
  /Users/kaeganclark/keli/attendance/node_modules/react-native-view- 
  shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:13: error: cannot find 
  symbol
  import androidx.annotation.StringDef;
                          ^
  symbol:   class StringDef

and I'm at a loss.

#### Version & Platform
attendance@0.1.44 /Users/kaeganclark/keli/attendance
├── react-native@0.59.10 
└── react-native-view-shot@3.0.2

Android

#### Expected behavior
For my app to let me debug.
#### Actual behavior
App won't launch and errors out.

**Comment by gre** [comment]
https://github.com/react-native-community/discussions-and-proposals/issues/129

I think that might mean this lib is not compatible with RN <=0.59 anymore

**Comment by gre** [comment]
Please try with the 2.6.0 of this library
We bumped a major for reactnative 0.60
If confirmed I'll add in documentation

**Comment by KaeganClark** [comment]
The earlier version worked for me. Thanks for the response!

**Comment by MotikDev** [comment]
I encountered the same issue with React Native 0.73.6, so I downgraded to version 3.8.0.
