### ISSUE TITLE
CaptureScreen() failing.

### ISSUE THREAD

**Issue by KaeganClark** [gre/react-native-view-shot#281]
Bug report
I am using captureScreen like so:
```
captureScreen({
        format: "jpg",
        quality: 0.8
      }).then(
        uri => console.log(uri),
        error => console.error("Oops, snapshot failed", error)
      );
```
It worked the first few times I used it and now I keep getting this error:
```
"Error: Failed to capture view snapshot\n    at createErrorFromErrorData (/Users/kaeganclark/keli/attendance/.vscode/.react/index.android.bundle:2106:17)\n    at /Users/kaeganclark/keli/attendance/.vscode/.react/index.android.bundle:2058:27\n    at MessageQueue.__invokeCallback (/Users/kaeganclark/keli/attendance/.vscode/.react/index.android.bundle:2629:18)\n    at /Users/kaeganclark/keli/attendance/.vscode/.react/index.android.bundle:2360:18\n    at MessageQueue.__guard (/Users/kaeganclark/keli/attendance/.vscode/.react/index.android.bundle:2533:13)\n    at MessageQueue.invokeCallbackAndReturnFlushedQueue (/Users/kaeganclark/keli/attendance/.vscode/.react/index.android.bundle:2359:14)\n    at /Users/kaeganclark/keli/attendance/.vscode/.react/debuggerWorker.js:200:58\n    at process.<anonymous> (/Users/kaeganclark/keli/attendance/.vscode/.react/debuggerWorker.js:68:9)\n    at process.emit (events.js:203:13)\n    at emit (internal/child_process.js:876:12)"
```
Version & Platform
```bash
├── react-native@0.59.10 
└── react-native-view-shot@2.6.0 
```
Android

Expected behavior
Take a screenShot.

Actual behavior
Error and fail to screenShot.

Help is greatly appreciated!

**Comment by abdulbasit1248** [comment]
Same Issue.Please sort it out if someone

**Comment by abdulbasit1248** [comment]
For android the stable package is 2.5.0 please install this one.Then
in MainApplication.Java you have to import like this 
[](https://github.com/gre/react-native-view-shot/issues/106#issuecomment-399658331)

**Comment by KaeganClark** [comment]
> For android the stable package is 2.5.0 please install this one.Then
> in MainApplication.Java you have to import like this
> [Click here](https://github.com/gre/react-native-view-shot/issues/106#issuecomment-399658331)

@abdulbasit1248 
Steps I followed:
1. Deleted node_modules and package_lock.json
2. Changed version to 2.5.0 in package.json
3. Npm install
4. Link the dependency as outlined in link.

Same error.

**Comment by tiwus** [comment]
facing same issue in real device

**Comment by KaeganClark** [comment]
@abdulbasit1248  
I have found that if the react native camera is authorized then the captureScreen() fails but if it is unauthorized the screenshot works. Ideas?

**Comment by KaeganClark** [comment]
I solved this by removing this for loop ```for (final View child : childrenList) {} ``` from viewshot.java.
