### ISSUE TITLE
Build fail after updating to 3.1.1

### ISSUE THREAD

**Issue by panda0603** [gre/react-native-view-shot#284]
After updating to version 3.1.1 from 3.0.2, I get build error on android. IOS works fine. 

```
* Where:
Build file '.../node_modules/react-native-view-shot/android/build.gradle' line: 50

A problem occurred evaluating project ':react-native-view-shot'.
> Cannot get property 'reactNative' on extra properties extension as it does not exist

```
#### Version & Platform

```bash
├── react-native@0.61.5 
└── react-native-view-shot@3.1.1 
```

**Platform:** iOS? Android?
Android

Tried uninstalling and reinstall, same problem

**Comment by nicolasifce** [comment]
I have the same problem

**Comment by kraison1** [comment]
I use the method 
 - roofolder/node_modules/ react-native-view-shot/android
- Edit file build.gradle 
- tag dependencies change  api "com.facebook.react:react-native:${rootProject.ext.reactNative}" to     api 'com.facebook.react:react-native:+'
