### ISSUE TITLE
Help-- Is This like taking a screenshot?

### ISSUE THREAD

**Issue by CWilsonTSP** [gre/react-native-view-shot#287]
### feature request/Help Wanted
Sorry if this is the wrong thing to ask. I was under the impression when I read about this that it is creating an image of the view/component rather than taking a screenshot.

Does this actually capture the view itself or does it act like taking a screen shot?
I have a working example and there is a bunch of white space on the right side of the image, presumably because the view takes up the entire width. Is there a way to prevent this? 
<img width="375" alt="TJHM1155" src="https://user-images.githubusercontent.com/55925610/73097953-5e94c700-3eb6-11ea-9c86-2fc4f6489b1f.PNG">

**Comment by gre** [comment]
This library is rasterizing a view. In other words, it's taking the pixels of a view and making it an image.

If you have a padding in a view, it will capture this padding as well, so this needs to be fixed in your side to make the view having the proper style conditions to get the dimension fixed.
