### ISSUE TITLE
captureRef to shot the screen frequently , releaseCapture does not work 

### ISSUE THREAD

**Issue by lvshaoping007** [gre/react-native-view-shot#290]
### feature request

"react-native-view-shot": "^2.4.0",

### bug report 
i use captureRef to shot the screen frequently，but it always saved the same picture(the first one )  so i want to free the shot when shared . then i use releaseCapture(data) to free .but it did not work , can you tell me how to free the shot ?  there is my code 
thank you very much 

`captureRef(this.refs.viewShot, {
      quality: 1,
      result: "data-uri",
    })
      .then(data => {
        let shareImageBase64 = {
          url: data
        };
        Share.open(shareImageBase64).then((res) => {
          releaseCapture(data)
        }).catch((err)=>{
          console.log(err)
        });
      })`

**Comment by tuantvk** [comment]
same issues
i use "react-native-view-shot": "^3.1.2"

**Comment by gre** [comment]
I do not understand the issue raised here. if you use a data-uri there are nothing to "release", it's not saved on disk.
