### ISSUE TITLE
It is possible to view shot into PDF format ?

### ISSUE THREAD

**Issue by saczuac** [gre/react-native-view-shot#296]
### PDF FORMAT

View shot on pdf format ? or how can I convert this png to a pdf and download it ?

**Comment by agarwalamn** [comment]
Any solution to this?

**Comment by MJahanzaibKhan** [comment]
any solution to this?

**Comment by gre** [comment]
I'm a bit confused by the usecase here. you want the view to be captured as a PDF, not a "rasterized" image into a PDF? i think it's beyond the scope of this library, someone would need to make a 'react native pdf"
