### ISSUE TITLE
react-native@0.62.x is not supported

### ISSUE THREAD

**Issue by oleksandr-dziuban** [gre/react-native-view-shot#297]
### feature request

Please add support for react-native v0.62+, because currently application is crashed when using react-native-view-shot library. With react-native v0.61.5 it works perfectly.

#### Version & Platform

```bash
react-native@0.62 or higher
react-native-view-shot@3.0.2 or higher
```

**Platform:** iOS, Android

#### Expected behavior
Application is not crashed when use react-native-view-shot library on react-native v0.62+.

#### Actual behavior
Application is crashing when use react-native-view-shot library on react-native v0.62+.

**Comment by othiagobruno** [comment]
I also need help with that

**Comment by oleksandr-dziuban** [comment]
Is this library still maintained? Looks like no...

**Comment by oleksandr-dziuban** [comment]
@gre @brunowbbs Hello, could you please check the RN 0.62.+ support here?

**Comment by myklosbotond** [comment]
@oleksandr-dziuban, did you check if the crash comes specifically from this library? I upgraded today to `react-native@0.62.2` and I'm using `react-native-view-shot@3.1.2` and it worked fine for me.

**Comment by eltomali** [comment]
Same for me. I have RN v0.62.2 and the app crashes due to react-native-view-shot@3.1.2. 
1. It doesn't work after pod install
2. It doesn't work after manual configuration based on manual linking as suggested and as recommended to look at React Native doc https://reactnative.dev/docs/linking-libraries-ios.html 
3. Also tried fixing warnings on Xcode but failed.

**Comment by myklosbotond** [comment]
Hi, @eltomali 

I'm just curios, what error logs do you get that link the problem to this library?

**Comment by eltomali** [comment]
> Hi, @eltomali
> 
> I'm just curios, what error logs do you get that link the problem to this library?

Hi, 
Thanks for your response. Got it to Work just now in this last trial. Yess!
So here is what I did now after git reseting to the previous working commit:   

1. Install the package and pod install. 
- yard add react-native-view-shot
- cd ios && pod install && cd ..
2. Added my relevant view shot code in my project, saved and closed the apps and restarted the build: 
- npx react-native run-android   
- npx react-native run-ios
And it works now !!
3. Reg iOS, in Xcode I get the following warnings just for info: 
![Screenshot 2020-05-20 at 15 52 38](https://user-images.githubusercontent.com/23627669/82455003-be8d2a00-9ab2-11ea-9ef1-2056c18fd47f.png)

**Comment by myklosbotond** [comment]
Glad it works

**Comment by oleksandr-dziuban** [comment]
@myklosbotond Hi, yes, I will rerun 0.62.2 branch and prepare cash log from xcode

**Comment by othiagobruno** [comment]
it seems that I discovered the problem, was using with flex: 1 on all children.

React-native-view-shot does not allow to use flex: 1, therefore, or error. I removed all flex: 1 and it worked

**Comment by oleksandr-dziuban** [comment]
@othiagobruno and what is the alternative for flex: 1?

**Comment by oleksandr-dziuban** [comment]
Sorry, this issue is closed, as I found the reason: crash occurs because of react-native-share library
