### ISSUE TITLE
canvas in the WebView is no work in this plug-in

### ISSUE THREAD

**Issue by jianglove7** [gre/react-native-view-shot#298]
the same as title

**Comment by jianglove7** [comment]
i use echart svg

**Comment by Rishabh-Streak** [comment]
I am also facing a similar issue .. I have a chart formed in canvas inside a webview and I am not able to capture screenShot for it.

**Comment by Lunziyuan** [comment]
same question. native-echart

It works normally on IOS, but not on Android

**Comment by Lunziyuan** [comment]
same with the https://github.com/gre/react-native-view-shot/issues/53
if i set android:hardwareAccelerated="false", it works

**Comment by Manju-lab** [comment]
any update on this?
