### ISSUE TITLE
[feature-request] Please enhance this to support react-native-video on android

### ISSUE THREAD

**Issue by pavankumarkl** [gre/react-native-view-shot#302]
Currently react-native-view-shot does not support react-native-video

I have to capture screenshot when a video is played using react-native-video on android but it is not possible with view-shot library, can you suggest any other library if it exists or give few suggestions to do the same.

**Comment by gre** [comment]
Capturing a `<Video` works as shown in the examples 
<img width="286" alt="Screenshot 2022-05-28 at 11 33 13" src="https://user-images.githubusercontent.com/211411/170821475-a8a070f3-62dc-4886-920a-000e984934b0.png">

but it's a bit limited and probably not the best way to do it. I think this is more a feature request for react-native-video and if it's out of their scope, maybe there is a need for a video utility library.

Thanks
