### ISSUE TITLE
Render off screen area

### ISSUE THREAD

**Issue by timLoewel** [gre/react-native-view-shot#31]
Hi,

is it possible to capture a whole View, even the parts that are not yet on screen (like in a scrollview)?
Or even better: capture a View that has not yet been given to the render method?
e.g. 

```	
createView(){ 
		return <View>
			<Text>Hello World</Text>
		</View>
	}
...
RNViewShot.takeSnapshot(this.createView(), {
					 format: 'png',
					result: 'file',
					 });
```

Is this planned, and would this at all be possible with the current architecture? 
Best, Tim

**Comment by gre** [comment]
you can "render off-screen" by rendering it in a View that is not displayed or absolute "out of the screen".
It's a bit hacky but i've been using it in prod.

just a quick example:
```
class Stuff extends Component {
  snapIt() { return RNViewShot.takeSnapshot(this.refs.root, {...}) }
  render () {
    return <View ref="root">...</View>;
  }
}
class MyApp extends Component {
  doIt = () => { this.refs.stuff.snapIt().then(...) }
  render () {
    return <View>
      <View style={{ position: "absolute", left: 1000 }}>
        <Stuff ref="stuff" />
      </View>
      .. your contnet..
      <Button onPress={this.doIt} label="RENDER IT!" />
    </View>
  }
}
```

**Comment by timLoewel** [comment]
Cool, This Works. Thanks a lot.

**Comment by tza17313** [comment]
@gre   Have you ever encountered a view outside the Image will have a certain probability can not be captured; I am sure this picture has been loaded . if I set the `left` to 0, the Image ca be captured.

> 你有没有遇到过视图外的 Image 会有一定几率无法截到；我确定图片已经加载好了，如果我把绝对定位的left值改为0，就不会出现Image 无法截到的情况。

**Comment by hugoh59** [comment]
Do you have an exemple for a functional component?
