### ISSUE TITLE
console.error:'Oops, snapshot failed', { framesToPop: 1, code: 'E_UNABLE_TO_SNAPSHOT' }

### ISSUE THREAD

**Issue by taolu-youxun** [gre/react-native-view-shot#312]
#### Version & Platform
react-native@0.57.8
react-native-view-shot@2.0.6
**Platform:**  Android

`<ScrollView
          contentInsetAdjustmentBehavior="automatic"
          ref={this.ref}
          style={{ flex: 1, backgroundColor: 'red' }}
        >
          <View
            collapsable={false}
            ref={this.abc}
            style={{ flex: 1, backgroundColor: 'red' }}
          >
             <Text> Hello View Snap Shot </Text> 
          </View
    </ScrollView>`

#### Actual behavior
![11595941858_ pic](https://user-images.githubusercontent.com/23043908/88670429-a15e8280-d117-11ea-91f0-48b1f8f9f575.jpg)
>

**Comment by taolu-youxun** [comment]
Using  'View'  screenshot, Android side reports an error

**Comment by taolu-youxun** [comment]
I know the problem

**Comment by tkud04** [comment]
This fixed it for me: https://github.com/gre/react-native-view-shot/issues/555#issue-2792705792
