### ISSUE TITLE
Can the generated uri not be uploaded to the server?

### ISSUE THREAD

**Issue by showtan001** [gre/react-native-view-shot#314]
#### Version & Platform

**Platform:** iOS? Android?

 iOS and Android

#### Steps to reproduce the behavior

Can the generated uri not be uploaded to the server.

uri:
file:///Users/mac/Library/Developer/CoreSimulator/Devices/49F925E7-AC38-4CF5-B9C5-87F59420162E/data/Containers/Data/Application/A4E23377-6818-48D4-A23B-20FAA5814412/tmp/ReactNative/A4FDB610-B242-4359-A9BE-002353C2B17C.jpg.

How can I make the uri upload to the server, just like react-native-image-crop-picker.

**Comment by gre** [comment]
This is a feature beyond the scope of this library. it's possible to upload images with other library, or actually directly with React Native.
https://www.reactnativeschool.com/how-to-upload-images-from-react-native
