### ISSUE TITLE
Getting errors with 1.6.0 after upgrading to RN 0.40 🙏 😢

### ISSUE THREAD

**Issue by Eyesonly88** [gre/react-native-view-shot#32]
So I upgraded to RN 0.40 and everything broke. So now I'm trying to go through each library I used and hopefully get it working again.

I upgraded to 1.6.0 and can't get the project to build, with errors like:
![image](https://cloud.githubusercontent.com/assets/767013/22283744/c2a7525c-e348-11e6-95b0-3a7b6b82a15a.png)

```
/MY_APP_LOCATION/node_modules/react-native-view-shot/ios/RNViewShot.m:31:16: Property 'uiManager' cannot be found in forward class object 'RCTBridge'
```
I `npm install` the 1.6.0 and `react-native unlink react-native-view-shot`ed then `react-native link react-native-view-shot`ed and cleaned project in xCode but still not compiling. One of the errors is coming from this library as shown in the image above.

Any ideas on how to fix this please 🙏?

**Comment by gre** [comment]
are you sure about this bug? I can run https://github.com/gre/react-native-view-shot-example fine on RN 0.40 and RNVS 1.6.0

**Comment by gre** [comment]
sorry i'm actually on 0.41.2 to be more precise, but it should be fine on 0.40.0 too (i tested a few weeks ago)
