### ISSUE TITLE
Animations are frozen on View.Animated with PanResponder

### ISSUE THREAD

**Issue by pythys** [gre/react-native-view-shot#321]
### bug report

Animations are disabled when my `<View>` is surrounded by `<ViewShot>...</ViewShot>`. This happens when I have an sub-views that are of type `Animated.View` and I use a `PanResponder` to handle user clicks

#### Version & Platform

```
3.1.2 on Android
```

#### Expected behavior

Animation should work fine and ViewShot should not disable animations.

#### Actual behavior

Animations freeze and I cannot click or move things about.

#### Steps to reproduce the behavior

- Create a view
- Inside that view create an animated view
- Assign a PanResponder to the animated view to allow for having interactive animation (e.g. move)
- Surround the outer view with `<ViewShot>`
- Observe the freeze

**Comment by sataporn8063** [comment]
me too animation loading is freeze on android while viewShot.capture() is working
any solution or workaround ?

**Comment by pythys** [comment]
I think the problem revolves around PanResponder. My solution was a bit of a hack:

1. Save the state of animation
2. Make the introduction of Viewshot programmatic and conditional (like tapping a button for example)
3. On certain event add the viewshot component using the saved state to keep everything where it was

**Comment by deCodeIt** [comment]
Can't we put the capture to background thread rather than main UI thread?

**Comment by gre** [comment]
it is better not to use `<ViewShot>` in that case but directly the imperative API. using a ref.
