### ISSUE TITLE
Is there a way to ignore a specific component

### ISSUE THREAD

**Issue by Ich-bin-naoya** [gre/react-native-view-shot#331]
I want to ignore some component from  capturing 
like ignoring  a ShareBtn comoponent

```jsx
      <ScrollView  collapsable={false}>
          <ViewShot onCapture={this.onCapture} captureMode="mount" options={{ format: "jpg", quality: 0.9}}>
              <View style={{ width: width,padding:5}}>
                  <Text>Title</Text> 
                  <ShareBtn>  <- I wont this component to be not on the image
             </View>
        </ViewShot>
     </ScrollView>

```

If someone have solutions let me know please!

**Comment by gre** [comment]
The only way is to render that without them 🤔
A trick is you could use a copy of that rendering in a hidden frame the user wouldn't see (eg position offset it outside of the screen)

**Comment by Ich-bin-naoya** [comment]
> The only way is to render that without them 🤔
> A trick is you could use a copy of that rendering in a hidden frame the user wouldn't see (eg position offset it outside of the screen)

Thank you!!

**Comment by Dastnbek** [comment]
Just move your share button outside of viewshot components
