### ISSUE TITLE
[feature request] Allow ability to capture screen as a video

### ISSUE THREAD

**Issue by ronneldavis** [gre/react-native-view-shot#335]
### feature request
It would be super useful to be able to capture the contents of the screen as a video, even if there's a limit of 5-10 seconds

**Comment by rohit-ganapathy** [comment]
hey ronnel what is the usecase for which you're building this?

**Comment by ronneldavis** [comment]
I have a ride tracking app for cyclists, and had a share feature that would show your path on a map. It currently shares it as an image but wanted to show an animated path on the map.

**Comment by rohit-ganapathy** [comment]
interesting were you able to achieve it finally?

**Comment by rohit-ganapathy** [comment]
the only problem i see is the wait time for this. You could take multiple screenshots and stitch the images together using FFMPEG to create a video

**Comment by riku99** [comment]
I want this feature too!

**Comment by gre** [comment]
I am afraid this is asking for another library. This would need something available at the OS level too.
Here we are only focusing on capturing a snapshot of a view which is already hard to solve for all the usecases there are. We'll focus on this scope for now 🙏 .
