### ISSUE TITLE
Change name of default uri

### ISSUE THREAD

**Issue by RomainJunca** [gre/react-native-view-shot#336]
Hello !  This is not really an issue but is it possible, when using "await captureRef()", to change the default name ?

I am storing it in a "uri" variable to be then used with react-native-share, but the default name is always something like this "D7CB8F0B-71E6-451A-9D56-C7D147537632.png", how can it be changed ?

Thank you !

**Comment by lame-dev** [comment]
This answer helped me achieve that:

https://github.com/gre/react-native-view-shot/issues/116#issuecomment-458048092

**Comment by Victorcassiano** [comment]
Also wanting to know how I do

**Comment by gre** [comment]
was included in https://github.com/gre/react-native-view-shot/releases/tag/v3.3.0
