### ISSUE TITLE
React Native View Shot not capturing video of live stream on ios

### ISSUE THREAD

**Issue by ruowyong** [gre/react-native-view-shot#337]
Hi all, in interoperability it states RN video is not compatible with react native video, but I was able to capture screenshots of RN video livestreaming with android.

Is React Native video shot not able to capture screenshots of a video being livestreamed on both devices? 

https://stackoverflow.com/questions/66045012/react-native-view-shot-not-capturing-video-of-live-stream-on-ios

**Comment by gre** [comment]
This library can't be used to capture a video. only image snapshots. capturing a View from react-native-video is supported on both iOS and Android according to our example.
