### ISSUE TITLE
use with scrollview,can not  capture without screen

### ISSUE THREAD

**Issue by manweill** [gre/react-native-view-shot#34]
use with scrollview,can not  capture without screen

**Comment by gre** [comment]
Hi,

have you try to just snapshot the webview, does it render anything? maybe it's another bug. some advanced elements like Video, or GLView is likely to render black/transparent and i'm not sure if it's easily fixable..

**Comment by gre** [comment]
I mean, independently from capturing from inside a ScrollView?

I guess it does not matter, it's likely you can't snapshot WebView (but i don't have experience on this, maybe you still can!?).
it might be a security issue?
imagine, i can just display someone's Gmail and snapshot its content? (not sure if cookies are inherited implicitely from safari though?)

**Comment by gre** [comment]
maybe it's possible, but not easily. People seems to have to implement their own WebView and implement the onDraw method? mmh not sure how we can solve that without having to do that.

**Comment by manweil** [comment]
WebView content is a canvas, and i test just snapshot WebView, does it just render background ;

**Comment by gre** [comment]
closing in favor of https://github.com/gre/react-native-view-shot/issues/40
