### ISSUE TITLE
Android Build Fail on React Native 0.63.4

### ISSUE THREAD

**Issue by muhammedjailam** [gre/react-native-view-shot#340]
I m using the following conf 

"react-native": "0.63.4",
"react-native-view-shot": "^3.1.2",

Upon executing npx react-native run-android I get the following build errors

> Task :app:mergeDexDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
310 actionable tasks: 24 executed, 286 up-to-date
Note: C:\react-native\loama\node_modules\react-native-view-shot\android\src\main\java\fr\greweb\reactnativeviewshot\RNViewShotModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D8: Cannot fit requested classes in a single dex file (# fields: 69296 > 65536)
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
     The number of method references in a .dex file cannot exceed 64K.
     Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
    
Steps to Reproduce
---------------------------
Install react native 0.63.4
Install the latest version of react-native-view-shot
Run npx react-native run-android

**Comment by marvin-rao** [comment]
Did you manage do solve this issue?

**Comment by gre** [comment]
The build issues should have been fixed by https://github.com/gre/react-native-view-shot/releases/tag/v3.3.0
