### ISSUE TITLE
Screenshot the other apps in mobile while in background mode

### ISSUE THREAD

**Issue by sankar2389** [gre/react-native-view-shot#348]
### feature request

**Platform:** iOS & Android

#### Steps to reproduce the behavior
```
const veryIntensiveTask = async taskDataArguments => {
  console.log('running veryIntensiveTask.....');
  const {delay} = taskDataArguments;
  await new Promise(async resolve => {
    for (let i = 0; BackgroundService.isRunning(); i++) {
      console.log(i);
      captureScreen({
        format: 'jpg',
        quality: 0.8,
      }).then(
        uri => console.log('Image saved to', uri),
        error => console.error('Oops, snapshot failed', error),
        //await CameraRoll.saveToCameraRoll(uri, 'photo'),
      );
      await sleep(delay);
    }
  });
};
```

**Comment by Derek851029** [comment]
@sankar2389 Did you solve this problem please?

**Comment by sankar2389** [comment]
@Derek851029 you need to work on Native Android side to make this work,

use [Media Projection](https://developer.android.com/reference/android/media/projection/MediaProjection)

**Comment by albert17** [comment]
@sankar2389 Were you able to successfully use Media Projection from React Native?

**Comment by sankar2389** [comment]
Yes, Media Projection from React Native solves the problem.

**Comment by albert17** [comment]
Thanks @sankar2389. Do you have any example or reference?

**Comment by sankar2389** [comment]
https://github.com/sankar2389/ScreenshotNative-Media-Projection

Include this native android project into your react native. For iOS I don't have any samples. But you find in github or google

**Comment by joelpanor** [comment]
How to include this project into react native? Can you show how you did it please?

**Comment by sankar2389** [comment]
@joelpanor 

const App = () => {
  const {Screenshot} = NativeModules;
  
  const startCapture = async () => {
    await Screenshot.captureScreenshot(delay);
  };

  const stopCapture = async () => {
    await Screenshot.stopCapturing();
  };

  return (
    <SafeAreaView style={styles.container}>
      <TouchableOpacity style={styles.button} onPress={startCapture}>
        <Text style={styles.text}>{'Start Capture'}</Text>
      </TouchableOpacity>
      <TouchableOpacity
        style={[styles.button, styles.buttonStyle]}
        onPress={stopCapture}>
        <Text style={styles.text}>{'Stop Capture'}</Text>
      </TouchableOpacity>
    </SafeAreaView>
  );
}



Android part
ScreenshotPackage.java

import androidx.annotation.NonNull;

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class ScreenshotPackage implements ReactPackage {
    @NonNull
    @Override
    public List<NativeModule> createNativeModules(@NonNull ReactApplicationContext reactContext) {
        List<NativeModule> modules = new ArrayList<>();
        modules.add(new ScreenshotModule(reactContext));
        return modules;
    }

    @NonNull
    @Override
    public List<ViewManager> createViewManagers(@NonNull ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }
}


ScreenshotModule.java

import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.graphics.Bitmap;
import android.graphics.PixelFormat;
import android.hardware.display.DisplayManager;
import android.hardware.display.VirtualDisplay;
import android.media.Image;
import android.media.ImageReader;
import android.media.projection.MediaProjection;
import android.media.projection.MediaProjectionManager;
import android.os.Handler;
import android.util.Base64;
import android.util.Log;

import androidx.annotation.NonNull;

import com.facebook.react.bridge.ActivityEventListener;
import com.facebook.react.bridge.BaseActivityEventListener;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.module.annotations.ReactModule;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.ByteBuffer;

@ReactModule(name = ScreenshotModule.NAME)
public class ScreenshotModule extends ReactContextBaseJavaModule {

    public static final String NAME = "Screenshot";
    private static final String TAG = "ScreenshotModule Error";
    private static final int REQUEST_CODE = 100;

    private ReactApplicationContext reactContext;
    private Promise screenshotPromise;

    private Activity currentActivity;
    private MediaProjection mMediaProjection;
    private MediaProjectionManager mMediaProjectionManager;

    private int mResultCode;
    private Intent mResultData;

    private ImageReader mImageReader;
    private VirtualDisplay mVirtualDisplay;
    private int mDensity;
    private int mWidth;
    private int mHeight;
    private static final String SCREENCAP_NAME = "screencap";
    private static int IMAGES_PRODUCED;
    private Handler mHandler;

    public static int screenshotInterval;

    public static String mStoreDir;

    public ScreenshotModule(ReactApplicationContext reactContext) {
        super(reactContext);
        this.reactContext = reactContext;
        this.currentActivity = reactContext.getCurrentActivity();

        // add listeners
        // reactContext.addLifecycleEventListener(mActivityListener);
        reactContext.addActivityEventListener(mActivityEventListener);

        mMediaProjectionManager =
                (MediaProjectionManager) reactContext.getApplicationContext().getSystemService(Context.MEDIA_PROJECTION_SERVICE);
    }

    private final ActivityEventListener mActivityEventListener = new BaseActivityEventListener() {
        @Override
        public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent intent) {
            if (requestCode == REQUEST_CODE) {
                if (screenshotPromise != null) {
                    if (resultCode == Activity.RESULT_CANCELED) {
                        screenshotPromise.reject(TAG, "Permission Denied");
                    } else if (resultCode == Activity.RESULT_OK) {
                        mResultCode = resultCode;
                        mResultData = intent;
                        setUpMediaProjection();
                        createVirtualDisplay();
                    }
                }
            }
        }
    };

    @Override
    @NonNull
    public String getName() {
        return NAME;
    }

    @ReactMethod
    public void captureScreenshot(int delay, final Promise promise) {
        init(delay);
        screenshotPromise = promise;
        try {
            if (mMediaProjection != null) {
                createVirtualDisplay();
            } else if (mResultCode != 0 && mResultData != null) {
                setUpMediaProjection();
                createVirtualDisplay();
            } else {
                currentActivity.startActivityForResult(mMediaProjectionManager.createScreenCaptureIntent(), REQUEST_CODE);
            }
        } catch (Exception exception) {
            screenshotPromise.reject(TAG, exception);
            screenshotPromise = null;
        }
    }

**Comment by joelpanor** [comment]
Thnaks you for sharing this code.
But I have an error when I try to run the project.
These functions are undefined  **setUpMediaProjection();**
 and **createVirtualDisplay();**

Can you share these functions please?

**Comment by sankar2389** [comment]
private void setUpMediaProjection() {
        mMediaProjection = mMediaProjectionManager.getMediaProjection(mResultCode, mResultData);
    }

    @SuppressLint("WrongConstant")
    private void createVirtualDisplay() {
        // display metrics
        mDensity = Resources.getSystem().getDisplayMetrics().densityDpi;

        // get width and height
        mWidth = Resources.getSystem().getDisplayMetrics().widthPixels;
        mHeight = Resources.getSystem().getDisplayMetrics().heightPixels;

        // start capture reader
        mImageReader = ImageReader.newInstance(mWidth, mHeight, PixelFormat.RGBA_8888, 2);
        mVirtualDisplay = mMediaProjection.createVirtualDisplay(SCREENCAP_NAME, mWidth, mHeight,
                mDensity, getVirtualDisplayFlags(), mImageReader.getSurface(), null, null);
        mImageReader.setOnImageAvailableListener(new ScreenshotModule.ImageAvailableListener(), null);
    }


    private static int getVirtualDisplayFlags() {
        return DisplayManager.VIRTUAL_DISPLAY_FLAG_OWN_CONTENT_ONLY | DisplayManager.VIRTUAL_DISPLAY_FLAG_PUBLIC;
    }

 @ReactMethod
    public void stopCapturing(final Promise promise) {
        if (mVirtualDisplay == null) {
            return;
        }
        mVirtualDisplay.release();
        mVirtualDisplay = null;
        promise.resolve("capture stopped...");
    }

**Comment by joelpanor** [comment]
Thank you for sharing. Can you show the function **ImageAvailableListener** to please?

**Comment by joelpanor** [comment]
Have you a git repo to expose code please?

**Comment by sankar2389** [comment]
https://github.com/sankar2389/ScreenshotNative-Media-Projection.git

https://github.com/sankar2389/ScreenshotNative-Media-Projection/blob/07c54c894de2e24e9c2b47053063d2e824b0caef/app/src/main/java/com/deity/fro/ScreenCaptureService.java#L85
