### ISSUE TITLE
captureScreen has some bugs

### ISSUE THREAD

**Issue by KouSyurei** [gre/react-native-view-shot#349]
Take full screen, no status bar in the screenshot
![企业微信截图_0fbcea13-ad02-4a26-8cd8-bfa974d310f0](https://user-images.githubusercontent.com/29012830/114003213-25b0fa00-9890-11eb-8a2c-c72b0e870d00.png)

**Comment by gre** [comment]
This is part of the OS, I don't think we can programmatically achieve what you asked.
