### ISSUE TITLE
ScrollView with horizontal={true} does not capture entire view 

### ISSUE THREAD

**Issue by fariya12** [gre/react-native-view-shot#352]
I have a view with top vertical  scrollview  and inside  a horizontal flatlist when trying to capture viewshot
 horizontal view is getting trimmed not able to get full view for horizonatl view any idea how to  ??

**Comment by mengxianglong123** [comment]
I also faced this problem.Did you find a solution？

**Comment by mengxianglong123** [comment]
> I have a view with top vertical scrollview and inside a horizontal flatlist when trying to capture viewshot horizontal view is getting trimmed not able to get full view for horizonatl view any idea how to ??

I have found the way to solve this problem just now.When you set  horizontal={true},you can not write the ViewShot tag out the ScollView，you shoud write it inner ScrollView.Just like this:

```html
<ScrollView horizontal={true}>
    <!-- 包裹其子标签，而不是ScrollView -->
    <ViewShot ref={shot}>
        <View style={styles.overTest} >
            
            <View><Text style={styles.overText}>一岁一枯荣开始</Text></View>
            <View><Text style={styles.overText}>一岁一枯荣</Text></View>
            ...
        </View>
    </ViewShot>
```

**Comment by gre** [comment]
This should be fixed by using `snapshotContentContainer` option
