### ISSUE TITLE
Problem with Jest Rendering

### ISSUE THREAD

**Issue by exithial** [gre/react-native-view-shot#359]
I'm having problems rendering with "@testing-library/react-native" in jest, I'm using "react-native-view-shot": "^ 3.1.2", and the console returns the following error 

"Warning: React.createElement : type is invalid - expected a string (for built-in components) or a class / function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports."

![image](https://user-images.githubusercontent.com/20939594/119572334-8d5bcf80-bd80-11eb-880c-dde88fb54c8c.png)

**Comment by jaysonsori0** [comment]
Try to mock the library by creating `react-native-view-shot.js` and put it in `__mocks__` folder on your `src`.

This is the code I put on the mock file:

```
import React from 'react';

class ViewShot extends React.Component {
    render() {
        return null;
    }
}

export default ViewShot;
```

It worked for me. I hope it helps.

**Comment by flexbox** [comment]
Hey @Xulthes 

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by iRetray** [comment]
A better mock implementation to render successfully the children and get working the capture() method will be the next one, I have tested the capture() method and the correct render of the children on Jest and it works properly
`
import React from 'react';

class ViewShot extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return this.props.children;
  }

  capture() {
    return new Promise(resolve => {
      resolve('fake/path/to/view-shot-file.jpg');
    });
  }
}

export default ViewShot;
`

**Comment by Raja71** [comment]
Hey,

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

I created custom hook with this library and trying to use across the components but getting above error,

I have used below solution:
import React from 'react';

class ViewShot extends React.Component {
    render() {
        return null;
    }
}
export default ViewShot;

added in jest.config.js file
 '^react-native-view-shot': '<rootDir>/src/__mocks__/CaptureScreenShot.tsx',
 
 and mocked in test file 
 jest.mock('react-native-view-shot')
