### ISSUE TITLE
Exporting airbnb/react-native-map results in blank image

### ISSUE THREAD

**Issue by kanekotic** [gre/react-native-view-shot#36]
Hello first of all great package 😄 .

This is more a question than an issue, but trying to export a MapView from https://github.com/airbnb/react-native-maps the map itself is a blank. Do you have any idea on why this could be happening?. Could it be that is probably a native element so this exporter does not know how to render something that is not a react-native rendered element? (I imagine i can be completely wrong on my self-explanation on why it does not work)

**Comment by elliotstokes** [comment]
Hey. I'm seeing the same issue (android only). I'm guessing it's something to do with the way the maps are rendered.

**Comment by gre** [comment]
this might be somehow related to the same problem appearing for WebView ( https://github.com/gre/react-native-view-shot/issues/34 ) . there are probably some kind of View like OpenGL View that are not friendly with current implementation of snapshotting. I'm wondering if it's solvable and i would be happy if anyone want to investigate.

it would be good to have somewhere a test app that test bunch of different kind of view, so we can easily test things and do a checklist of things supported per platform.

**Comment by elliotstokes** [comment]
I've done a bit of digging and have come up with a possible solution.

You need to grab all the textureviews contained within that view and then render them on top of the base bitmap using a canvas.

Solution can be found within this thread (https://github.com/fastlane/fastlane/issues/2081). I've tried it out and I'm correctly seeing my map image.

**Comment by gre** [comment]
mmh that's very promising! do you think it can be done generically on a View?

**Comment by kanekotic** [comment]
hello sorry for the delay in getting back here but i had a crazy week. I think is a good thing to try, if you want i am cloning and doing some tests to see if i can create a PR 👍 , let me know if any of you is doing the same so we dont overlap 😛

**Comment by kanekotic** [comment]
well i can see the map now :) with this commit https://github.com/kanekotic/react-native-view-shot/commit/fab00971c1da74ae9ad1a2e09d939e2740821c6f , the view is missaligned when I export but I will try to solve that ... but seems a good direction to solve this 😄

**Comment by gre** [comment]
yeah feel free to do this and get a PR! that would be awesome =)

I guess we'll eventually need to investigate the same for iOS, but ok for now to just focus on android

**Comment by kanekotic** [comment]
so I have been putting a bit of time on this, but still having issues, the problem is how to combine different layers in the bitmap, specifically what areas are going to be ignored, also the layering seem a bit complex. I will keep you guys posted.

meanwhile I find a small workaround  for maps that could interest you @elliotstokes and is set the property `cacheEnabled` to true in the `MapView` to get the map as an image (it works for me, I have not tried it to change it on the fly).

**Comment by gre** [comment]
https://github.com/gre/react-native-view-shot-example now includes a react-native-maps example. it seems to work on iOS but I can reproduce the problem for Android.

**Comment by gerardus1995** [comment]
Yes, on Android still i see a black snapshot with only the google logo.

**Comment by gre** [comment]
@gerardus1995 what about this https://github.com/airbnb/react-native-maps#take-snapshot-of-map ?

if that lib can do the snapshotting instead, we will close that issue.

**Comment by gerardus1995** [comment]
Yes it works! Thanks!
