### ISSUE TITLE
Resizing issue

### ISSUE THREAD

**Issue by veyselkurnaz** [gre/react-native-view-shot#361]
Platform: Android 11

I have given width and height to ViewShot, but the width and height of the image I get is not what I want.

The width and height of the resulting image is 2200x1375

Here is the code:

  <ViewShot ref={this.viewShot} options={{format: 'png',width:1027,height:767}}>
                  <Image
                    source={source}
                    style={{
                      height: imageHeight,
                      width: imageWidth,
                    }}
                    resizeMode="center"
                  />
                  <View style={styles.boxes}>{this.renderResults()}</View>
                  <View style={styles.boxes}>{this.renderResults()}</View>
     </ViewShot>

Thanks a lot

**Comment by VinitBhavsar** [comment]
@veyselkurnaz you're passing the wrong option.
`
"width/height": 1027/767
`

**Comment by gre** [comment]
should be fixed by https://github.com/gre/react-native-view-shot/pull/414
