### ISSUE TITLE
How to capture entire vertical scrollview using <ViewShot> element?

### ISSUE THREAD

**Issue by pallaviMN** [gre/react-native-view-shot#362]
I am using react native hooks and embed <ViewShot> inside scrollview but it doesnt capture entire screen.

**Comment by Mkaleem-neslit** [comment]
i am facing a same issue can u help me ?
@pallaviMN

**Comment by gre** [comment]
you have to use a `snapshotContentContainer` option, but you should probably not use `<ViewShot` but instead use a ref of the scroll view to do the snapshot.
