### ISSUE TITLE
available for surfaceview screenshot ?

### ISSUE THREAD

**Issue by zldada** [gre/react-native-view-shot#37]
My app use surfaceview to display the video,and I want to take a screenshot to share to other people when i play the video, i have tried many ways,but did'n work,what i got is black screen, so I want to ask this program can be used to take a screenshot of surfaceview ? Any advice will be appreciated.

**Comment by gre** [comment]
aware of that current limitation, it's something we currently are discussing in https://github.com/gre/react-native-view-shot/issues/34 and https://github.com/gre/react-native-view-shot/issues/36 
and there might be a beginning of a solution in that #36 , if you have time to experiment on that, and provide a PR, it would be good :)

**Comment by gre** [comment]
there is probably a common generic solution across your usecase and #36, i'll close the issue in favor of #36 if you don't mind, if you come to a solution, PR is welcomed!

also I've started to establish a table of what is currently supported or not in the README
