### ISSUE TITLE
Android - ViewShot is not capturing all children of the View

### ISSUE THREAD

**Issue by fdagostino** [gre/react-native-view-shot#370]
### bug report
When capturing a View with two children, a gl-react Surface rendering a photo taken with the camera and a Image PNG mask on top of it, and saving it to the media library, the saved image contains only the image rendered in the Surface and is not including the PNG mask/overlay.

Please, let me know if you need further info.

#### Version & Platform

react-native@0.63.2  invalid
└── react-native-view-shot@3.1.2

**Platform:** Android - Expo

#### Expected behavior

When capturing a View it should capture all the visible children.

![expected](https://user-images.githubusercontent.com/17678220/127905075-a1a701e8-85e2-4c5a-9fa4-de7dcbfcb841.png)

#### Actual behavior

When capturing a View it is capturing only one child.

![actual](https://user-images.githubusercontent.com/17678220/127905063-243c4482-3adb-4183-9114-f44ca04ac4e9.png)

#### Steps to reproduce the behavior

You can find a repro here: https://github.com/fdagostino/react-native-view-shot-repro-expo-android-issues

**Comment by GitKat** [comment]
Ok I ve been working on it recently. and found a way to achieve this.
For some reasons when you Capture directly with camera opened it will always gets on top.
I solve this issue first taking the picture from camera 
Then sets the Image uri to rasterize other elements  on top of uri came from the camera

**Comment by GitKat** [comment]
![Screenshot_1630828148](https://user-images.githubusercontent.com/7541657/132119561-b59d6a48-b145-4d5b-9ae2-9eca56a3845b.png)

**Comment by fdagostino** [comment]
Hey @GitKat, can you provide me with a code example?

**Comment by GitKat** [comment]
Ok. my code is not so professional I'm just learning...
first: Im using RNCamera to open camera, 
I dont use RNCamera to take pictures. Im using CaptureRef/CaptureScreen (upto you what you use )

```
> <View collapsable={false} ref={viewRef} style={styles.container}>
>   <RNCamera ref={cameraRef}  style={styles.actualImage}></RNCamera> 
>   <View
>     style={{flex: 0, flexDirection: 'row', justifyContent: 'center'}}>
>     <TouchableOpacity
>       onPress={() => captureHandler(route.params.imageNum)}
>       style={styles.btnText}>
>       <Text style={{fontSize: 14}}> SNAP </Text>
>     </TouchableOpacity>
>   </View>
> </View>
```

inside captureHandle function , this is where I  get the capture from RNCamera, and then setting the URI to a hook and passing
it to image component and take an auto screenshot() after 600 ms  
```
>  captureRef(viewRef, {
>         format: 'jpg',
>         quality: 0.8,
>       }).then(
>         uri => {
>           const filePath = uri; 
>           setImageURIRN(filePath);
>           setShowSecondStep(true); 
>           setTimeout(() => { 
>             takeScreenShot();
>           }, 600);
>         },
>         error => console.error('Oops, snapshot failed', error),
>       );
```

Here in second step,  im using ImageBackground Component to set my image as background.

```
> <View ref={viewRef2} style={styles.containerR}>
>           <ImageBackground source={{uri: imageURIRN}} style={styles.camera_img}>
>             <View style={styles.imgPrev}>
>               {/* <Text>Centered text</Text> */}
>               {/* <Text style={styles.titleText}>
>                 React Native Example to Take Screenshot Programmatically
>               </Text> */}
>               {/* <Text style={styles.textStyle}>
>                 {savedImagePath ? `Saved Image Path\n ${savedImagePath}` : ''}
>               </Text> */}
>               {/* <Text style={{fontSize: 30}}> 📷 3</Text> */}
>               {/* <TouchableOpacity
>                 style={styles.buttonStyle}
>                 onPress={takeScreenShot}>
>                 <Text style={styles.buttonTextStyle}>Take Screenshot</Text>
>               </TouchableOpacity> */}
>               <Text style={styles.operatinDetails}>{Date()}</Text>
>             </View>
>           </ImageBackground>
>         </View>
```
 now that takeScreenShot() function capture the screen with text on it, im using date for my use case...

```
> const takeScreenShot = () => {
>     // To capture Screenshot
>     // captureScreen({
>     captureRef(viewRef2, {
>       // Either png or jpg (or webm Android Only), Defaults: png
>       format: 'jpg',
>       // Quality 0.0 - 1.0 (only available for jpg)
>       quality: 0.8,
>     }).then(
>       //callback function to get the result URL of the screnshot
>       uri => {
>         setSavedImagePath(uri);
>         // setImageURI(uri);
>         setImageURIRN(uri);
>         setUploadStep(true);
>         setLoading(false);
>       },
>       error => console.error('Oops, Something Went Wrong', error),
>     );
>   };
```
Now the last step if you want further more actions its upto you. im just uploading at this point.





https://user-images.githubusercontent.com/7541657/132246300-96638ff1-6c1b-4c14-a622-54ab60fe7d1d.mp4

**Comment by GitKat** [comment]
u can close this issue now !
