### ISSUE TITLE
Uncaught (in promise) Error: react-native-view-shot: NativeModules.RNViewShot is undefined. Make sure the library is linked on the native side.

### ISSUE THREAD

**Issue by rafaelbrahmantya** [gre/react-native-view-shot#378]
Hi i am using expo, and i got this error while using the ViewShot.

Can you help me resolve this ?

**Comment by GitKat** [comment]
make sure the library is installed properly.

**Comment by harriscreativity** [comment]
react-native-view-shot: NativeModules.RNViewShot is undefined. Make sure the library is linked on the native side.
 ERROR  TypeError: Cannot read property 'FACEBOOK' of null, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

**Comment by alephpt** [comment]
same error using yarn

**Comment by angleneo** [comment]
same error

**Comment by jhsonmac** [comment]
use `<View ref={viewRef} collapsable={false}>...</View`

**Comment by gre** [comment]
This error is supposed to be a build problem but please check with latest version https://github.com/gre/react-native-view-shot/releases/tag/v3.3.0 Feel free to recreate the issue if it is still happening. Thanks

**Comment by bayramn** [comment]
Still happening. It works fine in development (Simulator, ExpoGo), but throws above error in iPhone app. What could be causing it? I am sharing it as soon as screenshot captures, not sure that is causing.

**Comment by ColeTownsend** [comment]
@bayramn did you figure this out

**Comment by bayramn** [comment]
> @bayramn did you figure this out

Nope, I think they have new update with new Expo 46 SDK that you can see in [changelog](https://github.com/expo/expo/blob/main/CHANGELOG.md#:~:text=%40kudo)-,Updated,-react%2Dnative%2Dview). I need rebuilt and check. I'll let you know soon.

**Comment by ofir-hakshur** [comment]
Has someone overcome this problem?

**Comment by Eli-BH** [comment]
Same error   "expo": "~50.0.14", with dev client.

**Comment by lhguerra** [comment]
still happening with expo 52 and view shot 3.8.0
