### ISSUE TITLE
How to download the view shot to my downloads folder?

### ISSUE THREAD

**Issue by Aryan6290** [gre/react-native-view-shot#382]

**Comment by mitjnextt** [comment]
Hey @Aryan6290 , You can use [rn-fetch-blob](https://www.npmjs.com/package/rn-fetch-blob)

**Comment by GitKat** [comment]
You can use **react-native-fs** as I'm using it in my project

**Comment by Victorcassiano** [comment]
> You can use **react-native-fs** as I'm using it in my project

Can you show me an example?
