### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by njimmy10** [gre/react-native-view-shot#384]
<img width="1440" alt="Screen Shot 2021-11-27 at 1 40 04 PM" src="https://user-images.githubusercontent.com/90354662/143679670-d094814d-f475-4549-92ff-822ec83ec288.png">
i am having this error while compiling, can someone help

**Comment by gre** [comment]
please check with latest version https://github.com/gre/react-native-view-shot/releases/tag/v3.3.0 Thanks

**Comment by njimmy10** [comment]
Still the same erro
<img width="1440" alt="Screen Shot 2022-05-29 at 1 35 42 PM" src="https://user-images.githubusercontent.com/90354662/170863702-906deeef-d621-4c77-8863-77fd105ef8ea.png">
r

**Comment by gre** [comment]
Do you have a simple project that reproduces it? Because the example project don't have this issue.
Are you using React Native , Expo ? which version? 

Thanks
