### ISSUE TITLE
deprecated String-refs instead of React.createRef()

### ISSUE THREAD

**Issue by Thunermay** [gre/react-native-view-shot#388]
### deprecation report 

**Platform:** iOS & Android

#### Actual behavior

You use String-refs. Strings-refs are soon to be deprecated. Please change this, so you can use `React.createRef()`
https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs

#example

current:
`<ViewShot ref={"viewshotRef"}>`

how it should be:
```
this.viewShotRef = React.createRef();

<ViewShot ref={this.viewShotRef} >
```

**Comment by gre** [comment]
Thanks. Fixed in the readme.
