### ISSUE TITLE
Support for react-native 0.40+

### ISSUE THREAD

**Issue by rohitgoyal** [gre/react-native-view-shot#39]
I am getting this issue with RNViewShot in react-native 0.40

<img width="262" alt="screen shot 2017-02-14 at 8 24 55 pm" src="https://cloud.githubusercontent.com/assets/4688513/22934082/b756afbe-f2f3-11e6-9962-91316fe02e38.png">

**Comment by gre** [comment]
there were some breaking changes introduced in RN 0.40
are you sure you are up to date with react-native-view-shot library? (check what `npm ls react-native-view-shot` tell you) You need at least version 1.6.0

**Comment by fantapop** [comment]
Same problem here

**Comment by gre** [comment]
Do you know where the bug is and where to fix it? is that a bug on user project side or on the library side? Because I was able to use the library on a new project, mmh

**Comment by fantapop** [comment]
I verified that it works with the latest version.  My app was actually on an old version.

**Comment by AmirolAhmad** [comment]
im also getting the same problem.

```
$ npm ls react-native-view-shot
react-native-view-shot@1.7.0
```

**Comment by gre** [comment]
going to close this because a bad version / cache issue is probably the reason.
