### ISSUE TITLE
TypeError: cannot set sizeCalculation without setting maxSize

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [gre/react-native-view-shot#394]
### Error asking 
<img width="973" alt="image" src="https://user-images.githubusercontent.com/97073795/155506747-a662c749-11d7-47d0-88ef-a3943dfd89c4.png">
After download and build with xcode gives the following error

#### Version & Platform
Version 3.1.2
**Platform:** iOS

**Comment by gre** [comment]
This library don't use LRUCache so it must be something else.
