### ISSUE TITLE
Android TextureView Freezes when trying to get viewshot

### ISSUE THREAD

**Issue by tinni95** [gre/react-native-view-shot#401]
On android, if I try to capture a screenshot of a texture view. The texture view stream freezes for one second.

Any suggestions on this?

**Comment by tinni95** [comment]
After some testing I realised the issue is that the I/O operation of saving the bitmap (ViewShot.java, line 392) blocks the ui because it is done in the UI thread.

**Comment by gre** [comment]
3.3.0 have shifted the computation to a background thread. 🤞
