### ISSUE TITLE
Can't build after installing in iOS

### ISSUE THREAD

**Issue by JulioRosil** [gre/react-native-view-shot#404]
**Platform:** iOS? Android?
iOS

I just installed on iOS today, buy I have a lot of build error. The build fails exclusively with this library.

React Native 0.68.1
Xcode 13.3.1

![image](https://user-images.githubusercontent.com/99291594/165864850-6f3d387e-6ba6-4e7e-bf95-53580ea0adce.png)

**Comment by gre** [comment]
3.3.0 should have fixed it. thanks
