### ISSUE TITLE
Image Resolution Doubled?

### ISSUE THREAD

**Issue by fantapop** [gre/react-native-view-shot#41]
When I load an image into a view and then use react-native-view-shot to create an image from that view the resolution seems to be doubled.

I don't think I'm doing anything weird...

Here is the function I'm using to take the image:
```
        console.log('taking picture of size: ', width, height);
        RNViewShot.takeSnapshot(this.refs['layout'], {
            format: 'png',
            quality: 0.8,
            width,
            height
        })
        .then(
            uri => {
                console.log('Image saved to', uri);
                Image.getSize(uri, (width, height) => {
                    console.log(`Image dimensions: ${width}x${height}`);
                });
            },
            error => console.error('Oops, snapshot failed', error)
        );
    }
```

And the output:

```
[PERF ASSETS] Loading image at size {3600, 3600}, which is larger than the screen size {750, 1334}
index.ios.js:21 taking picture of size:  3600 3600
index.ios.js:30 Image saved to /Users/chris/Library/Developer/CoreSimulator/Devices/A0EC9E9C-B184-46B8-80BE-DCCA88E4C699/data/Containers/Data/Application/2552626F-31AC-4F3D-86BF-12EFCC163100/tmp/ReactNative/DB9581E0-E465-460C-A3E9-FC904218C47E.png
index.ios.js:32 Image dimensions: 7200x7200
```

**Comment by fantapop** [comment]
I'm not sure, but I have a suspicion this has to do with my screen being a retina display.
https://developer.android.com/studio/troubleshoot.html#scaling_factor_settings

**Comment by gre** [comment]
yeah I think this is because of Retina, I don't think this is a bug but more a feature. the screenshot is in real pixel, not virtual pixel size.
If you want to make it resized to a given size, you can use the width and height options.
