### ISSUE TITLE
react-native-view-shot:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by EashSundar** [gre/react-native-view-shot#411]
This is failing the build and started happen after the new release of the package.

**Comment by cristianoccazinsp** [comment]
Looks like this is only supported in updated Java / React-Native versions. What version are you guys using?

**Comment by EashSundar** [comment]
@cristianoccazinsp react native version 0.63.4

**Comment by cristianoccazinsp** [comment]
Looks like a problem with Java, you need at least Java 8 for lambdas to work. I think RN changed Java to Java 11 starting 0.65, but I can't find anywhere before that what's the default Java version.

**Comment by cristianoccazinsp** [comment]
Not without upgrading Java or changing the code to not use lambdas.

**Comment by cristianoccazinsp** [comment]
Can you share part of your build.gradle files to see whether or not you are setting the java/jdk version to 7?

**Comment by EashSundar** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        renderscriptVersion = 21
        ndkVersion = "20.1.5948944"
        googlePlayServicesAuthVersion = "16.0.1"
        firebaseMessagingVersion="21.1.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
        classpath 'com.google.gms:google-services:4.3.5'
        classpath "com.bugsnag:bugsnag-android-gradle-plugin:5.+"
        //classpath("com.android.tools.build:gradle:3.5.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

@cristianoccazinsp

**Comment by cristianoccazinsp** [comment]
Please also share the `app/build.gradle` file. The RN docs clearly define Java 1.8 (https://github.com/facebook/react-native/blob/v0.63.4/template/android/app/build.gradle) for RN 0.63. Any chance java 1.6 is defined there?

**Comment by cristianoccazinsp** [comment]
There's something your build stack that's telling the compiler to use Java 7, but I can't really find where that would be defined.

**Comment by cristianoccazinsp** [comment]
Maybe android studio is pointing to java 7? From your error above, the compiler is using java 7 instead of 8.

**Comment by EashSundar** [comment]
Much Thanks, will try it @cristianoccazinsp
