### ISSUE TITLE
Can we save the GIF?

### ISSUE THREAD

**Issue by mertbuldur** [gre/react-native-view-shot#412]
How can we save if there is a gif in the view while taking the view image.

**Comment by gre** [comment]
I'm afraid generating animation, video or gif is not in the scope of this library.

**Comment by mertbuldur** [comment]
Is there a package you can recommend for this?

**Comment by ashrazdev** [comment]
@mertbuldur did you find a solution?
with the help of this library, I am taking multiple shots of  captureMode={'continuous'} and making gifs of my animation which is created by React Native Animated but Animation is not working 😂
