### ISSUE TITLE
Error Installing - iOS simulator loads to blank screen

### ISSUE THREAD

**Issue by kevando** [gre/react-native-view-shot#43]
This is the error in xcode logs

`RCTBridge required dispatch_sync to load RCTAccessibilityManager. This may lead to deadlocks`

**Comment by kevando** [comment]
It happens when I turn on chrome debugger

**Comment by gre** [comment]
The error does not seem related to the lib or any dependency of the library. are you sure you are not having another issue in your build?

**Comment by kevando** [comment]
It could be something with my local config, but when I run the example app and turn on the debugger I get the same issue.

**Comment by gre** [comment]
on a device or simulator? which iOS version?

**Comment by kevando** [comment]
Simulator.

Seems like it could be related to [this issue](https://github.com/facebook/react-native/issues/11196#issuecomment-285672227)

**Comment by jbolter** [comment]
I fixed this issue by moving libRNViewShot.a to the bottom of my Build Phases -> Link Binaries With Libraries and I am able to use the debugger again.

**Comment by ankymtan** [comment]
@jbolter It works :). Thanks a lot. You have any idea why?
