### ISSUE TITLE
How to share image with a URL of the product attached below

### ISSUE THREAD

**Issue by isoftpage22** [gre/react-native-view-shot#434]
### feature request
Hi I want  to share image with a URL of the product attached below

#### Version & Platform
3.3.0

**Platform:** iOS? Android?
BOTH

**Comment by didiabel** [comment]
yo will have to generate the the image with a ref that belongs to a view that contains everything you want to share

**Comment by isoftpage22** [comment]
![Screenshot_2022-08-23-23-51-56-190_com whatsapp w4b](https://user-images.githubusercontent.com/110735049/186234906-726cb06f-f44b-497f-a163-39e1b067bb1f.jpg)

**Comment by didiabel** [comment]
for url's you might need [react-native-share
](https://www.npmjs.com/package/react-native-share)
this might help you out https://stackoverflow.com/questions/49484159/react-native-can-we-share-an-image-and-text-into-whatsapp
