### ISSUE TITLE
Large image is empty / blank on iOS. useRenderWithContext doesn't exists

### ISSUE THREAD

**Issue by israel-dv** [gre/react-native-view-shot#437]
### bug report 

I 'm capturing a list, but the bigger the list, the image becomes empty. 

This only happens on iOS, in android works well

#### Version & Platform

``` react-native-view-sho: 3.4.0```

**Platform:** iOS

#### Steps to reproduce the behavior
Take a shoot in a list component when the list is very big.

**Comment by hengkx** [comment]
3.5.0 same

**Comment by BuhTig8** [comment]
same
