### ISSUE TITLE
Project RNViewShot supports: uap10.0.17134 (UAP,Version=v10.0.17134)

### ISSUE THREAD

**Issue by Qurishe** [gre/react-native-view-shot#438]
RNViewShot doesn't seem to work with version (10.0.19041.0) is there a way to change the target version to  (10.0.19041.0)?

System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 6.33 GB / 11.90 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32901.82 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0 => 0.70.0
    react-native-windows: 0.70.1 => 0.70.1
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by gre** [comment]
mmh what is uap10.0.17134 ?

**Comment by 592da** [comment]
i have the same issue,
some one solved it?
@gre @Qurishe ?

**Comment by gre** [comment]
What is the issue? i'm completely lost on what is getting reported here.

**Comment by 592da** [comment]
I found the issue, it's when building react-native-windows, the UAP is basically the windows SDK version, i fixed it locally.
thanks!
