### ISSUE TITLE
can not take shot on iphone device when playing video ,on simulator wos ok!

### ISSUE THREAD

**Issue by neegqi** [gre/react-native-view-shot#46]

**Comment by gre** [comment]
can you precise what happens? Does it crash / does it renders black?

**Comment by neegqi** [comment]
not crash, called Promise catch and return error "Failed to capture view snapshot"

**Comment by gre** [comment]
I'll try to improve the error message because it's probably breaking internally in the Android side (it's Android, right?)

**Comment by neegqi** [comment]
no it`s on ios real device,using react native video module to play hls Stream,

**Comment by gre** [comment]
Ok. I'll give a try! it might be that the `drawViewHierarchyInRect` function returns FALSE and I'll need to see what's the way to fix it / get a better error message.

**Comment by neegqi** [comment]
thanks

**Comment by gre** [comment]
I think the error needs to be more clear or it should just renders something black (not this weird error).
but note that it's likely snapshotting a video won't work (maybe we'll have good surprise, but not sure!). see actually https://github.com/react-native-community/react-native-video/issues/95

**Comment by gre** [comment]
I'm afraid currently answer is you can't.
even thought it seems to work on Simulator, the renderInContext does not work for Video, it renders black (if ignoring the returned value of drawViewHierarchyInRect – I don't want to ignore it and prefer the call to be a failure promise so you can deal with it and not end up with a black image)

– at least it's not possible with the video from react-native-video, therefore, it will be up to this library to provide you a way to get a snapshot from a video. and it's possible to do, but it needs lower level API calls ( http://stackoverflow.com/questions/8291727/ios-extracting-video-frames-as-images )

**Comment by gre** [comment]
we could find a generic solution that react-native-view-shot would use, like react-native-video could expose some sort of generic method we would duck-call. but i'll leave that to the following issue: https://github.com/react-native-community/react-native-video/issues/95
