### ISSUE TITLE
Error: No view found with reactTag with new architecture 

### ISSUE THREAD

**Issue by ErHarinderSingh** [gre/react-native-view-shot#469]
[](url)Hi there, 
I am getting error No view found with reactTag but only with new architecture.
Same error in both Android & iOS.
Anyone? How to resolve it?

<img width="682" alt="Screenshot 2023-04-15 at 13 42 54" src="https://user-images.githubusercontent.com/22139572/232199888-a5d244d6-86f3-4116-a39c-0a95481b5e01.png">

**Comment by ErHarinderSingh** [comment]
I think it's because **findNodeHandle** is not compatible with React 18. Deprecation of findNodeHandle in React Native is similar to the [deprecation of findDOMNode in React DOM](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage).

And the thing is react-native-view-shot uses **findNodeHandle**
Here is the link :
https://reactnative.dev/docs/0.70/new-architecture-library-intro#preparing-your-javascript-codebase-for-the-new-react-native-renderer-fabric

**Comment by ErHarinderSingh** [comment]
@gre make attention please.

**Comment by ErHarinderSingh** [comment]
**viewRegistry[target]**
is coming as null inside iOS Native Module **RNViewShow.m**

**Comment by faceyspacey** [comment]
+1

**Comment by faceyspacey** [comment]
It looks like the native code is going to have be rewritten to support the new architecture.

It seems the following code (for iOS) needs to be written using the "Fabric Native Components" methodology:

https://reactnative.dev/docs/the-new-architecture/pillars-fabric-components


```js
RCT_EXPORT_METHOD(captureRef:(nonnull NSNumber *)target
                  withOptions:(NSDictionary *)options
                  resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)
{
  [self.bridge.uiManager addUIBlock:^(__unused RCTUIManager *uiManager, NSDictionary<NSNumber *, UIView *> *viewRegistry) {

    // Get view
    UIView *view;

    if ([target intValue] == -1) {
      UIWindow *window = [[UIApplication sharedApplication] keyWindow];
      view = window;
    } else {
      view = viewRegistry[target];
    }

    if (!view) {
      reject(RCTErrorUnspecified, [NSString stringWithFormat:@"No view found with reactTag: %@", target], nil);
      return;
    }
```
> *node_modules/react-native-view-shot/ios/RNViewShot.m*

**Comment by ErHarinderSingh** [comment]
Yeah, And same for android @faceyspacey

**Comment by the-skins-app** [comment]
Any update on this one? @gre

**Comment by ErHarinderSingh** [comment]
Any update on this @gre ?

**Comment by ErHarinderSingh** [comment]
We are facing this from 0.70.x. Now we are at 0.73.x and the issue is still there for new architecture. New architecture is mandatory now. Someone has to focus on this issue. React Native Skia is also capturing screenshot images. Someone can refer to the code changes from there.
Cc : @gre

**Comment by rohit-jindal018** [comment]
capture not working in Android new architecture.

**Comment by faceyspacey** [comment]
Need this too.

**Comment by uzaymacar** [comment]
Any updates on this?

**Comment by rabbitmouse** [comment]
i have same issue on ios
<img width="329" alt="image" src="https://github.com/gre/react-native-view-shot/assets/11554140/5f1304a7-dd04-4c77-8715-df60830bdbf9">

**Comment by L0rdCr1s** [comment]
> i have same issue on ios <img alt="image" width="329" src="https://private-user-images.githubusercontent.com/11554140/312691691-5f1304a7-dd04-4c77-8715-df60830bdbf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjkyNTYsIm5iZiI6MTcxMDQyODk1NiwicGF0aCI6Ii8xMTU1NDE0MC8zMTI2OTE2OTEtNWYxMzA0YTctZGQwNC00Yzc3LTg3MTUtZGY2MDgzMGJkYmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE1MDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNWY3MTYyNmU2OGIyMWYyNTI2ZjlhZWIxYjFhM2Y2MWIwMzFjMTQ5N2ZmNzY4YTkwYWNjNmY4YmRjOWZlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BSggSfbzaJqbzScbrN8MiigzJnymqzjul8u_DTxWonY">

have you found a workaround for this issue, I only found out that the `addUIBlock` is no longer working with the newArch enabled, i'm looking for alternatives

**Comment by cortinico** [comment]
Here the fix for this library:
- https://github.com/gre/react-native-view-shot/pull/516

**Comment by NoahSimajji** [comment]
Hi there,  i getting this issue on IOS only. Any workaround for this?

**Comment by alainib** [comment]
i have this error now with react native 0.76
how to fix this please ?

**Comment by brianangulo** [comment]
> i have this error now with react native 0.76 but we don't use `react-native-view-shot` how to fix this please ? i didn't found anything on internet

If you don't have this package then search somewhere else this error is RN specific and can be thrown by other packages that rely on this API also

**Comment by theBGuy** [comment]
I'm seeing this issue still with:
- react native: 0.77 on the new arch
- expo sdk 52
- react-native-view-shot: 3.8.0 and 4.0.3

**Comment by somasekharkakarla** [comment]
Hi guys, i am using react native 0.76.6 with new arch and react-native-view-shot is 4.0.3. still issue exists. Please reopen the ticket

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/6c9eadd2-a5c7-4e03-a6b5-237e65037dc7" />

**Comment by Essam-Harrous** [comment]
Me too it's still happening

**Comment by Essam-Harrous** [comment]
@somasekharkakarla 

I found this alternative
`import ViewShot from "react-native-view-shot";`

 `await viewShotRef?.current
      ?.capture?.()
      .then((uri) => {
        console.log(uri, "uri");`

use this view reference instead.
`  const viewShotRef = useRef<ViewShot>(null);`

use this ViewShot component instead
`      <ViewShot ref={viewShotRef}>`

**Comment by somasekharkakarla** [comment]
@Essam-Harrous I tried the same way yesterday. Yes It worked.

**Comment by daehyeonmun2021** [comment]
@Essam-Harrous 's solution works here but snapshotContentContainer option doesn't work with it.
