### ISSUE TITLE
iOS: add support for snapshotContentContainer bool option

### ISSUE THREAD

**Issue by gre** [gre/react-native-view-shot#47]

**Comment by noodleutopia** [comment]
When I use snapshotContentContainer with ScrollView, I can just snapshot content with the height of current screen, missing the content beneath...can you help me ?
BTW, I got this message when debugging:
`[PERF ASSETS] Loading image at size {750, 1773}, which is larger than the screen size {750, 1334}`

**Comment by gre** [comment]
weird! it might be broken. feel free to send a PR if you send a fix, otherwise i'll investigate ASAP.

**Comment by noodleutopia** [comment]
BTW, this problem only occurs on iOS and I'm using simulator. It works fine on Android.

**Comment by ihor** [comment]
I'm still having the same issue. ```react-native-view-shot``` version ```1.9.1```, React Native version ```0.42.3```. Could you help me, please?
