### ISSUE TITLE
React Native Version

### ISSUE THREAD

**Issue by boblad** [gre/react-native-view-shot#5]
Im on RN 0.27.2 and I got it working just great with IOS, However android fails with `import com.facebook.react.uimanager.UIBlock;` and anything that uses the UIBlock, Does android only work with versions of react-native that are `react-native@>=0.30.0`?

**Comment by gre** [comment]
yes. only works starting from 0.30.0, it's impossible to resolve a View before this version. https://github.com/facebook/react-native/pull/8217
