### ISSUE TITLE
Blur image

### ISSUE THREAD

**Issue by shengzihong** [gre/react-native-view-shot#50]
The shot image is blur, even though I set the quality to 1.0.
Is there anyway to get a high quality or clear image?

**Comment by Eyesonly88** [comment]
+1. The image quality even when using `png` format is not the best. 
I can see compression happening and area around the text is pixelated.

Is it possible to disable all compression and get the highest possible image?

**Comment by gre** [comment]
on which platform?
do you use any `{width,height}` option (better not to if you don't want the implementation to resize the image)

**Comment by Eyesonly88** [comment]
@gre I'm using it on iOS 10 using RN `0.42.2`. 
I'm not sizing it and just using the default options.

**Comment by gre** [comment]
I'm not sure why it happens and we can do.
this code looks fine: https://github.com/gre/react-native-view-shot/blob/master/ios/RNViewShot.m#L95-L98

especially in `UIGraphicsBeginImageContextWithOptions(size, NO, 0);` the zero makes sure it will use the device pixel ratio (e.g. retina) quality.. mmh

**Comment by gre** [comment]
I don't think there is anything we can do about this. we are using the raw iOS api to capture the view, if you ever find a better way I'm happy to accept a PR.
