### ISSUE TITLE
[iOS] Prevent snapshot flash?

### ISSUE THREAD

**Issue by joncursi** [gre/react-native-view-shot#51]
Is it possible to prevent the snapshot screen flash on IOS?

**Comment by gre** [comment]
I'm not aware of this bug. Is that happening on a specific device?

**Comment by joncursi** [comment]
Looks like it's only happening on the iOS sim. iPhone 7 running 10.2. Not noticeable on a physical device tho.

**Comment by gre** [comment]
ok, that's weird i never noticed it. that's hopeful it's not happening on device

thanks
