### ISSUE TITLE
how to avoid black edges formed after capturing. 

### ISSUE THREAD

**Issue by chaitanya71998** [gre/react-native-view-shot#526]
### Issue
getting black edges on the sides after capturing a view and sharing it.
Version:
Platform: IOS & Android

#### Expected behavior:
Need a image without black edges on horizontal sides

#### Actual behavior:
Getting black edges on left and right

![image](https://github.com/gre/react-native-view-shot/assets/46353549/dca83beb-2e10-4b5c-8cc4-bf46c91c5054)

#### Steps to reproduce the behavior
* create a view with size of 312x492, capture it under JPG format and share in any social media or save it you will observe black edges at horizontal sides

**Comment by chaitanya71998** [comment]
the captureRef is giving an image of size 1080x1355 and when i share it in any app its coming with black edges

**Comment by Mashirowww** [comment]
I also encountered this problem seems to have to manually cut by myself
