### ISSUE TITLE
Regression in 4.0.0-alpha.2

### ISSUE THREAD

**Issue by alanjhughes** [gre/react-native-view-shot#527]
### bug report
I believe #515 has caused a regression where all the snapshots are blank images. Reverting these changes restores the correct behaviour. 

#### Version & Platform
react-native-view-shot 4.0.0-alpha.2
react-native 0.74.0
iOS 17.4

**Platform:** 
iOS

#### Expected behavior

After reverting the change for #515 
![Simulator Screenshot - iPhone 15 Pro - 2024-04-24 at 11 05 11](https://github.com/gre/react-native-view-shot/assets/30924086/ae74da1d-4dab-4ffd-bdb6-af3825ab0f0f)

#### Actual behavior

The images are all blank
With the changes from #515 
![Simulator Screenshot - iPhone 15 Pro - 2024-04-24 at 11 06 57](https://github.com/gre/react-native-view-shot/assets/30924086/24d2bd51-6e51-43e4-a420-9b147257ba00)

#### Steps to reproduce the behavior
Run version `4.0.0-alpha.2` on RN `0.74.0`

**Comment by stevengoldberg** [comment]
Observed the same behavior in `4.0.0-alpha.3` with RN `0.74.1`.
