### ISSUE TITLE
WebView charts captures blank

### ISSUE THREAD

**Issue by Manweill** [gre/react-native-view-shot#53]
**webview source require this html,captures blank, in the react-native-view-shot-example project** @gre 
```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>ECharts</title>
  <!-- 引入 echarts.js -->
  <script src="http://cdn.bootcss.com/echarts/3.4.0/echarts.min.js"></script>
</head>

<body>
  <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
  <div id="main" style="width: 600px;height:400px;"></div>
  <script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));

    // 指定图表的配置项和数据
    var symbolSize = 20;
    var data = [[15, 0], [-50, 10], [-56.5, 20], [-46.5, 30], [-22.1, 40]];
    var points = [];

    option = {
      title: {
        text: 'Click to Add Points'
      },
      tooltip: {
        formatter: function (params) {
          var data = params.data || [0, 0];
          return data[0].toFixed(2) + ', ' + data[1].toFixed(2);
        }
      },
      grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
      },
      xAxis: {
        min: -60,
        max: 20,
        type: 'value',
        axisLine: { onZero: false }
      },
      yAxis: {
        min: 0,
        max: 40,
        type: 'value',
        axisLine: { onZero: false }
      },
      series: [
        {
          id: 'a',
          type: 'line',
          smooth: true,
          symbolSize: symbolSize,
          data: data
        }
      ]
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
  </script>
</body>

</html>
```

**Comment by manweill** [comment]
but, if move the webview element after `<View ref="form"></View>` , is not blank.
like this:
```
       <View
          ref="form"
          style={styles.form}>
          <View style={styles.btns}>
            <Btn label="😻 Reset" onPress={() => this.setState({ previewSource: catsSource })} />
            <Btn label="📷 Head Section" onPress={this.snapshot("header")} />
            <Btn label="📷 Form" onPress={this.snapshot("form")} />
            <Btn label="📷 Experimental Section" onPress={this.snapshot("complex")} />
            <Btn label="📷 All (ScrollView)" onPress={this.snapshot("full")} />
            <Btn label="📷 GL React" onPress={this.snapshot("gl")} />
            <Btn label="📷 MapView" onPress={this.snapshot("mapview")} />
            <Btn label="📷 WebView" onPress={this.snapshot("webview")} />
            <Btn label="📷 Video" onPress={this.snapshot("video")} />
            <Btn label="📷 Empty View (should crash)" onPress={this.snapshot("empty")} />
          </View>

          <View
            ref="webview"
            collapsable={false}
            style={{ width: 300, height: 500 }}>
            <WebView
              source={require('./assets/cavans.html')}
            />
          </View>
```

**Comment by oakis** [comment]
What platform are you developing on?

This is what it says in the docs:

> Android WebView:
> Only supported by wrapping a <View collapsable={false}> parent and snapshotting it.

**Comment by manweill** [comment]
is Android WebView. and, I thinks you don't mean what i say .  
use the WebView snapshot is work ,but the canvas is blank.

**Comment by gre** [comment]
as said in the README here https://github.com/gre/react-native-view-shot#interoperability-table

Android WebView is *Only supported by wrapping a <View collapsable={false}> parent and snapshotting it.*

for some reason directly attempting to snapshot the WebView won't work. to avoid this confusion, I might introduce that https://github.com/gre/react-native-view-shot/issues/48 so you don't have to think about this problem. What do you think?

**Comment by manweill** [comment]
@gre  yes ,is in <View collapsable={false}> .  maybe i expressions has worng.  i will fork react-native-view-shot-example and code the problem

**Comment by manweill** [comment]
@gre  see in https://github.com/manweill/react-native-view-shot-example

**Comment by gre** [comment]
I've tested your code in a WebView and I can successfully snapshot in Android so maybe this was recently fixed

<img width="473" alt="screen shot 2017-08-25 at 22 15 40" src="https://user-images.githubusercontent.com/211411/29731020-00bb65d8-89e3-11e7-81ff-32a91ea14cb2.png">

**Comment by Rice-M** [comment]
@Manweill Hi, how did you solve this, in my case some canvas in webview can not be captured

**Comment by gre** [comment]
are you sure the canvas is rendered at the time you capture it?

**Comment by Rice-M** [comment]
@gre  yes, I can see the rendered canvas in the srceen, bug when capture to img some canvas not shown

**Comment by Rice-M** [comment]
![wechatimg120](https://user-images.githubusercontent.com/6166502/33919752-645c06fc-dff5-11e7-8ad1-0ab0a7119561.jpeg)

![wechatimg121](https://user-images.githubusercontent.com/6166502/33919781-83ec9662-dff5-11e7-985a-10e0c2b28b04.jpeg)
You can see the img1 some section is blank

**Comment by Tomatoo** [comment]
solved？

**Comment by csfwff** [comment]
try to set android:hardwareAccelerated="false", it works.

**Comment by Grom-S** [comment]
I a have the same problem. Canvas in webview is blank. Setting android:hardwareAccelerated="false" works, but then you don't get the acceleration and the app is slow. 
Is there any other way to solve this issue?  @Rice-M how did you solved it?

**Comment by leonsimple** [comment]
hint https://developer.android.com/reference/android/view/PixelCopy

**Comment by salman-ar-sar** [comment]
Did anyone find a solution for this without setting android:hardwareAccelerated="false"? That is not a real solution right? 

I am facing this issue on Android only when capturing a view containing TradingView in a WebView.

@gre Please let me know if I am missing anything.
