### ISSUE TITLE
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by sandeshnaroju** [gre/react-native-view-shot#534]
it is not working in android 14, with new changes that happened in android 14. 

        const localUri = await captureRef(imageRef, {
            quality: 1,
        });

```
[Error: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts]
```
Kindly help me to fix this issue.

**Comment by haidarmy** [comment]
i got same problem, how do you fix it? @sandeshnaroju

**Comment by sandeshnaroju** [comment]
For me the issue was from share package module, not from this.
