### ISSUE TITLE
IOS debug error for RNViewShot.captureRef: Argument NSNumber has unspecified nullability 

### ISSUE THREAD

**Issue by holakmateusz** [gre/react-native-view-shot#547]
### bug report
IOS debug error for RNViewShot.captureRef: Argument NSNumber has unspecified nullability 

#### Version & Platform
    "expo": "51.0.28",
    "react-native": "0.74.2",
    "react-native-view-shot": "^4.0.0",

**Platform:** iOS

#### Expected behavior
There is no red error in iOS debug mode

#### Actual behavior
It shows red error with LogBox as it shown below:
![IMG_0156](https://github.com/user-attachments/assets/df68021c-f074-4b06-9dd9-c149c867f5c0)

#### Steps to reproduce the behavior

1. invoke captureRef() in debug mode on iOS

**Comment by alehano** [comment]
Same issue here

**Comment by outaTiME** [comment]
Sadly, same here after updating to version 4.x

**Comment by DimaKogut** [comment]
Save here! version 4.x

**Comment by MehdiSv** [comment]
Same here

**Comment by keeganthomp** [comment]
+1

**Comment by tosettil-polimi** [comment]
same

**Comment by tosettil-polimi** [comment]
I opened a pull request for fixing this (see #549)

# Temporary Nullability Fix for react-native-view-shot

## Prerequisites
If `patch-package` is not installed:
```bash
yarn add patch-package -D
```

## Patch Steps
1. Open `node_modules/react-native-view-shot/ios/RNViewShot.mm`
2. Modify line 48 from:
   ```objc
   RCT_EXPORT_METHOD(captureRef:(NSNumber *)target
   ```
   to:
   ```objc
   RCT_EXPORT_METHOD(captureRef:(nonnull NSNumber *)target
   ```
3. Run patch command:
   ```bash
   yarn patch-package react-native-view-shot
   ```

## Recommended
- Keep an eye on library updates
- Remove patch when official fix is released

**Comment by Yusang-park** [comment]
It's now fixed on v.4.0.3

**Comment by ils-anwarshah** [comment]
upgrading to v.4.0.3 solved my problem
