### ISSUE TITLE
Support for ReactNativeART?

### ISSUE THREAD

**Issue by imarem** [gre/react-native-view-shot#57]
Hi,
Thanks for this good plugin.

Is there any way for this plugin to support the ReactNativeART library? Or do you have any plans to add this feature?

I would love to use it with a components like Surface, Shape, Path from ReactNativeART.

Thanks for advance.

**Comment by gre** [comment]
oh it does not work? what happen?

**Comment by imarem** [comment]
Hi @gre 

I'm running on Android, and I'm using something similar to react-native-circular-progress wrapped in a view with collapsable={false}. Everthing is snapshoted correctly except my Surface, Path, Shape, etc components.

If you want to see an example, you can try something similar to the following code, (assuming you use the plugin react-native-circular-progress):

<View ref="content" collapsable={false} style={styles.container}  >
    <AnimatedCircularProgress
                            ref='hour'
                            size={300}
                            width={16}
                            fill={100}
                            tintColor="rgb(47,59,118)"
                            backgroundColor="rgba(47,59,118, 0.2)"
                            prefill={60}
                            rotation={360}
                            linecap={'round'}>
       </AnimatedCircularProgress>
</View>

The component AnimatedCircularProgress it's basicaly a View wrapping a Surface with specifically paths.

If you have any idea where I can look to fix the problem, or put some light in my case, I would greatly appreciate it!

Thanks!

**Comment by gre** [comment]
it appears that the android ArtSurfaceView is backed by TextureView https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/art/ARTSurfaceView.java

TextureView might not be supported by the library at the moment, but maybe we can see if we can `instanceof` the view to detect a TextureView and call the getBitmap method.. https://developer.android.com/reference/android/view/TextureView.html

I won't be able to work on that in a while, but if you want to work on that and send a PR i can merge it fast

**Comment by vegmorse** [comment]
I have the same problem. Is there any plan to include this feature? Or could you tell me where to look to capture TextureView?

Thank you!!

**Comment by gre** [comment]
Please check this again as we've merged https://github.com/gre/react-native-view-shot/pull/84
it might not be perfect yet but we can iterate on improving this :)

**Comment by imarem** [comment]
Thanks a lot! Will try it!!

**Comment by gre** [comment]
if you want you might want to help out of this topic too -> https://github.com/gre/react-native-view-shot/pull/84#issuecomment-324864690

basically there might be some offset issues, but it's probably solvable

**Comment by imarem** [comment]
Hi @gre 

Thanks for the improvement in the plugin, there are still some details regarding the position of the children between Surface component. But I have already been able to adapt my code to work correctly.

If you want to close the issue, and thanks again !!

**Comment by gre** [comment]
i'm going to create another issue for the position issue

**Comment by HenleyKuang** [comment]
Hi, I had the same issue as you while using react-native-progress circle graph but solved it with this change: https://github.com/gre/react-native-view-shot/pull/153

Hope it helps :)
