### ISSUE TITLE
Image real path to save it to camera roll

### ISSUE THREAD

**Issue by valentinancy** [gre/react-native-view-shot#58]
I was tried the example code and i got a uri like this:
file:///data/user/0/com.last/cache/ReactNative-snapshot-image1446502249.png

**Is there any way to change the uri into the real path?** just like:
"/storage/emulated/0/Pictures/ReactNative-snapshot-image799473449.png"

so i could use the path for the CameraRoll library from react native like:
CameraRoll.saveToCameraRoll(path,'photo')

Thanks and please help hehe

**Comment by gre** [comment]
have you tried using the `path` option ? https://github.com/gre/react-native-view-shot#dirs-constants

**Comment by valentinancy** [comment]
Oh ya you right! Thanks and sorry i was miss reading your documentation. But i got another problem here.
I was trying to make an application that could choose a frame to put on an image. I used _state_ to change the current frame, then after the user choosed the frame i was planning to use your plugin to screenshot that view and save it to camera roll. By your answer before, i was able to save it to camera roll. But the problem is that it was only screenshot the image without the frame on it. I don't know where i miss. Here is  my code: (by the way should I ask this question in another issue with the right title?)
`
import Icon from 'react-native-vector-icons/FontAwesome';
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Image,
  Button,
  Alert,
  ScrollView,
  ListView,
  TouchableOpacity,
  CameraRoll
} from 'react-native';

import { Column as Col, Row } from 'react-native-flexbox-grid';
import ImagePicker from 'react-native-image-picker';
import { takeSnapshot, dirs } from 'react-native-view-shot'
import RNGRP from 'react-native-get-real-path'

const { CacheDir, DocumentDir, MainBundleDir, MovieDir, MusicDir, PictureDir } = dirs;

import styles from './../../assets/styles/Style'

class EditPhoto extends Component {
  constructor(){
    super();
    this.state = {
      frame:null,
      choosenFrame: null
    }
  }

  showFrame() {
    if(!this.state.choosenFrame) {
      return(
        <View style={styles.emptyView}>
          <Image style={styles.empty} source={require('./../../assets/images/sub-header-photo.png')}/>
        </View>
      )
    }
    return(
      <View style={styles.choosenFrameView}>
        <Image style={styles.choosenFrame} source={this.state.choosenFrame}/>
      </View>
    )
  }

  setChoosenFrame(e, frame) {
    this.setState({
      choosenFrame: frame
    })
  }

  snapshot = refname => () => 
    takeSnapshot(this.refs[refname], {
      format: "png",
      quality: 0.9,
      result: "file",
      snapshotContentContainer: false,
      path: PictureDir+"/foo.png"
      })
    .then(
      uri => {
        console.log(" isi uri ", uri)
        CameraRoll.saveToCameraRoll(uri,'photo').then(function(result) {
          console.log('saved ' + result);
        }).catch(function(error) {
          console.log('error ' + error);
        });

        this.uploadImage(uri)
    },
      error => console.error("Oops, snapshot failed", error)
    );
        

    uploadImage(image) {
      let formData = new FormData();
      formData.append('photo', image);
      fetch('http://test/photos/upload.json', {
        method:'POST',
         body: formData
      })
    }

  render() {
    return (
      <ScrollView>
        <Image source={require('./../../assets/images/sub-header-photo.png')} style={styles.headlineImage} >
          <View style={styles.backdropView}>
            <Text style={styles.teammateHeadline}>TEAMMATE PHOTOS</Text>
          </View>
        </Image>

        <View>
          <View style={styles.choosenImageView} collapsable={false} ref="header">
            <Image source={{uri: this.props.asd}} style={styles.choosenImage} resizeMode='cover'/>
          </View>
          { this.showFrame() }

        <View style={styles.frameGroup}>
            <Row size={10} nowrap>
                  <Col sm={2} md={2} lg={2}>
                    <TouchableOpacity onPress={(e) => this.setChoosenFrame(e,require('./../../assets/images/frame01.png')) }>
                      <View style={styles.frameImageView}>
                        <Image
                          style={ styles.frameImage }
                          source={require('./../../assets/images/frame01.png')}
                        />
                      </View>
                    </TouchableOpacity>
                  </Col>
                  <Col sm={2} md={2} lg={2}>
                    <TouchableOpacity onPress={(e) => this.setChoosenFrame(e,require('./../../assets/images/frame02.png')) }>
                      <View style={styles.frameImageView}>
                        <Image
                          style={ styles.frameImage }
                          source={require('./../../assets/images/frame02.png')}
                        />
                      </View>
                    </TouchableOpacity>
                  </Col>
                  <Col sm={2} md={2} lg={2}>
                    <TouchableOpacity onPress={(e) => this.setChoosenFrame(e,require('./../../assets/images/frame03.png')) }>
                      <View style={styles.frameImageView}>
                        <Image
                          style={ styles.frameImage }
                          source={require('./../../assets/images/frame03.png')}
                        />
                      </View>
                    </TouchableOpacity>
                  </Col>
                  <Col sm={2} md={2} lg={2}>
                    <TouchableOpacity onPress={(e) => this.setChoosenFrame(e,require('./../../assets/images/frame04.png')) }>
                      <View style={styles.frameImageView}>
                        <Image
                          style={ styles.frameImage }
                          source={require('./../../assets/images/frame04.png')}
                        />
                      </View>
                    </TouchableOpacity>
                  </Col>
                  <Col sm={2} md={2} lg={2}>
                    <TouchableOpacity onPress={(e) => this.setChoosenFrame(e,require('./../../assets/images/frame05.png')) }>
                      <View style={styles.frameImageView}>
                        <Image
                          style={ styles.frameImage }
                          source={require('./../../assets/images/frame05.png')}
                        />
                      </View>
                    </TouchableOpacity>
                  </Col>
              </Row>
            </View>
        </View>
        <View style={styles.bStyle}>
          <Button
            color= "red"
            onPress={this.snapshot("header")}
            title="Submit"
          />
        </View>
        <View style={styles.bStyle}>
          <Button
            color= "red"
            onPress={sharePhoto}
            title="Share"
          />
        </View>
      </ScrollView>
    );
  }
}

const uploadPhoto = () => {
  Alert.alert('Button has been pressed!');
};

const sharePhoto = () => {
  Alert.alert('Button has been pressed!');
};

export default EditPhoto`

**Comment by parasher25** [comment]
> I was tried the example code and i got a uri like this:
> file:///data/user/0/com.last/cache/ReactNative-snapshot-image1446502249.png
> 
> **Is there any way to change the uri into the real path?** just like:
> "/storage/emulated/0/Pictures/ReactNative-snapshot-image799473449.png"
> 
> so i could use the path for the CameraRoll library from react native like:
> CameraRoll.saveToCameraRoll(path,'photo')
> 
> Thanks and please help hehe

How did you solve this?
I am facing the same issue, please help!
