### ISSUE TITLE
Image could not show on photo ,but showed in file

### ISSUE THREAD

**Issue by aqnaruto** [gre/react-native-view-shot#61]
i mean if you save image into path: DCIM/Camera , 
the image file could find in [file manager],but not showed in system photo application 

> device info  android
oppo r9
xiaomi 4 5

**Comment by gre** [comment]
have you tried to use `dirs.PictureDir` ?

according to some answers on http://stackoverflow.com/questions/8560501/android-save-image-into-gallery to save into gallery should be android's `Environment.DIRECTORY_PICTURES ` which is exposed by the lib in dirs.PictureDir with this code: https://github.com/gre/react-native-view-shot/blob/36c8271be46521175002b08f9c9ae919ae7b17e8/android/src/main/java/fr/greweb/reactnativeviewshot/RNViewShotModule.java#L144

**Comment by aqnaruto** [comment]
i am  very gratefull to recieve your reply,  i have allready tried use dirs.PicturesDir , and DcimDir ，if you use origin-android-system , image in those Dir is abled to be finded in gallery 。 but if you  use customization-android-system  ,such as xiaomi,oppo,huawei,lenovo ,it is can't , it lead to if user  use other app such as weichat or facebook and so on,they can't find the image they have captured.

**Comment by gre** [comment]
I'm not sure to know the answer :'( 
maybe the customization-android-system use another path?

**Comment by aqnaruto** [comment]
i checked those picture,it is in the same path。but not showed，it is seems customization-android-system have traced the Image url  when take a photo or take a screenshot or save a picture 。and only show picture is traced

**Comment by aqnaruto** [comment]
![image](https://cloud.githubusercontent.com/assets/9067159/25566240/c4395dae-2e07-11e7-9376-88352d1b0dff.png)
here is a sample , i use wechat, wechat could display the image i have save from browser or screenshot just now。but, not showed if i use  react-native-view-shot,  and they are in the same path.

**Comment by gre** [comment]
maybe they rely on the filename? (like the DCIM number) or maybe they rely on a given extension?
(have you tried JPG vs PNG ?)

**Comment by aqnaruto** [comment]
@gre,yeah,i have tried, i tried different filename and quality, even the same file name is still not show。

and a search from net it seems,when save image neet to notice system ,to let system know galery is updated.

code like this
`Intent intent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
Uri uri = Uri.fromFile(file);
intent.setData(uri);
context.sendBroadcast(intent);//
`

**Comment by gre** [comment]
do you want to try that and provide a PR if this works?

**Comment by aqnaruto** [comment]
i don't know the real reason,i am not a android developer,i just search from the net. it is a difficult work for me ,but i think i will spend time to figure it out  ...

**Comment by aqnaruto** [comment]
now it 3:00 clock beijing time ,i need to go sleep.i will try it tomorrow . i think this is solution ,it is in stackoverflow,the link you give me 

http://stackoverflow.com/questions/8560501/android-save-image-into-gallery

![image](https://cloud.githubusercontent.com/assets/9067159/25567121/792693a6-2e19-11e7-9bc7-6423fc5b3b4e.png)

**Comment by aqnaruto** [comment]
hey,dear @gre , i have tryed and suceed by add this,work perfectly
![image](https://cloud.githubusercontent.com/assets/9067159/25779512/9e9d4822-334c-11e7-8f6d-358420dc6250.png)

**Comment by gre** [comment]
oh! cool :) would you like to create a PR ?

**Comment by aqnaruto** [comment]
thank you ,but ,what is pr?@gre

**Comment by gre** [comment]
sorry, a Pull Request, on Github

**Comment by gre** [comment]
see PR https://github.com/gre/react-native-view-shot/pull/62#issuecomment-303346134

in short: a better solution is to use CameraRoll.saveToCameraRoll and we will deprecate use of path in this library
