### ISSUE TITLE
'Oops, snapshot failed', { [Error: Failed to snapshot view tag 296] framesToPop: 1, code: 'E_UNABLE_TO_SNAPSHOT' }

### ISSUE THREAD

**Issue by imbudhiraja** [gre/react-native-view-shot#64]
Hi I'm facing this issue on Samsung Galaxy 7 and Moto G3. Please let me know whats wrong with this.

**Comment by gre** [comment]
do you have an example that reproduce the problem?

**Comment by imbudhiraja** [comment]
Yes Here find the sample code. 


<View collapsable={false} style={[styles.topLevelView,CommonStyle.setElevation]}>
  <View collapsable={false} style={this.state.visible?{backgroundColor:"#fff"}:{}} ref= {'snap'+rowdata._id}>
    <View style={{flexDirection:'row',marginVertical:(Screen.width/100)*4,
      backgroundColor: '#fff'}}>
      <TouchableHighlight
        underlayColor = "transparent" >  
        <Image style={styles.profileIcon}
          source={{uri: "google.com/images.png"}}
        />   
      </TouchableHighlight>           
    </View>
  </View>

  <View style={{marginHorizontal:(Screen.width/100)*1.5,
    backgroundColor: 'transparent',
    borderTopWidth:1,
    borderColor:"#C0C0C0",
    marginTop:(Screen.height/100)*-1,
    paddingVertical:(Screen.height/100)*1.3,
    alignItems:"center"
      }} >
    <TouchableHighlight style={{position:'absolute',
      left:(Screen.width/100)*20,
      alignItems: 'center',
      height:(Screen.width/100)*15,
      width:(Screen.width/100)*20,}}
      underlayColor = "transparent" 
      onPress={()=>this.socialMediaShare(rowdata)}>
        <Image
          style={[CommonStyle.message_board_bottom_icons,{marginTop:7,
          width:(Screen.width/100)*7.2,height:(Screen.width/100)*7.22,}]}
          source={share_icon} 
        />
    </TouchableHighlight> 
  </View>
</View>

**Comment by gre** [comment]
Where is your ref set?

is it on a View, if so, have you tried to set `collapsable={false}` on it?

**Comment by imbudhiraja** [comment]
@gre ref id is set to view and view is set to collapsable={false}.

**Comment by the747j** [comment]
I have the same problem, i was usin expo sdk 50 an it was working, but when I changed to SDK 52 stops working.
its a reali big prblem for mi now becouse the app need that function y we need to release 🫥

**Comment by the747j** [comment]
this is my app.json
{
  "expo": {
     . . .
    "android": {
      "permissions": [
        "CAMERA",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE",
        "ACCESS_MEDIA_LOCATION"
      ]
   }
   . . .
}

**Comment by the747j** [comment]
react-native-view-shot\android\src\main\java\fr\greweb\reactnativeviewshot\ViewShot.java
line 232    ->   Log.e(TAG, "Failed to capture view snapshot", ex);
Something is happening there, but I don't know what it is.

**Comment by FabianJFR** [comment]
I have the same problem. Do you know if there is any update to the library or any component that should be added? I've already tried all the options they mention and they haven't worked for me.

this is my code. I simplified it to just print the URL

import ViewShot, { captureRef } from "react-native-view-shot";
const receiptRef = useRef(null);
const handleCapture = async () => {
    if (!receiptRef.current) {
      console.error('Referencia no existe');
      return;
    }
    try {
      const uri = await captureRef(receiptRef.current);
      console.log('Captura:', uri);
    } catch (error) {
      console.error('Error:', error);
    }
    };
<Modal
        visible={recibo}
        transparent={true}  // Vuelve a true
        animationType="slide"
      >
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)' }}><TouchableOpacity
          onPress={() => compartirRecibo(imageURI)}
          style={styles.touchableIcon2}
        >
          <Icon
            reverse
            name="share-social-outline"
            type="ionicon"
            color="#387478"
            size={28}
            containerStyle={{ alignSelf: "flex-end" }}
            disabled={isButtonEnabled ? false : true}
          />
        </TouchableOpacity>

          <TouchableOpacity
            onPress={() => { setRecibo(false), navigation.goBack() }}
            style={styles.touchableIcon}
          >
            <Icon
              reverse
              name="close-outline"
              type="ionicon"
              color="#4A628A"
              size={28}
              containerStyle={{ alignSelf: "flex-end" }}
              disabled={isButtonEnabled ? false : true}
            />
          </TouchableOpacity>
          <View style={{ justifyContent: 'center', alignItems: 'center', backgroundColor: '#fff', width: "90%", height: "85%" }}>

            <Animated.Text
              style={{
                opacity: animation,
                transform: [
                  {
                    translateY: animation.interpolate({
                      inputRange: [0, 1],
                      outputRange: [0, 10]
                    })
                  }
                ],
                color: isButtonEnabled ? "#fff" : "#000"
              }}
            >
              GUARDANDO RECIBO...
            </Animated.Text>
            <View ref={receiptRef} collapsable={false} style={{
              position: 'relative',
              width: '95%',
              height: '90%',
              backgroundColor: '#fff',
              borderRadius: 30,
              margin: 10,
              zIndex: 2,
            }}>
              <Image resizeMode="contain" source={{
                uri: "https://firebasestorage.googleapis.com/v0/b/escuelas-235df.appspot.com/o/jfr.png?alt=media&token=9def21c0-223c-4f99-9a91-70dab1f147e2",
              }}
                style={{
                  width: 90,
                  height: 90,
                  alignSelf: "center",
                  marginTop: 10,
                  marginBottom: 10,
                  marginLeft: "35%"
                }} />
              <Divider />
              <View style={{
                backgroundColor: 'white',
                width: '90%',
                justifyContent: 'center',
              }}>

                <Text allowFontScaling={false} style={{ fontSize: 16, marginTop: 10, marginLeft: 20, }}>
                  <Text style={{ fontWeight: "bold" }} allowFontScaling={false}> Folio:</Text> {folio}
                </Text>

                <Text allowFontScaling={false} style={{ fontSize: 16, marginTop: 10, marginLeft: 20, }}>
                  <Text style={{ fontWeight: "bold" }} allowFontScaling={false}> Cajero:</Text> App p
                </Text>

                <Text allowFontScaling={false} style={{ fontSize: 16, marginTop: 10, marginLeft: 20, }}>
                  <Text style={{ fontWeight: "bold", }} allowFontScaling={false}> Matricula:</Text> {user.matricula}
                </Text>

                <Text allowFontScaling={false} style={{ fontSize: 16, marginTop: 10, marginLeft: 20, }}>
                  <Text style={{ fontWeight: "bold" }} allowFontScaling={false}> Grupo:</Text> {user.grado} {user.nivelEscolar} {user.grupo}
                </Text>

                <Text allowFontScaling={false} style={{ fontSize: 16, marginTop: 10, marginLeft: 20, }}>
                  <Text style={{ fontWeight: "bold" }} allowFontScaling={false}> Alumno:</Text> {nombre}
                </Text>

                <Text allowFontScaling={false} style={{ fontSize: 16, marginTop: 10, marginLeft: 20, }}>
                  <Text style={{ fontWeight: "bold" }} allowFontScaling={false}> Referencia:</Text> {referencia}
                </Text>

                <Text allowFontScaling={false} style={{ fontSize: 16, marginTop: 10, marginLeft: 20, }}>
                  <Text style={{ fontWeight: "bold" }} allowFontScaling={false}> Forma de pago:</Text> Tarjeta de credito/debito
                </Text>

                <Text allowFontScaling={false} style={{ fontSize: 16, marginTop: 10, marginLeft: 20, }}>
                  <Text style={{ fontWeight: "bold" }} allowFontScaling={false}> Caja o Banco:</Text> Aplicación
                </Text>
              </View>
              <View style={styles.containerTable}>
                <View style={styles.header}>
                  <Text style={styles.headerCell} allowFontScaling={false}>Cant.</Text>
                  <Text style={styles.headerCell} allowFontScaling={false}>Descrip.</Text>
                  <Text style={styles.headerCell} allowFontScaling={false}>Único</Text>
                  <Text style={styles.headerCell} allowFontScaling={false}>Importe</Text>
                </View>
                <View style={styles.row}>
                  <Text style={styles.cell} allowFontScaling={false}>1</Text>
                  <Text style={styles.cell} allowFontScaling={false}>{colegiatura.concepto}</Text>
                  <Text style={styles.cell} allowFontScaling={false}>{amount}</Text>
                  <Text style={styles.cell} allowFontScaling={false}>${amount}.00</Text>
                </View>
                <View style={styles.totalRow}>
                  <IntlProvider locale="es-MX">
                    <Text style={styles.txtCantidad} allowFontScaling={false}>
                      <FormattedNumber
                        value={amount}
                        style="currency"
                        currency="MXN"
                      />
                    </Text>
                  </IntlProvider>
                </View>

                <Text style={{ fontSize: 16, marginTop: 5, marginLeft: 20, }} allowFontScaling={false}>RFC: IJF110217AN5</Text>

                <Text style={{ fontSize: 16, marginTop: 10, marginLeft: 20, }} allowFontScaling={false}>4461466076</Text>

                <Text style={{ fontSize: 16, marginTop: 10, marginLeft: 20, }} allowFontScaling={false}>pagos@institutojfr.edu.mx</Text>
              </View>
            </View>
          </View>
        </View>
      </Modal>

**Comment by tkud04** [comment]
This fixed it for me: https://github.com/gre/react-native-view-shot/issues/555#issue-2792705792
