### ISSUE TITLE
Custom width height of snapshot

### ISSUE THREAD

**Issue by trangcongthanh** [gre/react-native-view-shot#65]
How can I custom size of Image file after take snapshot? I tested on iPhone 6 simulator, file result only have 750px width.

Example: I wanna result file have 2048x2048 px.

**Comment by gre** [comment]
there are width and height option in the library but this is doing a bitmap scaling. so if you scale things up, it will be all blurry.

What you can do however is to generate a `<View>` that will be a 2048x2048 view and snapshot it.

to generate such a view, you basically need to:

`style={{ width: 2048 / PixelRatio.get(), height: 2048 / PixelRatio.get() }}`
