### ISSUE TITLE
drop the "path" option support

### ISSUE THREAD

**Issue by gre** [gre/react-native-view-shot#67]
following up of https://github.com/gre/react-native-view-shot/issues/66#issuecomment-303322276 / https://github.com/gre/react-native-view-shot/pull/62#issuecomment-303346134
need to deprecate "path" and release a major that drop it.

for moving files, use react-native-fs or CameraRoll.saveToCameraRoll

**Comment by brentvatne** [comment]
:+1: makes sense to deprecate it to me

**Comment by gre** [comment]
at the same time, we should rename "file" to "tmpfile" to make it clear this is not going to be kept very long.
that way we can also deprecate any usage of that "file" at same time of "path"

**Comment by gre** [comment]
fixed in v2
