### ISSUE TITLE
(Android) Trying to resolve view with tag which doesn't exist

### ISSUE THREAD

**Issue by mooqoo** [gre/react-native-view-shot#7]
I'm getting this issue if my view reference did not specify a backgroundColor.

so the code works fine if I take a Snapshot with the below viewRef

```
<View   
  style={{backgroundColor: 'yellow'}}   
  ref={ref => viewRefSuccess = ref}>   
  <Text>   
    Hello View Snap Shot   
  </Text>   
</View>   
```

However it will crash with the "Trying to resolve view with tag 'tagID' which doesn't exist"
if I remove the backgroundColor props.

```
<View ref={ref => viewRefSuccess = ref}>   
  <Text>   
    Hello View Snap Shot   
  </Text>   
</View>   
```

Any thought on why this is happening?

Thanks.

**Comment by gre** [comment]
Android or iOS?

**Comment by mooqoo** [comment]
on Android

**Comment by gre** [comment]
it might be a bug in React Native then, that if an element don't have a style, it's not even in the resolveView list..
For now, you will have to provide a style I guess.

**Comment by gaguirre** [comment]
Probably related to the [collapsable property](http://facebook.github.io/react-native/releases/0.32/docs/view.html#collapsable) for Android Views.
Setting it to **false** could fix the problem.

**Comment by gre** [comment]
view is somehow virtual (don't mirror a real UI View underneath) if you use that property, so it makes sense that resolveView don't work in that case, it's not a bug on RN then.

**Comment by gre** [comment]
I'll add a note in README

**Comment by faxioman** [comment]
I'm not able to fix this issue.
I'm trying to take a screenshot for the main navigator ... setting collapsable on the navigator component or on his parent doesn't solve the issue. Some ideas?

**Comment by faxioman** [comment]
Resolved passing a reference of the view which contains the main navigator.

**Comment by gre** [comment]
yeah, because `<Navigator>` does not have a UIView representation in the native side, it really needs to be on a View / Image / anything that you are sure that a 'native ui view' will exists

**Comment by manivannan-mp** [comment]
Resolved by adding collapsable={false} to view

`<View
 collapsable={false}
  style={{backgroundColor: 'yellow'}}   
  ref={ref => viewRefSuccess = ref}> 
  <Text>   
    Hello View Snap Shot   
  </Text>   
</View>`

**Comment by rameshvishnoi90904** [comment]
> Resolved by adding collapsable={false} to view
> 
> `<View collapsable={false} style={{backgroundColor: 'yellow'}} ref={ref => viewRefSuccess = ref}> <Text> Hello View Snap Shot </Text> </View>`

Still works

**Comment by hanancs** [comment]
Thanks

**Comment by hanancs** [comment]
> Resolved by adding collapsable={false} to view
> 
> `<View collapsable={false} style={{backgroundColor: 'yellow'}} ref={ref => viewRefSuccess = ref}> <Text> Hello View Snap Shot </Text> </View>`

Thanks  @manivannan-mp

**Comment by yaser-elbatal** [comment]
> Resolved by adding collapsable={false} to view
> 
> `<View collapsable={false} style={{backgroundColor: 'yellow'}} ref={ref => viewRefSuccess = ref}> <Text> Hello View Snap Shot </Text> </View>`

when add ref To View 
give error
Oops, snapshot failed [Error: Failed to capture view snapshot]

**Comment by dev-alix** [comment]
> Resolved by adding collapsable={false} to view
> 
> `<View collapsable={false} style={{backgroundColor: 'yellow'}} ref={ref => viewRefSuccess = ref}> <Text> Hello View Snap Shot </Text> </View>`

Yeah it's working for me 

"react-native": "0.70.5",
"react-native-view-shot": "^3.5.0",

thanks

**Comment by nijarv** [comment]
Still getting same error

**Comment by Ronaldo-Kadenasty** [comment]
> Resolved by adding collapsable={false} to view
> 
> `<View collapsable={false} style={{backgroundColor: 'yellow'}} ref={ref => viewRefSuccess = ref}> <Text> Hello View Snap Shot </Text> </View>`

Still working thanks !!

**Comment by camboYY** [comment]
not working
