### ISSUE TITLE
ios 11 bug around taking screenshots.

### ISSUE THREAD

**Issue by myusuf3** [gre/react-native-view-shot#71]
![image](https://user-images.githubusercontent.com/156825/26938787-3c08f232-4c43-11e7-99c8-eaf291093c35.png)

**Comment by myusuf3** [comment]
Might be underlying issue with react native but heads up.

**Comment by gre** [comment]
What are you screenshoting? There are specific limitations on not being able to screenshot things like glkviews, videoview,..

**Comment by myusuf3** [comment]
Its not a video view but a simple webview we have alway been able to do.

**Comment by segalr3** [comment]
i have the same issue

**Comment by gre** [comment]
In react-native-view-shot-example the snapshotting of WebView works successfully (where the webview url is set to this repo itself)

mind sharing an URL that reproduce the bug?

**Comment by ER1011** [comment]
We have this issue in iOS 10 using captureScreen when trying to take a screenshot (not a viewshot) in the presence of a paused video. Has anybody encountered this?

**Comment by gre** [comment]
can't really investigate without a reproducible example. please provide & we can reopen
