### ISSUE TITLE
Snapshotting a View right after it gets rendered fails

### ISSUE THREAD

**Issue by vicmpen** [gre/react-native-view-shot#74]
Hello and thanks for the module!

I had since January the following code 
```
<View  **ref='sig'**
    collapsable = {false} 
    style={{flex:1,backgroundColor:'white', 
        marginTop:70,paddingLeft:5,paddingRight:5,paddingBottom:5}}>
    <View  collapsable = {false} style={{flex:1,backgroundColor:'white'}}>
        {this.renderText()}
         <Image style = {{flex:5}} source={{uri: this.state.base64, scale: 3}}/>
    </View>
</View>
```

and it was working properly, ie it took a snapshot of the top view (ref == sig) and its children.

After Updating to RN 0.41 and to react-native-view-shot  v1.9.1 this was no longer working and i had to move the ref down to the actual view that i wanted to snapshot.

```
<View
    collapsable = {false} 
    style={{flex:1,backgroundColor:'white', 
        marginTop:70,paddingLeft:5,paddingRight:5,paddingBottom:5}}>
    <View  **ref='sig'**  collapsable = {false} style={{flex:1,backgroundColor:'white'}}>
        {this.renderText()}
         <Image style = {{flex:5}} source={{uri: this.state.base64, scale: 3}}/>
    </View>
</View>
```

Is this an intentional change?

**Comment by gre** [comment]
mmh I'm not sure what could have potentially changed but i don't think there should be a regression around this. Maybe something changed in React Native side?
have you tried to keep using the same previous react-native-view-shot version?

**Comment by vicmpen** [comment]
Yeah, i will try it and let you know. Thanks for the fast response!

**Comment by vicmpen** [comment]
Well, my initial comment was wrong. There is no problem with the ref, or the children of a view. Let me provide you with some more context.

What i want to snapshot is a signature drawn on the screen. The user draws it on the designated space and then, when pressing a button, i assign the base64 signature to an <Image/>, and immediately snapshot that image.

Before RN41, or RN-view-shot 1.9.1 there was no problem doing that. After updating, i cannot get the view. If i call the snapshot method at the setState() callback, the image is blank.

What works is setting a timeout on the setState callback of > 1000 ms that works. 

Any ideas?

**Comment by gre** [comment]
have you tried waiting the Image to be loaded? hook a onLoad on Image and only do the snapshot at that time.
even if the image is a base64 (and that there is no network involved here) i'm not sure that RN will draw it in sync (I'm pretty sure it does the decoding in async in another thread)

**Comment by vicmpen** [comment]
Ahh, the onLoad, ofc.

This should do it, although it is still weird that it was working 100% in the previous set up. I will give it a try and close it. Probably it is an internal RN change, nothing wrong with the module.

Thanks again for the help!
