### ISSUE TITLE
Error: The content size must not be zero or negative. Got: (0, 0)

### ISSUE THREAD

**Issue by MiLeung** [gre/react-native-view-shot#77]
RN version 0.46.4

Just using the example provided in the docs. 

```
  takeSnapshot(this.cam, {
      // format: 'jpeg',
      // // result: 'base64',
      // quality: 0.8,
      // height: width,
      // width: width
    })
    .then(
      uri => console.log("Image saved to", uri),
      error => console.error("Oops, snapshot failed", error)
    );
```

**Comment by MiLeung** [comment]
The issue was that I was calling takeSnapshot onComponentDidMount. Had to delay this call with setTimeout for it to work

**Comment by gre** [comment]
maybe you should hook to `onLayout` that happens a tiny bit after the mount. also be aware onLayout is likely to be called many times (i think each time layout changes)
