### ISSUE TITLE
The android webview loads the screenshots of the map black

### ISSUE THREAD

**Issue by Muriel0603** [gre/react-native-view-shot#83]

**Comment by gre** [comment]
which map?  the map of react-native-maps ? see also https://github.com/gre/react-native-view-shot#interoperability-table

**Comment by Muriel0603** [comment]
No,weiview's own map.

**Comment by Muriel0603** [comment]
There's no problem with ios, and the map doesn't show up on android screenshots

**Comment by gre** [comment]
what is WebView's map? 🤔 

Android is overall more limited when it comes to snapshotting and it might be a limitation. have you tried wrapping a `collapsable` `View` like in the readme?

**Comment by Muriel0603** [comment]
I'm used amap in webview.I added the < View collapsable = {false} > property,but it doesn't work

**Comment by gre** [comment]
I'm not sure what's wrong for you but in the react-native-view-shot-example , I can successfully snapshot a WebView:

![screenshot_20170825-105329](https://user-images.githubusercontent.com/211411/29707119-75b89f36-8984-11e7-998e-759e74422635.png)
