### ISSUE TITLE
View shot of camera view renders a black image

### ISSUE THREAD

**Issue by Progoogler** [gre/react-native-view-shot#85]
I'm currently using a derivative of React-Native-Camera that doesn't have a capture functionality. So in order to "capture" the image of the camera, I'm attempting to utilize React-Native-View-Shot. However, despite successfully returning the promise with the uri, the saved view shot renders a black image. Is this behavior normal for camera views?

I've tried taking the view shot from `<View collapsable={false} ref="this.cameraView">` and from the `<Camera ref="this.cameraView">` to no avail. Does anyone have another suggestion which I may attempt?

Unfortunately, using a different camera library which does support capture is not an option. :(

**Comment by Progoogler** [comment]
I ended up switching between the non-capturing camera view and React-Native-Camera using state in order to get the shot.

**Comment by gre** [comment]
Yeah I think camera as well as videoviews and glkviews is going to produce a black result (and not sure if this can be solved).
