### ISSUE TITLE
[Android] TextureViews positionning issues

### ISSUE THREAD

**Issue by gre** [gre/react-native-view-shot#86]
following up https://github.com/gre/react-native-view-shot/pull/84#issuecomment-324864690
(for android) there is a beginning of supporting snapshotting TextureViews but it does not yet position them correctly, we need to accumulate the position offset somehow

**Comment by jayesbe** [comment]
Looked at #84 and #57 and this issue is still happening with the latest 2.1.1

@gre is there a particular section of the code I can look at, I have a couple days I would like to try and resolve this.
