### ISSUE TITLE
svgIcon

### ISSUE THREAD

**Issue by TryImpossible** [gre/react-native-view-shot#90]
Can't capture svgicon. this svg that  i use 'react-native-svg-uri' in github

**Comment by gre** [comment]
Hi, thanks for the issue. could you give more detail?

like:
- which platform
- what actually happen? black result or it just throw an exception?
- any code to show the bug?

**Comment by gre** [comment]
- if it's a bug related to react-native-svg, a good start will be to implement an example in the example app so we can replicate it (therefore i've created https://github.com/gre/react-native-view-shot/issues/97 – let's work on this first. and optionally attempt a fix. **feel free to provide a new PR** )
- my other guess is that, with the -uri lib, you probably need to wait the svg is loaded & rendered, have you done that? The lib don't offer any way to do so, so i've created https://github.com/matc4/react-native-svg-uri/issues/79 . if this is the bug, then it will be up to you to hook to onLoad.

**Comment by gre** [comment]
I've just pushed an example that successful can snapshot a SVG. both on iOS and Android. so the bug must be on your side.

**Comment by TryImpossible** [comment]
thank you very much!

**Comment by gre** [comment]
BTW i've sent https://github.com/matc4/react-native-svg-uri/pull/80
