### ISSUE TITLE
Error height incomplete Image

### ISSUE THREAD

**Issue by herel** [gre/react-native-view-shot#91]
** render device **

![screen](https://user-images.githubusercontent.com/416115/29798161-000bf680-8c21-11e7-9eba-22e6ad52bf51.png)

**My code**
![captura de pantalla 2017-08-28 a la s 18 41 58](https://user-images.githubusercontent.com/416115/29798108-9dfde3a4-8c20-11e7-966f-d3a1c38401ba.png)

**Result Image**
![captura de pantalla 2017-08-28 a la s 18 39 00](https://user-images.githubusercontent.com/416115/29798047-35896762-8c20-11e7-91c4-3eba565fa10d.png)

Any suggestion?

**Comment by herel** [comment]
Fixed  :D 

change in RNViewShotModule.java

 File externalCacheDir = context.getExternalCacheDir();
        File internalCacheDir = context.getCacheDir();

to 

File externalCacheDir = context.getExternalCacheDir();
File internalCacheDir = context.getExternalCacheDir();


Switch to an accessible directory or 
He seems to be running out of memory

![screen](https://user-images.githubusercontent.com/416115/29798982-264785f8-8c26-11e7-825b-f4fc257ae0af.png)

**Comment by gre** [comment]
not sure what we can do better than current approach (which should chose the best available space)
