### ISSUE TITLE
NativeModules.RNViewShot is undefined

### ISSUE THREAD

**Issue by GH974** [gre/react-native-view-shot#94]
### feature request
NativeModules.RNViewShot is undefined. Make sure the library is linked on the native side.

#### Version & Platform
latest on github

**Platform:** Android

REACT-NATIVE V0.47

###############
I have use command npm install react-native-view-shot --save
and after install i try react-native link react-native-view-shot

**Comment by GH974** [comment]
I found this bug, I have solved this In /android/app/src/main/java/com/[appName]/MainApplication.java

is missing this "new RNViewShotPackage()"

**Comment by sidferreira** [comment]
Having this on iOS

**Comment by gre** [comment]
it means you have not linked the library properly in xcode

**Comment by sidferreira** [comment]
Sorry the delay @gre but indeed the `react-native link` wasn't working and I had to do it manually

**Comment by tanvirshajahan4** [comment]
i was having issue on android only, ios was working.
I fixed it by run the project on Android Studio. then run gradle i found that react-native-view-shot is using AndroidX. and i was using Android.. so i change the library imports which has androidx to android

eg: import androidx.annotation.NonNull;
import android.support.annotation.NonNull; <- use this

hope this help..

**Comment by diatche** [comment]
I had this issue on iOS, where auto linking was not happening, manually linking also didn't work. Turns out the `react-native-view-shot` dependency ended up in `optionalDependencies` in `package.json`. Moving the dependency to `dependencies` solved the issue and auto linking started to work.
