### ISSUE TITLE
reactNativeViewShot.takeSnapshot is not a function   

### ISSUE THREAD

**Issue by Jallynme** [gre/react-native-view-shot#95]
I downloaded the demo project seem like the takeSnapshot function doesn't work anymore 

is show like (0,_reactNativeViewShot.takeSnapshot) is not a function. 
  show like (0,_reactNativeViewShot.takeSnapshot)  is undefined

<img src="http://imageshack.com/a/img924/4674/kurRBI.png">

**Comment by caihc001** [comment]
Hi, I meet the same problem. Have you found a solution yet?

**Comment by gre** [comment]
sorry for that, the example was outdated. you can now find it in the example folder of this repo

https://github.com/gre/react-native-view-shot/tree/master/example

**Comment by crpeter** [comment]
Does the project need to be ejected for this to work?

**Comment by gre** [comment]
for Expo, you can directly use https://docs.expo.io/versions/v27.0.0/sdk/take-snapshot-async#__next because i think the embed native library is outdated
