### ISSUE TITLE
Cannot read property 'captureRef' of undefined

### ISSUE THREAD

**Issue by longpq18** [gre/react-native-view-shot#98]
I trying run here: https://github.com/gre/react-native-view-shot/blob/master/example/App.js
But not working, please tell me how to fix it, thank
My react-native version:
react-native-cli: 2.0.1
react-native: 0.47.1

**Comment by gre** [comment]
I just forked the project, CD-ed into example , run yarn, opened xcode, run it to the simulator, and it worked.

so i'm not sure what's going on but the error sounds like a linking problem. if on iOS, make sure this appears:

<img width="1072" alt="screen shot 2017-09-20 at 09 39 19" src="https://user-images.githubusercontent.com/211411/30632225-a6096748-9de7-11e7-80ee-d77b8f5fdd3b.png">

**Comment by longpq18** [comment]
It's error in Android

**Comment by gre** [comment]
i just pushed a new version of the app, maybe it solved it? try to clean the cache and everything, but it works for me
