### ISSUE TITLE
How to Take a long shot?

### ISSUE THREAD

**Issue by Taym95** [gre/react-native-view-shot#99]
I am using view shot to take long shot for all my ScrollView but I am getting just first part
There is any solution to do that? 

```
<ViewShot onCapture={this.onCapture} >
                    <ScrollView>
                            <Text>
                              Long Text ......
                            </Text>
                    </ScrollView>
</ViewShot>
```

**Comment by gre** [comment]
there are 2 solutions, either the one you suggested in the PR,

or you can snapshot the ScrollView with `snapshotContentContainer` on.. in this case you need a ref of the scrollview that you can pass to snapshotRef() imperative API (i don't think you can use ViewShot if using snapshotContentContainer approach).

**Comment by Mitesh-2009** [comment]
> there are 2 solutions, either the one you suggested in the PR,
> 
> or you can snapshot the ScrollView with `snapshotContentContainer` on.. in this case you need a ref of the scrollview that you can pass to snapshotRef() imperative API (i don't think you can use ViewShot if using snapshotContentContainer approach).
> 
> ```
> <ScrollView ref="foo">
> ```
> 
> ```js
> captureRef(this.refs.foo, { snapshotContentContainer: true })
> ```

not working
